
#define ARGS(...)
#define LIB_PROC(rv, name, args) 
#endif
#ifndef LIB_PROC
LIB_PROC(char *, eglGetDisplayDriverConfig, ARGS(EGLDisplay dpy))
LIB_PROC(const char *, eglGetDisplayDriverName, ARGS(EGLDisplay dpy))
LIB_PROC(const char*, eglQueryDeviceStringEXT, ARGS(EGLDeviceEXT device, EGLint name))
LIB_PROC(const char *, eglQueryOutputLayerStringEXT, ARGS(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint name))
LIB_PROC(const char *, eglQueryOutputPortStringEXT, ARGS(EGLDisplay dpy, EGLOutputPortEXT port, EGLint name))
LIB_PROC(constchar *, eglQueryString, ARGS(EGLDisplay dpy, EGLint name))
LIB_PROC(EGLBoolean, eglBindAPI, ARGS(EGLenum api))
LIB_PROC(EGLBoolean, eglBindTexImage, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint buffer))
LIB_PROC(EGLBoolean, eglBindWaylandDisplayWL, ARGS(EGLDisplay dpy, struct wl_display *display))
LIB_PROC(EGLBoolean, eglChooseConfig, ARGS(EGLDisplay dpy, const EGLint *attrib_list, EGLConfig *configs, EGLint config_size, EGLint *num_config))
LIB_PROC(EGLBoolean, eglClientSignalSyncEXT, ARGS(EGLDisplay dpy, EGLSync sync, const EGLAttrib *attrib_list))
LIB_PROC(EGLBoolean, eglCompositorBindTexWindowEXT, ARGS(EGLint external_win_id))
LIB_PROC(EGLBoolean, eglCompositorSetContextAttributesEXT, ARGS(EGLint external_ref_id, const EGLint *context_attributes, EGLint num_entries))
LIB_PROC(EGLBoolean, eglCompositorSetContextListEXT, ARGS(const EGLint *external_ref_ids, EGLint num_entries))
LIB_PROC(EGLBoolean, eglCompositorSetSizeEXT, ARGS(EGLint external_win_id, EGLint width, EGLint height))
LIB_PROC(EGLBoolean, eglCompositorSetWindowAttributesEXT, ARGS(EGLint external_win_id, const EGLint *window_attributes, EGLint num_entries))
LIB_PROC(EGLBoolean, eglCompositorSetWindowListEXT, ARGS(EGLint external_ref_id, const EGLint *external_win_ids, EGLint num_entries))
LIB_PROC(EGLBoolean, eglCompositorSwapPolicyEXT, ARGS(EGLint external_win_id, EGLint policy))
LIB_PROC(EGLBoolean, eglCopyBuffers, ARGS(EGLDisplay dpy, EGLSurface surface, EGLNativePixmapType target))
LIB_PROC(EGLBoolean, eglDestroyContext, ARGS(EGLDisplay dpy, EGLContext ctx))
LIB_PROC(EGLBoolean, eglDestroyImage, ARGS(EGLDisplay dpy, EGLImage image))
LIB_PROC(EGLBoolean, eglDestroyImageKHR, ARGS(EGLDisplay dpy, EGLImageKHR image))
LIB_PROC(EGLBoolean, eglDestroyStreamKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLBoolean, eglDestroySurface, ARGS(EGLDisplay dpy, EGLSurface surface))
LIB_PROC(EGLBoolean, eglDestroySync, ARGS(EGLDisplay dpy, EGLSync sync))
LIB_PROC(EGLBoolean, eglDestroySyncKHR, ARGS(EGLDisplay dpy, EGLSyncKHR sync))
LIB_PROC(EGLBoolean, eglDestroySyncNV, ARGS(EGLSyncNV sync))
LIB_PROC(EGLBoolean, eglExportDMABUFImageMESA, ARGS(EGLDisplay dpy, EGLImageKHR image, int *fds, EGLint *strides, EGLint *offsets))
LIB_PROC(EGLBoolean, eglExportDMABUFImageQueryMESA, ARGS(EGLDisplay dpy, EGLImageKHR image, int *fourcc, int *num_planes, EGLuint64KHR *modifiers))
LIB_PROC(EGLBoolean, eglExportDRMImageMESA, ARGS(EGLDisplay dpy, EGLImageKHR image, EGLint *name, EGLint *handle, EGLint *stride))
LIB_PROC(EGLBoolean, eglFenceNV, ARGS(EGLSyncNV sync))
LIB_PROC(EGLBoolean, eglGetCompositorTimingANDROID, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint numTimestamps, const EGLint *names, EGLnsecsANDROID *values))
LIB_PROC(EGLBoolean, eglGetCompositorTimingSupportedANDROID, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint name))
LIB_PROC(EGLBoolean, eglGetConfigAttrib, ARGS(EGLDisplay dpy, EGLConfig config, EGLint attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglGetConfigs, ARGS(EGLDisplay dpy, EGLConfig *configs, EGLint config_size, EGLint *num_config))
LIB_PROC(EGLBoolean, eglGetFrameTimestampsANDROID, ARGS(EGLDisplay dpy, EGLSurface surface, EGLuint64KHR frameId, EGLint numTimestamps, const EGLint *timestamps, EGLnsecsANDROID *values))
LIB_PROC(EGLBoolean, eglGetFrameTimestampSupportedANDROID, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint timestamp))
LIB_PROC(EGLBoolean, eglGetNextFrameIdANDROID, ARGS(EGLDisplay dpy, EGLSurface surface, EGLuint64KHR *frameId))
LIB_PROC(EGLBoolean, eglGetOutputLayersEXT, ARGS(EGLDisplay dpy, const EGLAttrib *attrib_list, EGLOutputLayerEXT *layers, EGLint max_layers, EGLint *num_layers))
LIB_PROC(EGLBoolean, eglGetOutputPortsEXT, ARGS(EGLDisplay dpy, const EGLAttrib *attrib_list, EGLOutputPortEXT *ports, EGLint max_ports, EGLint *num_ports))
LIB_PROC(EGLBoolean, eglGetSyncAttrib, ARGS(EGLDisplay dpy, EGLSync sync, EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglGetSyncAttribKHR, ARGS(EGLDisplay dpy, EGLSyncKHR sync, EGLint attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglGetSyncAttribNV, ARGS(EGLSyncNV sync, EGLint attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglInitialize, ARGS(EGLDisplay dpy, EGLint *major, EGLint *minor))
LIB_PROC(EGLBoolean, eglLockSurfaceKHR, ARGS(EGLDisplay dpy, EGLSurface surface, const EGLint *attrib_list))
LIB_PROC(EGLBoolean, eglMakeCurrent, ARGS(EGLDisplay dpy, EGLSurface draw, EGLSurface read, EGLContext ctx))
LIB_PROC(EGLBoolean, eglOutputLayerAttribEXT, ARGS(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib value))
LIB_PROC(EGLBoolean, eglOutputPortAttribEXT, ARGS(EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib value))
LIB_PROC(EGLBoolean, eglPostSubBufferNV, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint x, EGLint y, EGLint width, EGLint height))
LIB_PROC(EGLBoolean, eglPresentationTimeANDROID, ARGS(EGLDisplay dpy, EGLSurface surface, EGLnsecsANDROID time))
LIB_PROC(EGLBoolean, eglQueryContext, ARGS(EGLDisplay dpy, EGLContext ctx, EGLint attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglQueryDebugKHR, ARGS(EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryDeviceAttribEXT, ARGS(EGLDeviceEXT device, EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryDevicesEXT, ARGS(EGLint max_devices, EGLDeviceEXT *devices, EGLint *num_devices))
LIB_PROC(EGLBoolean, eglQueryDisplayAttribEXT, ARGS(EGLDisplay dpy, EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryDisplayAttribKHR, ARGS(EGLDisplay dpy, EGLint name, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryDisplayAttribNV, ARGS(EGLDisplay dpy, EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryDmaBufFormatsEXT, ARGS(EGLDisplay dpy, EGLint max_formats, EGLint *formats, EGLint *num_formats))
LIB_PROC(EGLBoolean, eglQueryDmaBufModifiersEXT, ARGS(EGLDisplay dpy, EGLint format, EGLint max_modifiers, EGLuint64KHR *modifiers, EGLBoolean *external_only, EGLint *num_modifiers))
LIB_PROC(EGLBoolean, eglQueryNativeDisplayNV, ARGS(EGLDisplay dpy, EGLNativeDisplayType *display_id))
LIB_PROC(EGLBoolean, eglQueryNativePixmapNV, ARGS(EGLDisplay dpy, EGLSurface surf, EGLNativePixmapType *pixmap))
LIB_PROC(EGLBoolean, eglQueryNativeWindowNV, ARGS(EGLDisplay dpy, EGLSurface surf, EGLNativeWindowType *window))
LIB_PROC(EGLBoolean, eglQueryOutputLayerAttribEXT, ARGS(EGLDisplay dpy, EGLOutputLayerEXT layer, EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryOutputPortAttribEXT, ARGS(EGLDisplay dpy, EGLOutputPortEXT port, EGLint attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryStreamAttribKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib *value))
LIB_PROC(EGLBoolean, eglQueryStreamKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglQueryStreamMetadataNV, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum name, EGLint n, EGLint offset, EGLint size, void *data))
LIB_PROC(EGLBoolean, eglQueryStreamTimeKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLTimeKHR *value))
LIB_PROC(EGLBoolean, eglQueryStreamu64KHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLuint64KHR *value))
LIB_PROC(EGLBoolean, eglQuerySurface64KHR, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLAttribKHR *value))
LIB_PROC(EGLBoolean, eglQuerySurface, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglQuerySurfacePointerANGLE, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint attribute, void **value))
LIB_PROC(EGLBoolean, eglQueryWaylandBufferWL, ARGS(EGLDisplay dpy, struct wl_resource *buffer, EGLint attribute, EGLint *value))
LIB_PROC(EGLBoolean, eglReleaseTexImage, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint buffer))
LIB_PROC(EGLBoolean, eglReleaseThread, ARGS(void))
LIB_PROC(EGLBoolean, eglResetStreamNV, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLBoolean, eglSetDamageRegionKHR, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint *rects, EGLint n_rects))
LIB_PROC(EGLBoolean, eglSetStreamAttribKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLAttrib value))
LIB_PROC(EGLBoolean, eglSetStreamMetadataNV, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLint n, EGLint offset, EGLint size, const void *data))
LIB_PROC(EGLBoolean, eglSignalSyncKHR, ARGS(EGLDisplay dpy, EGLSyncKHR sync, EGLenum mode))
LIB_PROC(EGLBoolean, eglSignalSyncNV, ARGS(EGLSyncNV sync, EGLenum mode))
LIB_PROC(EGLBoolean, eglStreamAttribKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum attribute, EGLint value))
LIB_PROC(EGLBoolean, eglStreamConsumerAcquireAttribKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib *attrib_list))
LIB_PROC(EGLBoolean, eglStreamConsumerAcquireKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLBoolean, eglStreamConsumerGLTextureExternalAttribsNV, ARGS(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib *attrib_list))
LIB_PROC(EGLBoolean, eglStreamConsumerGLTextureExternalKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLBoolean, eglStreamConsumerOutputEXT, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLOutputLayerEXT layer))
LIB_PROC(EGLBoolean, eglStreamConsumerReleaseAttribKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream, const EGLAttrib *attrib_list))
LIB_PROC(EGLBoolean, eglStreamConsumerReleaseKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLBoolean, eglStreamFlushNV, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLBoolean, eglSurfaceAttrib, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint attribute, EGLint value))
LIB_PROC(EGLBoolean, eglSwapBuffers, ARGS(EGLDisplay dpy, EGLSurface surface))
LIB_PROC(EGLBoolean, eglSwapBuffersRegion2NOK, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint *rects))
LIB_PROC(EGLBoolean, eglSwapBuffersRegionNOK, ARGS(EGLDisplay dpy, EGLSurface surface, EGLint numRects, const EGLint *rects))
LIB_PROC(EGLBoolean, eglSwapBuffersWithDamageEXT, ARGS(EGLDisplay dpy, EGLSurface surface, const EGLint *rects, EGLint n_rects))
LIB_PROC(EGLBoolean, eglSwapBuffersWithDamageKHR, ARGS(EGLDisplay dpy, EGLSurface surface, const EGLint *rects, EGLint n_rects))
LIB_PROC(EGLBoolean, eglSwapInterval, ARGS(EGLDisplay dpy, EGLint interval))
LIB_PROC(EGLBoolean, eglTerminate, ARGS(EGLDisplay dpy))
LIB_PROC(EGLBoolean, eglUnbindWaylandDisplayWL, ARGS(EGLDisplay dpy, struct wl_display *display))
LIB_PROC(EGLBoolean, eglUnlockSurfaceKHR, ARGS(EGLDisplay dpy, EGLSurface surface))
LIB_PROC(EGLBoolean, eglUnsignalSyncEXT, ARGS(EGLDisplay dpy, EGLSync sync, const EGLAttrib *attrib_list))
LIB_PROC(EGLBoolean, eglWaitClient, ARGS(void))
LIB_PROC(EGLBoolean, eglWaitGL, ARGS(void))
LIB_PROC(EGLBoolean, eglWaitNative, ARGS(EGLint engine))
LIB_PROC(EGLBoolean, eglWaitSync, ARGS(EGLDisplay dpy, EGLSync sync, EGLint flags))
LIB_PROC(EGLClientBuffer, eglCreateNativeClientBufferANDROID, ARGS(const EGLint *attrib_list))
LIB_PROC(EGLClientBuffer, eglGetNativeClientBufferANDROID, ARGS(const struct AHardwareBuffer *buffer))
LIB_PROC(EGLContext, eglCreateContext, ARGS(EGLDisplay dpy, EGLConfig config, EGLContext share_context, const EGLint *attrib_list))
LIB_PROC(EGLContext, eglGetCurrentContext, ARGS(void))
LIB_PROC(EGLDisplay, eglGetCurrentDisplay, ARGS(void))
LIB_PROC(EGLDisplay, eglGetDisplay, ARGS(EGLNativeDisplayType display_id))
LIB_PROC(EGLDisplay, eglGetPlatformDisplay, ARGS(EGLenum platform, void *native_display, const EGLAttrib *attrib_list))
LIB_PROC(EGLDisplay, eglGetPlatformDisplayEXT, ARGS(EGLenum platform, void *native_display, const EGLint *attrib_list))
LIB_PROC(EGLenum, eglQueryAPI, ARGS(void))
LIB_PROC(EGLImage, eglCreateImage, ARGS(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLAttrib *attrib_list))
LIB_PROC(EGLImageKHR, eglCreateDRMImageMESA, ARGS(EGLDisplay dpy, const EGLint *attrib_list))
LIB_PROC(EGLImageKHR, eglCreateImageKHR, ARGS(EGLDisplay dpy, EGLContext ctx, EGLenum target, EGLClientBuffer buffer, const EGLint *attrib_list))
LIB_PROC(EGLint, eglClientWaitSync, ARGS(EGLDisplay dpy, EGLSync sync, EGLint flags, EGLTime timeout))
LIB_PROC(EGLint, eglClientWaitSyncKHR, ARGS(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags, EGLTimeKHR timeout))
LIB_PROC(EGLint, eglClientWaitSyncNV, ARGS(EGLSyncNV sync, EGLint flags, EGLTimeNV timeout))
LIB_PROC(EGLint, eglDebugMessageControlKHR, ARGS(EGLDEBUGPROCKHR callback, const EGLAttrib *attrib_list))
LIB_PROC(EGLint, eglDupNativeFenceFDANDROID, ARGS(EGLDisplay dpy, EGLSyncKHR sync))
LIB_PROC(EGLint, eglGetError, ARGS(void))
LIB_PROC(EGLint, eglLabelObjectKHR, ARGS(EGLDisplay display, EGLenum objectType, EGLObjectKHR object, EGLLabelKHR label))
LIB_PROC(EGLint, eglWaitSyncKHR, ARGS(EGLDisplay dpy, EGLSyncKHR sync, EGLint flags))
LIB_PROC(__eglMustCastToProperFunctionPointerType, eglGetProcAddress, ARGS(const char *procname))
LIB_PROC(EGLNativeFileDescriptorKHR, eglGetStreamFileDescriptorKHR, ARGS(EGLDisplay dpy, EGLStreamKHR stream))
LIB_PROC(EGLStreamKHR, eglCreateStreamAttribKHR, ARGS(EGLDisplay dpy, const EGLAttrib *attrib_list))
LIB_PROC(EGLStreamKHR, eglCreateStreamFromFileDescriptorKHR, ARGS(EGLDisplay dpy, EGLNativeFileDescriptorKHR file_descriptor))
LIB_PROC(EGLStreamKHR, eglCreateStreamKHR, ARGS(EGLDisplay dpy, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreatePbufferFromClientBuffer, ARGS(EGLDisplay dpy, EGLenum buftype, EGLClientBuffer buffer, EGLConfig config, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreatePbufferSurface, ARGS(EGLDisplay dpy, EGLConfig config, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreatePixmapSurface, ARGS(EGLDisplay dpy, EGLConfig config, EGLNativePixmapType pixmap, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreatePixmapSurfaceHI, ARGS(EGLDisplay dpy, EGLConfig config, struct EGLClientPixmapHI *pixmap))
LIB_PROC(EGLSurface, eglCreatePlatformPixmapSurface, ARGS(EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLAttrib *attrib_list))
LIB_PROC(EGLSurface, eglCreatePlatformPixmapSurfaceEXT, ARGS(EGLDisplay dpy, EGLConfig config, void *native_pixmap, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreatePlatformWindowSurface, ARGS(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLAttrib *attrib_list))
LIB_PROC(EGLSurface, eglCreatePlatformWindowSurfaceEXT, ARGS(EGLDisplay dpy, EGLConfig config, void *native_window, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreateStreamProducerSurfaceKHR, ARGS(EGLDisplay dpy, EGLConfig config, EGLStreamKHR stream, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglCreateWindowSurface, ARGS(EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list))
LIB_PROC(EGLSurface, eglGetCurrentSurface, ARGS(EGLint readdraw))
LIB_PROC(EGLSync, eglCreateSync, ARGS(EGLDisplay dpy, EGLenum type, const EGLAttrib *attrib_list))
LIB_PROC(EGLSyncKHR, eglCreateStreamSyncNV, ARGS(EGLDisplay dpy, EGLStreamKHR stream, EGLenum type, const EGLint *attrib_list))
LIB_PROC(EGLSyncKHR, eglCreateSync64KHR, ARGS(EGLDisplay dpy, EGLenum type, const EGLAttribKHR *attrib_list))
LIB_PROC(EGLSyncKHR, eglCreateSyncKHR, ARGS(EGLDisplay dpy, EGLenum type, const EGLint *attrib_list))
LIB_PROC(EGLSyncNV, eglCreateFenceSyncNV, ARGS(EGLDisplay dpy, EGLenum condition, const EGLint *attrib_list))
LIB_PROC(EGLuint64NV, eglGetSystemTimeFrequencyNV, ARGS(void))
LIB_PROC(EGLuint64NV, eglGetSystemTimeNV, ARGS(void))
LIB_PROC(struct wl_buffer *, eglCreateWaylandBufferFromImageWL, ARGS(EGLDisplay dpy, EGLImageKHR image))
LIB_PROC(void, eglSetBlobCacheFuncsANDROID, ARGS(EGLDisplay dpy, EGLSetBlobFuncANDROID set, EGLGetBlobFuncANDROID get))
