
#ifndef LIB_PROC
#define ARGS(...)
#define LIB_PROC(rv, name, args) 
#endif

LIB_PROC(const GLubyte *, glGetString, ARGS(GLenum name))
LIB_PROC(GLbitfield, glQueryMatrixxOES, ARGS(GLfixed *mantissa, GLint *exponent))
LIB_PROC(GLboolean, glExtIsProgramBinaryQCOM, ARGS(GLuint program))
LIB_PROC(GLboolean, glIsBuffer, ARGS(GLuint buffer))
LIB_PROC(GLboolean, glIsEnabled, ARGS(GLenum cap))
LIB_PROC(GLboolean, glIsFenceNV, ARGS(GLuint fence))
LIB_PROC(GLboolean, glIsFramebufferOES, ARGS(GLuint framebuffer))
LIB_PROC(GLboolean, glIsRenderbufferOES, ARGS(GLuint renderbuffer))
LIB_PROC(GLboolean, glIsSyncAPPLE, ARGS(GLsync sync))
LIB_PROC(GLboolean, glIsTexture, ARGS(GLuint texture))
LIB_PROC(GLboolean, glIsVertexArrayOES, ARGS(GLuint array))
LIB_PROC(GLboolean, glTestFenceNV, ARGS(GLuint fence))
LIB_PROC(GLboolean, glUnmapBufferOES, ARGS(GLenum target))
LIB_PROC(GLenum, glCheckFramebufferStatusOES, ARGS(GLenum target))
LIB_PROC(GLenum, glClientWaitSyncAPPLE, ARGS(GLsync sync, GLbitfield flags, GLuint64 timeout))
LIB_PROC(GLenum, glGetError, ARGS(void))
LIB_PROC(GLenum, glGetGraphicsResetStatusEXT, ARGS(void))
LIB_PROC(GLsync, glFenceSyncAPPLE, ARGS(GLenum condition, GLbitfield flags))
LIB_PROC(void, glActiveTexture, ARGS(GLenum texture))
LIB_PROC(void, glAlphaFunc, ARGS(GLenum func, GLfloat ref))
LIB_PROC(void, glAlphaFuncx, ARGS(GLenum func, GLfixed ref))
LIB_PROC(void, glAlphaFuncxOES, ARGS(GLenum func, GLfixed ref))
LIB_PROC(void, glBindBuffer, ARGS(GLenum target, GLuint buffer))
LIB_PROC(void, glBindFramebufferOES, ARGS(GLenum target, GLuint framebuffer))
LIB_PROC(void, glBindRenderbufferOES, ARGS(GLenum target, GLuint renderbuffer))
LIB_PROC(void, glBindTexture, ARGS(GLenum target, GLuint texture))
LIB_PROC(void, glBindVertexArrayOES, ARGS(GLuint array))
LIB_PROC(void, glBlendEquationOES, ARGS(GLenum mode))
LIB_PROC(void, glBlendEquationSeparateOES, ARGS(GLenum modeRGB, GLenum modeAlpha))
LIB_PROC(void, glBlendFunc, ARGS(GLenum sfactor, GLenum dfactor))
LIB_PROC(void, glBlendFuncSeparateOES, ARGS(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha))
LIB_PROC(void, glBufferData, ARGS(GLenum target, GLsizeiptr size, const void *data, GLenum usage))
LIB_PROC(void, glBufferSubData, ARGS(GLenum target, GLintptr offset, GLsizeiptr size, const void *data))
LIB_PROC(void, glClear, ARGS(GLbitfield mask))
LIB_PROC(void, glClearColor, ARGS(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
LIB_PROC(void, glClearColorx, ARGS(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
LIB_PROC(void, glClearColorxOES, ARGS(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
LIB_PROC(void, glClearDepthf, ARGS(GLfloat d))
LIB_PROC(void, glClearDepthfOES, ARGS(GLclampf depth))
LIB_PROC(void, glClearDepthx, ARGS(GLfixed depth))
LIB_PROC(void, glClearDepthxOES, ARGS(GLfixed depth))
LIB_PROC(void, glClearStencil, ARGS(GLint s))
LIB_PROC(void, glClientActiveTexture, ARGS(GLenum texture))
LIB_PROC(void, glClipPlanef, ARGS(GLenum p, const GLfloat *eqn))
LIB_PROC(void, glClipPlanefIMG, ARGS(GLenum p, const GLfloat *eqn))
LIB_PROC(void, glClipPlanefOES, ARGS(GLenum plane, const GLfloat *equation))
LIB_PROC(void, glClipPlanex, ARGS(GLenum plane, const GLfixed *equation))
LIB_PROC(void, glClipPlanexIMG, ARGS(GLenum p, const GLfixed *eqn))
LIB_PROC(void, glClipPlanexOES, ARGS(GLenum plane, const GLfixed *equation))
LIB_PROC(void, glColor4f, ARGS(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
LIB_PROC(void, glColor4ub, ARGS(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha))
LIB_PROC(void, glColor4x, ARGS(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
LIB_PROC(void, glColor4xOES, ARGS(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha))
LIB_PROC(void, glColorMask, ARGS(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
LIB_PROC(void, glColorPointer, ARGS(GLint size, GLenum type, GLsizei stride, const void *pointer))
LIB_PROC(void, glCompressedTexImage2D, ARGS(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data))
LIB_PROC(void, glCompressedTexSubImage2D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data))
LIB_PROC(void, glCopyTexImage2D, ARGS(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
LIB_PROC(void, glCopyTexSubImage2D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glCopyTextureLevelsAPPLE, ARGS(GLuint destinationTexture, GLuint sourceTexture, GLint sourceBaseLevel, GLsizei sourceLevelCount))
LIB_PROC(void, glCullFace, ARGS(GLenum mode))
LIB_PROC(void, glCurrentPaletteMatrixOES, ARGS(GLuint matrixpaletteindex))
LIB_PROC(void, glDeleteBuffers, ARGS(GLsizei n, const GLuint *buffers))
LIB_PROC(void, glDeleteFencesNV, ARGS(GLsizei n, const GLuint *fences))
LIB_PROC(void, glDeleteFramebuffersOES, ARGS(GLsizei n, const GLuint *framebuffers))
LIB_PROC(void, glDeleteRenderbuffersOES, ARGS(GLsizei n, const GLuint *renderbuffers))
LIB_PROC(void, glDeleteSyncAPPLE, ARGS(GLsync sync))
LIB_PROC(void, glDeleteTextures, ARGS(GLsizei n, const GLuint *textures))
LIB_PROC(void, glDeleteVertexArraysOES, ARGS(GLsizei n, const GLuint *arrays))
LIB_PROC(void, glDepthFunc, ARGS(GLenum func))
LIB_PROC(void, glDepthMask, ARGS(GLboolean flag))
LIB_PROC(void, glDepthRangef, ARGS(GLfloat n, GLfloat f))
LIB_PROC(void, glDepthRangefOES, ARGS(GLclampf n, GLclampf f))
LIB_PROC(void, glDepthRangex, ARGS(GLfixed n, GLfixed f))
LIB_PROC(void, glDepthRangexOES, ARGS(GLfixed n, GLfixed f))
LIB_PROC(void, glDisable, ARGS(GLenum cap))
LIB_PROC(void, glDisableClientState, ARGS(GLenum array))
LIB_PROC(void, glDisableDriverControlQCOM, ARGS(GLuint driverControl))
LIB_PROC(void, glDiscardFramebufferEXT, ARGS(GLenum target, GLsizei numAttachments, const GLenum *attachments))
LIB_PROC(void, glDrawArrays, ARGS(GLenum mode, GLint first, GLsizei count))
LIB_PROC(void, glDrawElements, ARGS(GLenum mode, GLsizei count, GLenum type, const void *indices))
LIB_PROC(void, glDrawTexfOES, ARGS(GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height))
LIB_PROC(void, glDrawTexfvOES, ARGS(const GLfloat *coords))
LIB_PROC(void, glDrawTexiOES, ARGS(GLint x, GLint y, GLint z, GLint width, GLint height))
LIB_PROC(void, glDrawTexivOES, ARGS(const GLint *coords))
LIB_PROC(void, glDrawTexsOES, ARGS(GLshort x, GLshort y, GLshort z, GLshort width, GLshort height))
LIB_PROC(void, glDrawTexsvOES, ARGS(const GLshort *coords))
LIB_PROC(void, glDrawTexxOES, ARGS(GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height))
LIB_PROC(void, glDrawTexxvOES, ARGS(const GLfixed *coords))
LIB_PROC(void, glEGLImageTargetRenderbufferStorageOES, ARGS(GLenum target, GLeglImageOES image))
LIB_PROC(void, glEGLImageTargetTexture2DOES, ARGS(GLenum target, GLeglImageOES image))
LIB_PROC(void, glEnable, ARGS(GLenum cap))
LIB_PROC(void, glEnableClientState, ARGS(GLenum array))
LIB_PROC(void, glEnableDriverControlQCOM, ARGS(GLuint driverControl))
LIB_PROC(void, glEndTilingQCOM, ARGS(GLbitfield preserveMask))
LIB_PROC(void, glExtGetBufferPointervQCOM, ARGS(GLenum target, void **params))
LIB_PROC(void, glExtGetBuffersQCOM, ARGS(GLuint *buffers, GLint maxBuffers, GLint *numBuffers))
LIB_PROC(void, glExtGetFramebuffersQCOM, ARGS(GLuint *framebuffers, GLint maxFramebuffers, GLint *numFramebuffers))
LIB_PROC(void, glExtGetProgramBinarySourceQCOM, ARGS(GLuint program, GLenum shadertype, GLchar *source, GLint *length))
LIB_PROC(void, glExtGetProgramsQCOM, ARGS(GLuint *programs, GLint maxPrograms, GLint *numPrograms))
LIB_PROC(void, glExtGetRenderbuffersQCOM, ARGS(GLuint *renderbuffers, GLint maxRenderbuffers, GLint *numRenderbuffers))
LIB_PROC(void, glExtGetShadersQCOM, ARGS(GLuint *shaders, GLint maxShaders, GLint *numShaders))
LIB_PROC(void, glExtGetTexLevelParameterivQCOM, ARGS(GLuint texture, GLenum face, GLint level, GLenum pname, GLint *params))
LIB_PROC(void, glExtGetTexSubImageQCOM, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, void *texels))
LIB_PROC(void, glExtGetTexturesQCOM, ARGS(GLuint *textures, GLint maxTextures, GLint *numTextures))
LIB_PROC(void, glExtTexObjectStateOverrideiQCOM, ARGS(GLenum target, GLenum pname, GLint param))
LIB_PROC(void, glFinish, ARGS(void))
LIB_PROC(void, glFinishFenceNV, ARGS(GLuint fence))
LIB_PROC(void, glFlush, ARGS(void))
LIB_PROC(void, glFlushMappedBufferRangeEXT, ARGS(GLenum target, GLintptr offset, GLsizeiptr length))
LIB_PROC(void, glFogf, ARGS(GLenum pname, GLfloat param))
LIB_PROC(void, glFogfv, ARGS(GLenum pname, const GLfloat *params))
LIB_PROC(void, glFogx, ARGS(GLenum pname, GLfixed param))
LIB_PROC(void, glFogxOES, ARGS(GLenum pname, GLfixed param))
LIB_PROC(void, glFogxv, ARGS(GLenum pname, const GLfixed *param))
LIB_PROC(void, glFogxvOES, ARGS(GLenum pname, const GLfixed *param))
LIB_PROC(void, glFramebufferRenderbufferOES, ARGS(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
LIB_PROC(void, glFramebufferTexture2DMultisampleEXT, ARGS(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLsizei samples))
LIB_PROC(void, glFramebufferTexture2DMultisampleIMG, ARGS(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLsizei samples))
LIB_PROC(void, glFramebufferTexture2DOES, ARGS(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
LIB_PROC(void, glFrontFace, ARGS(GLenum mode))
LIB_PROC(void, glFrustumf, ARGS(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f))
LIB_PROC(void, glFrustumfOES, ARGS(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f))
LIB_PROC(void, glFrustumx, ARGS(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f))
LIB_PROC(void, glFrustumxOES, ARGS(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f))
LIB_PROC(void, glGenBuffers, ARGS(GLsizei n, GLuint *buffers))
LIB_PROC(void, glGenerateMipmapOES, ARGS(GLenum target))
LIB_PROC(void, glGenFencesNV, ARGS(GLsizei n, GLuint *fences))
LIB_PROC(void, glGenFramebuffersOES, ARGS(GLsizei n, GLuint *framebuffers))
LIB_PROC(void, glGenRenderbuffersOES, ARGS(GLsizei n, GLuint *renderbuffers))
LIB_PROC(void, glGenTextures, ARGS(GLsizei n, GLuint *textures))
LIB_PROC(void, glGenVertexArraysOES, ARGS(GLsizei n, GLuint *arrays))
LIB_PROC(void, glGetBooleanv, ARGS(GLenum pname, GLboolean *data))
LIB_PROC(void, glGetBufferParameteriv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetBufferPointervOES, ARGS(GLenum target, GLenum pname, void **params))
LIB_PROC(void, glGetClipPlanef, ARGS(GLenum plane, GLfloat *equation))
LIB_PROC(void, glGetClipPlanefOES, ARGS(GLenum plane, GLfloat *equation))
LIB_PROC(void, glGetClipPlanex, ARGS(GLenum plane, GLfixed *equation))
LIB_PROC(void, glGetClipPlanexOES, ARGS(GLenum plane, GLfixed *equation))
LIB_PROC(void, glGetDriverControlsQCOM, ARGS(GLint *num, GLsizei size, GLuint *driverControls))
LIB_PROC(void, glGetDriverControlStringQCOM, ARGS(GLuint driverControl, GLsizei bufSize, GLsizei *length, GLchar *driverControlString))
LIB_PROC(void, glGetFenceivNV, ARGS(GLuint fence, GLenum pname, GLint *params))
LIB_PROC(void, glGetFixedv, ARGS(GLenum pname, GLfixed *params))
LIB_PROC(void, glGetFixedvOES, ARGS(GLenum pname, GLfixed *params))
LIB_PROC(void, glGetFloatv, ARGS(GLenum pname, GLfloat *data))
LIB_PROC(void, glGetFramebufferAttachmentParameterivOES, ARGS(GLenum target, GLenum attachment, GLenum pname, GLint *params))
LIB_PROC(void, glGetInteger64vAPPLE, ARGS(GLenum pname, GLint64 *params))
LIB_PROC(void, glGetIntegerv, ARGS(GLenum pname, GLint *data))
LIB_PROC(void, glGetLightfv, ARGS(GLenum light, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetLightxv, ARGS(GLenum light, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetLightxvOES, ARGS(GLenum light, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetMaterialfv, ARGS(GLenum face, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetMaterialxv, ARGS(GLenum face, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetMaterialxvOES, ARGS(GLenum face, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetnUniformfvEXT, ARGS(GLuint program, GLint location, GLsizei bufSize, GLfloat *params))
LIB_PROC(void, glGetnUniformivEXT, ARGS(GLuint program, GLint location, GLsizei bufSize, GLint *params))
LIB_PROC(void, glGetPointerv, ARGS(GLenum pname, void **params))
LIB_PROC(void, glGetRenderbufferParameterivOES, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetSyncivAPPLE, ARGS(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values))
LIB_PROC(void, glGetTexEnvfv, ARGS(GLenum target, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetTexEnviv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetTexEnvxv, ARGS(GLenum target, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetTexEnvxvOES, ARGS(GLenum target, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetTexGenfvOES, ARGS(GLenum coord, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetTexGenivOES, ARGS(GLenum coord, GLenum pname, GLint *params))
LIB_PROC(void, glGetTexGenxvOES, ARGS(GLenum coord, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetTexParameterfv, ARGS(GLenum target, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetTexParameteriv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetTexParameterxv, ARGS(GLenum target, GLenum pname, GLfixed *params))
LIB_PROC(void, glGetTexParameterxvOES, ARGS(GLenum target, GLenum pname, GLfixed *params))
LIB_PROC(void, glHint, ARGS(GLenum target, GLenum mode))
LIB_PROC(void, glInsertEventMarkerEXT, ARGS(GLsizei length, const GLchar *marker))
LIB_PROC(void, glLightf, ARGS(GLenum light, GLenum pname, GLfloat param))
LIB_PROC(void, glLightfv, ARGS(GLenum light, GLenum pname, const GLfloat *params))
LIB_PROC(void, glLightModelf, ARGS(GLenum pname, GLfloat param))
LIB_PROC(void, glLightModelfv, ARGS(GLenum pname, const GLfloat *params))
LIB_PROC(void, glLightModelx, ARGS(GLenum pname, GLfixed param))
LIB_PROC(void, glLightModelxOES, ARGS(GLenum pname, GLfixed param))
LIB_PROC(void, glLightModelxv, ARGS(GLenum pname, const GLfixed *param))
LIB_PROC(void, glLightModelxvOES, ARGS(GLenum pname, const GLfixed *param))
LIB_PROC(void, glLightx, ARGS(GLenum light, GLenum pname, GLfixed param))
LIB_PROC(void, glLightxOES, ARGS(GLenum light, GLenum pname, GLfixed param))
LIB_PROC(void, glLightxv, ARGS(GLenum light, GLenum pname, const GLfixed *params))
LIB_PROC(void, glLightxvOES, ARGS(GLenum light, GLenum pname, const GLfixed *params))
LIB_PROC(void, glLineWidth, ARGS(GLfloat width))
LIB_PROC(void, glLineWidthx, ARGS(GLfixed width))
LIB_PROC(void, glLineWidthxOES, ARGS(GLfixed width))
LIB_PROC(void, glLoadIdentity, ARGS(void))
LIB_PROC(void, glLoadMatrixf, ARGS(const GLfloat *m))
LIB_PROC(void, glLoadMatrixx, ARGS(const GLfixed *m))
LIB_PROC(void, glLoadMatrixxOES, ARGS(const GLfixed *m))
LIB_PROC(void, glLoadPaletteFromModelViewMatrixOES, ARGS(void))
LIB_PROC(void, glLogicOp, ARGS(GLenum opcode))
LIB_PROC(void *, glMapBufferOES, ARGS(GLenum target, GLenum access))
LIB_PROC(void *, glMapBufferRangeEXT, ARGS(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access))
LIB_PROC(void, glMaterialf, ARGS(GLenum face, GLenum pname, GLfloat param))
LIB_PROC(void, glMaterialfv, ARGS(GLenum face, GLenum pname, const GLfloat *params))
LIB_PROC(void, glMaterialx, ARGS(GLenum face, GLenum pname, GLfixed param))
LIB_PROC(void, glMaterialxOES, ARGS(GLenum face, GLenum pname, GLfixed param))
LIB_PROC(void, glMaterialxv, ARGS(GLenum face, GLenum pname, const GLfixed *param))
LIB_PROC(void, glMaterialxvOES, ARGS(GLenum face, GLenum pname, const GLfixed *param))
LIB_PROC(void, glMatrixIndexPointerOES, ARGS(GLint size, GLenum type, GLsizei stride, const void *pointer))
LIB_PROC(void, glMatrixMode, ARGS(GLenum mode))
LIB_PROC(void, glMultiDrawArraysEXT, ARGS(GLenum mode, const GLint *first, const GLsizei *count, GLsizei primcount))
LIB_PROC(void, glMultiDrawElementsEXT, ARGS(GLenum mode, const GLsizei *count, GLenum type, const void *const*indices, GLsizei primcount))
LIB_PROC(void, glMultiTexCoord4f, ARGS(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q))
LIB_PROC(void, glMultiTexCoord4x, ARGS(GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q))
LIB_PROC(void, glMultiTexCoord4xOES, ARGS(GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q))
LIB_PROC(void, glMultMatrixf, ARGS(const GLfloat *m))
LIB_PROC(void, glMultMatrixx, ARGS(const GLfixed *m))
LIB_PROC(void, glMultMatrixxOES, ARGS(const GLfixed *m))
LIB_PROC(void, glNormal3f, ARGS(GLfloat nx, GLfloat ny, GLfloat nz))
LIB_PROC(void, glNormal3x, ARGS(GLfixed nx, GLfixed ny, GLfixed nz))
LIB_PROC(void, glNormal3xOES, ARGS(GLfixed nx, GLfixed ny, GLfixed nz))
LIB_PROC(void, glNormalPointer, ARGS(GLenum type, GLsizei stride, const void *pointer))
LIB_PROC(void, glOrthof, ARGS(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f))
LIB_PROC(void, glOrthofOES, ARGS(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f))
LIB_PROC(void, glOrthox, ARGS(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f))
LIB_PROC(void, glOrthoxOES, ARGS(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f))
LIB_PROC(void, glPixelStorei, ARGS(GLenum pname, GLint param))
LIB_PROC(void, glPointParameterf, ARGS(GLenum pname, GLfloat param))
LIB_PROC(void, glPointParameterfv, ARGS(GLenum pname, const GLfloat *params))
LIB_PROC(void, glPointParameterx, ARGS(GLenum pname, GLfixed param))
LIB_PROC(void, glPointParameterxOES, ARGS(GLenum pname, GLfixed param))
LIB_PROC(void, glPointParameterxv, ARGS(GLenum pname, const GLfixed *params))
LIB_PROC(void, glPointParameterxvOES, ARGS(GLenum pname, const GLfixed *params))
LIB_PROC(void, glPointSize, ARGS(GLfloat size))
LIB_PROC(void, glPointSizePointerOES, ARGS(GLenum type, GLsizei stride, const void *pointer))#ifndef LIB_PROC
LIB_PROC(void, glPointSizex, ARGS(GLfixed size))
LIB_PROC(void, glPointSizexOES, ARGS(GLfixed size))
LIB_PROC(void, glPolygonOffset, ARGS(GLfloat factor, GLfloat units))
LIB_PROC(void, glPolygonOffsetx, ARGS(GLfixed factor, GLfixed units))
LIB_PROC(void, glPolygonOffsetxOES, ARGS(GLfixed factor, GLfixed units))
LIB_PROC(void, glPopGroupMarkerEXT, ARGS(void))
LIB_PROC(void, glPopMatrix, ARGS(void))
LIB_PROC(void, glPushGroupMarkerEXT, ARGS(GLsizei length, const GLchar *marker))
LIB_PROC(void, glPushMatrix, ARGS(void))
LIB_PROC(void, glReadnPixelsEXT, ARGS(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data))
LIB_PROC(void, glReadPixels, ARGS(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels))
LIB_PROC(void, glRenderbufferStorageMultisampleAPPLE, ARGS(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glRenderbufferStorageMultisampleEXT, ARGS(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glRenderbufferStorageMultisampleIMG, ARGS(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glRenderbufferStorageOES, ARGS(GLenum target, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glResolveMultisampleFramebufferAPPLE, ARGS(void))
LIB_PROC(void, glRotatef, ARGS(GLfloat angle, GLfloat x, GLfloat y, GLfloat z))
LIB_PROC(void, glRotatex, ARGS(GLfixed angle, GLfixed x, GLfixed y, GLfixed z))
LIB_PROC(void, glRotatexOES, ARGS(GLfixed angle, GLfixed x, GLfixed y, GLfixed z))
LIB_PROC(void, glSampleCoverage, ARGS(GLfloat value, GLboolean invert))
LIB_PROC(void, glSampleCoveragex, ARGS(GLclampx value, GLboolean invert))
LIB_PROC(void, glSampleCoveragexOES, ARGS(GLclampx value, GLboolean invert))
LIB_PROC(void, glScalef, ARGS(GLfloat x, GLfloat y, GLfloat z))
LIB_PROC(void, glScalex, ARGS(GLfixed x, GLfixed y, GLfixed z))
LIB_PROC(void, glScalexOES, ARGS(GLfixed x, GLfixed y, GLfixed z))
LIB_PROC(void, glScissor, ARGS(GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glSetFenceNV, ARGS(GLuint fence, GLenum condition))
LIB_PROC(void, glShadeModel, ARGS(GLenum mode))
LIB_PROC(void, glStartTilingQCOM, ARGS(GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask))
LIB_PROC(void, glStencilFunc, ARGS(GLenum func, GLint ref, GLuint mask))
LIB_PROC(void, glStencilMask, ARGS(GLuint mask))
LIB_PROC(void, glStencilOp, ARGS(GLenum fail, GLenum zfail, GLenum zpass))
LIB_PROC(void, glTexCoordPointer, ARGS(GLint size, GLenum type, GLsizei stride, const void *pointer))
LIB_PROC(void, glTexEnvf, ARGS(GLenum target, GLenum pname, GLfloat param))
LIB_PROC(void, glTexEnvfv, ARGS(GLenum target, GLenum pname, const GLfloat *params))
LIB_PROC(void, glTexEnvi, ARGS(GLenum target, GLenum pname, GLint param))
LIB_PROC(void, glTexEnviv, ARGS(GLenum target, GLenum pname, const GLint *params))
LIB_PROC(void, glTexEnvx, ARGS(GLenum target, GLenum pname, GLfixed param))
LIB_PROC(void, glTexEnvxOES, ARGS(GLenum target, GLenum pname, GLfixed param))
LIB_PROC(void, glTexEnvxv, ARGS(GLenum target, GLenum pname, const GLfixed *params))
LIB_PROC(void, glTexEnvxvOES, ARGS(GLenum target, GLenum pname, const GLfixed *params))
LIB_PROC(void, glTexGenfOES, ARGS(GLenum coord, GLenum pname, GLfloat param))
LIB_PROC(void, glTexGenfvOES, ARGS(GLenum coord, GLenum pname, const GLfloat *params))
LIB_PROC(void, glTexGeniOES, ARGS(GLenum coord, GLenum pname, GLint param))
LIB_PROC(void, glTexGenivOES, ARGS(GLenum coord, GLenum pname, const GLint *params))
LIB_PROC(void, glTexGenxOES, ARGS(GLenum coord, GLenum pname, GLfixed param))
LIB_PROC(void, glTexGenxvOES, ARGS(GLenum coord, GLenum pname, const GLfixed *params))
LIB_PROC(void, glTexImage2D, ARGS(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels))
LIB_PROC(void, glTexParameterf, ARGS(GLenum target, GLenum pname, GLfloat param))
LIB_PROC(void, glTexParameterfv, ARGS(GLenum target, GLenum pname, const GLfloat *params))
LIB_PROC(void, glTexParameteri, ARGS(GLenum target, GLenum pname, GLint param))
LIB_PROC(void, glTexParameteriv, ARGS(GLenum target, GLenum pname, const GLint *params))
LIB_PROC(void, glTexParameterx, ARGS(GLenum target, GLenum pname, GLfixed param))
LIB_PROC(void, glTexParameterxOES, ARGS(GLenum target, GLenum pname, GLfixed param))
LIB_PROC(void, glTexParameterxv, ARGS(GLenum target, GLenum pname, const GLfixed *params))
LIB_PROC(void, glTexParameterxvOES, ARGS(GLenum target, GLenum pname, const GLfixed *params))
LIB_PROC(void, glTexStorage1DEXT, ARGS(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width))
LIB_PROC(void, glTexStorage2DEXT, ARGS(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glTexStorage3DEXT, ARGS(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth))
LIB_PROC(void, glTexSubImage2D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels))
LIB_PROC(void, glTextureStorage1DEXT, ARGS(GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width))
LIB_PROC(void, glTextureStorage2DEXT, ARGS(GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glTextureStorage3DEXT, ARGS(GLuint texture, GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth))
LIB_PROC(void, glTranslatef, ARGS(GLfloat x, GLfloat y, GLfloat z))
LIB_PROC(void, glTranslatex, ARGS(GLfixed x, GLfixed y, GLfixed z))
LIB_PROC(void, glTranslatexOES, ARGS(GLfixed x, GLfixed y, GLfixed z))
LIB_PROC(void, glVertexPointer, ARGS(GLint size, GLenum type, GLsizei stride, const void *pointer))
LIB_PROC(void, glViewport, ARGS(GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glWaitSyncAPPLE, ARGS(GLsync sync, GLbitfield flags, GLuint64 timeout))
LIB_PROC(void, glWeightPointerOES, ARGS(GLint size, GLenum type, GLsizei stride, const void *pointer))
