#ifndef LIB_PROC
#define ARGS(...)
#define LIB_PROC(rv, name, args) 
#endif

LIB_PROC(const GLubyte *, glGetString, ARGS(GLenum name))
LIB_PROC(const GLubyte *, glGetString, ARGS(GLenum name))
LIB_PROC(const GLubyte *, glGetStringi, ARGS(GLenum name, GLuint index))
LIB_PROC(GLboolean, glIsBuffer, ARGS(GLuint buffer))
LIB_PROC(GLboolean, glIsEnabled, ARGS(GLenum cap))
LIB_PROC(GLboolean, glIsEnabledi, ARGS(GLenum target, GLuint index))
LIB_PROC(GLboolean, glIsFramebuffer, ARGS(GLuint framebuffer))
LIB_PROC(GLboolean, glIsProgram, ARGS(GLuint program))
LIB_PROC(GLboolean, glIsProgramPipeline, ARGS(GLuint pipeline))
LIB_PROC(GLboolean, glIsQuery, ARGS(GLuint id))
LIB_PROC(GLboolean, glIsRenderbuffer, ARGS(GLuint renderbuffer))
LIB_PROC(GLboolean, glIsSampler, ARGS(GLuint sampler))
LIB_PROC(GLboolean, glIsShader, ARGS(GLuint shader))
LIB_PROC(GLboolean, glIsSync, ARGS(GLsync sync))
LIB_PROC(GLboolean, glIsTexture, ARGS(GLuint texture))
LIB_PROC(GLboolean, glIsTransformFeedback, ARGS(GLuint id))
LIB_PROC(GLboolean, glIsVertexArray, ARGS(GLuint array))
LIB_PROC(GLboolean, glUnmapBuffer, ARGS(GLenum target))
LIB_PROC(GLenum, glCheckFramebufferStatus, ARGS(GLenum target))
LIB_PROC(GLenum, glClientWaitSync, ARGS(GLsync sync, GLbitfield flags, GLuint64 timeout))
LIB_PROC(GLenum, glGetError, ARGS(void))
LIB_PROC(GLenum, glGetGraphicsResetStatus, ARGS(void))
LIB_PROC(GLint, glGetAttribLocation, ARGS(GLuint program, const GLchar *name))
LIB_PROC(GLint, glGetFragDataLocation, ARGS(GLuint program, const GLchar *name))
LIB_PROC(GLint, glGetProgramResourceLocation, ARGS(GLuint program, GLenum programInterface, const GLchar *name))
LIB_PROC(GLint, glGetUniformLocation, ARGS(GLuint program, const GLchar *name))
LIB_PROC(GLsync, glFenceSync, ARGS(GLenum condition, GLbitfield flags))
LIB_PROC(GLuint, glCreateProgram, ARGS(void))
LIB_PROC(GLuint, glCreateShader, ARGS(GLenum type))
LIB_PROC(GLuint, glCreateShaderProgramv, ARGS(GLenum type, GLsizei count, const GLchar *const*strings))
LIB_PROC(GLuint, glGetDebugMessageLog, ARGS(GLuint count, GLsizei bufSize, GLenum *sources, GLenum *types, GLuint *ids, GLenum *severities, GLsizei *lengths, GLchar *messageLog))
LIB_PROC(GLuint, glGetProgramResourceIndex, ARGS(GLuint program, GLenum programInterface, const GLchar *name))
LIB_PROC(GLuint, glGetUniformBlockIndex, ARGS(GLuint program, const GLchar *uniformBlockName))
LIB_PROC(void*, glMapBufferRange, ARGS(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access))
LIB_PROC(void, glActiveShaderProgram, ARGS(GLuint pipeline, GLuint program))
LIB_PROC(void, glActiveTexture, ARGS(GLenum texture))
LIB_PROC(void, glAttachShader, ARGS(GLuint program, GLuint shader))
LIB_PROC(void, glBeginQuery, ARGS(GLenum target, GLuint id))
LIB_PROC(void, glBeginTransformFeedback, ARGS(GLenum primitiveMode))
LIB_PROC(void, glBindAttribLocation, ARGS(GLuint program, GLuint index, const GLchar *name))
LIB_PROC(void, glBindBuffer, ARGS(GLenum target, GLuint buffer))
LIB_PROC(void, glBindBufferBase, ARGS(GLenum target, GLuint index, GLuint buffer))
LIB_PROC(void, glBindBufferRange, ARGS(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size))
LIB_PROC(void, glBindFramebuffer, ARGS(GLenum target, GLuint framebuffer))
LIB_PROC(void, glBindImageTexture, ARGS(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format))
LIB_PROC(void, glBindProgramPipeline, ARGS(GLuint pipeline))
LIB_PROC(void, glBindRenderbuffer, ARGS(GLenum target, GLuint renderbuffer))
LIB_PROC(void, glBindSampler, ARGS(GLuint unit, GLuint sampler))
LIB_PROC(void, glBindTexture, ARGS(GLenum target, GLuint texture))
LIB_PROC(void, glBindTransformFeedback, ARGS(GLenum target, GLuint id))
LIB_PROC(void, glBindVertexArray, ARGS(GLuint array))
LIB_PROC(void, glBindVertexBuffer, ARGS(GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride))
LIB_PROC(void, glBlendBarrier, ARGS(void))
LIB_PROC(void, glBlendColor, ARGS(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
LIB_PROC(void, glBlendEquation, ARGS(GLenum mode))
LIB_PROC(void, glBlendEquationi, ARGS(GLuint buf, GLenum mode))
LIB_PROC(void, glBlendEquationSeparate, ARGS(GLenum modeRGB, GLenum modeAlpha))
LIB_PROC(void, glBlendEquationSeparatei, ARGS(GLuint buf, GLenum modeRGB, GLenum modeAlpha))
LIB_PROC(void, glBlendFunc, ARGS(GLenum sfactor, GLenum dfactor))
LIB_PROC(void, glBlendFunci, ARGS(GLuint buf, GLenum src, GLenum dst))
LIB_PROC(void, glBlendFuncSeparate, ARGS(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha))
LIB_PROC(void, glBlendFuncSeparatei, ARGS(GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha))
LIB_PROC(void, glBlitFramebuffer, ARGS(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter))
LIB_PROC(void, glBufferData, ARGS(GLenum target, GLsizeiptr size, const void *data, GLenum usage))
LIB_PROC(void, glBufferSubData, ARGS(GLenum target, GLintptr offset, GLsizeiptr size, const void *data))
LIB_PROC(void, glClear, ARGS(GLbitfield mask))
LIB_PROC(void, glClearBufferfi, ARGS(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil))
LIB_PROC(void, glClearBufferfv, ARGS(GLenum buffer, GLint drawbuffer, const GLfloat *value))
LIB_PROC(void, glClearBufferiv, ARGS(GLenum buffer, GLint drawbuffer, const GLint *value))
LIB_PROC(void, glClearBufferuiv, ARGS(GLenum buffer, GLint drawbuffer, const GLuint *value))
LIB_PROC(void, glClearColor, ARGS(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha))
LIB_PROC(void, glClearDepthf, ARGS(GLfloat d))
LIB_PROC(void, glClearStencil, ARGS(GLint s))
LIB_PROC(void, glColorMask, ARGS(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha))
LIB_PROC(void, glColorMaski, ARGS(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a))
LIB_PROC(void, glCompileShader, ARGS(GLuint shader))
LIB_PROC(void, glCompressedTexImage2D, ARGS(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data))
LIB_PROC(void, glCompressedTexImage3D, ARGS(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data))
LIB_PROC(void, glCompressedTexSubImage2D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data))
LIB_PROC(void, glCompressedTexSubImage3D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data))
LIB_PROC(void, glCopyBufferSubData, ARGS(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size))
LIB_PROC(void, glCopyImageSubData, ARGS(GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei srcWidth, GLsizei srcHeight, GLsizei srcDepth))
LIB_PROC(void, glCopyTexImage2D, ARGS(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border))
LIB_PROC(void, glCopyTexSubImage2D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glCopyTexSubImage3D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glCullFace, ARGS(GLenum mode))
LIB_PROC(void, glDebugMessageCallback, ARGS(GLDEBUGPROC callback, const void *userParam))
LIB_PROC(void, glDebugMessageControl, ARGS(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint *ids, GLboolean enabled))
LIB_PROC(void, glDebugMessageInsert, ARGS(GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar *buf))
LIB_PROC(void, glDeleteBuffers, ARGS(GLsizei n, const GLuint *buffers))
LIB_PROC(void, glDeleteFramebuffers, ARGS(GLsizei n, const GLuint *framebuffers))
LIB_PROC(void, glDeleteProgram, ARGS(GLuint program))
LIB_PROC(void, glDeleteProgramPipelines, ARGS(GLsizei n, const GLuint *pipelines))
LIB_PROC(void, glDeleteQueries, ARGS(GLsizei n, const GLuint *ids))
LIB_PROC(void, glDeleteRenderbuffers, ARGS(GLsizei n, const GLuint *renderbuffers))
LIB_PROC(void, glDeleteSamplers, ARGS(GLsizei count, const GLuint *samplers))
LIB_PROC(void, glDeleteShader, ARGS(GLuint shader))
LIB_PROC(void, glDeleteSync, ARGS(GLsync sync))
LIB_PROC(void, glDeleteTextures, ARGS(GLsizei n, const GLuint *textures))
LIB_PROC(void, glDeleteTransformFeedbacks, ARGS(GLsizei n, const GLuint *ids))
LIB_PROC(void, glDeleteVertexArrays, ARGS(GLsizei n, const GLuint *arrays))
LIB_PROC(void, glDepthFunc, ARGS(GLenum func))
LIB_PROC(void, glDepthMask, ARGS(GLboolean flag))
LIB_PROC(void, glDepthRangef, ARGS(GLfloat n, GLfloat f))
LIB_PROC(void, glDetachShader, ARGS(GLuint program, GLuint shader))
LIB_PROC(void, glDisable, ARGS(GLenum cap))
LIB_PROC(void, glDisablei, ARGS(GLenum target, GLuint index))
LIB_PROC(void, glDisableVertexAttribArray, ARGS(GLuint index))
LIB_PROC(void, glDispatchCompute, ARGS(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z))
LIB_PROC(void, glDispatchComputeIndirect, ARGS(GLintptr indirect))
LIB_PROC(void, glDrawArrays, ARGS(GLenum mode, GLint first, GLsizei count))
LIB_PROC(void, glDrawArraysIndirect, ARGS(GLenum mode, const void *indirect))
LIB_PROC(void, glDrawArraysInstanced, ARGS(GLenum mode, GLint first, GLsizei count, GLsizei instancecount))
LIB_PROC(void, glDrawBuffers, ARGS(GLsizei n, const GLenum *bufs))
LIB_PROC(void, glDrawElements, ARGS(GLenum mode, GLsizei count, GLenum type, const void *indices))
LIB_PROC(void, glDrawElementsBaseVertex, ARGS(GLenum mode, GLsizei count, GLenum type, const void *indices, GLint basevertex))
LIB_PROC(void, glDrawElementsIndirect, ARGS(GLenum mode, GLenum type, const void *indirect))
LIB_PROC(void, glDrawElementsInstanced, ARGS(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount))
LIB_PROC(void, glDrawElementsInstancedBaseVertex, ARGS(GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount, GLint basevertex))
LIB_PROC(void, glDrawRangeElements, ARGS(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices))
LIB_PROC(void, glDrawRangeElementsBaseVertex, ARGS(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices, GLint basevertex))
LIB_PROC(void, glEnable, ARGS(GLenum cap))
LIB_PROC(void, glEnablei, ARGS(GLenum target, GLuint index))
LIB_PROC(void, glEnableVertexAttribArray, ARGS(GLuint index))
LIB_PROC(void, glEndQuery, ARGS(GLenum target))
LIB_PROC(void, glEndTransformFeedback, ARGS(void))
LIB_PROC(void, glFinish, ARGS(void))
LIB_PROC(void, glFlush, ARGS(void))
LIB_PROC(void, glFlushMappedBufferRange, ARGS(GLenum target, GLintptr offset, GLsizeiptr length))
LIB_PROC(void, glFramebufferParameteri, ARGS(GLenum target, GLenum pname, GLint param))
LIB_PROC(void, glFramebufferRenderbuffer, ARGS(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer))
LIB_PROC(void, glFramebufferTexture2D, ARGS(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level))
LIB_PROC(void, glFramebufferTexture, ARGS(GLenum target, GLenum attachment, GLuint texture, GLint level))
LIB_PROC(void, glFramebufferTextureLayer, ARGS(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer))
LIB_PROC(void, glFrontFace, ARGS(GLenum mode))
LIB_PROC(void, glGenBuffers, ARGS(GLsizei n, GLuint *buffers))
LIB_PROC(void, glGenerateMipmap, ARGS(GLenum target))
LIB_PROC(void, glGenFramebuffers, ARGS(GLsizei n, GLuint *framebuffers))
LIB_PROC(void, glGenProgramPipelines, ARGS(GLsizei n, GLuint *pipelines))
LIB_PROC(void, glGenQueries, ARGS(GLsizei n, GLuint *ids))
LIB_PROC(void, glGenRenderbuffers, ARGS(GLsizei n, GLuint *renderbuffers))
LIB_PROC(void, glGenSamplers, ARGS(GLsizei count, GLuint *samplers))
LIB_PROC(void, glGenTextures, ARGS(GLsizei n, GLuint *textures))
LIB_PROC(void, glGenTransformFeedbacks, ARGS(GLsizei n, GLuint *ids))
LIB_PROC(void, glGenVertexArrays, ARGS(GLsizei n, GLuint *arrays))
LIB_PROC(void, glGetActiveAttrib, ARGS(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name))
LIB_PROC(void, glGetActiveUniform, ARGS(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name))
LIB_PROC(void, glGetActiveUniformBlockiv, ARGS(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params))
LIB_PROC(void, glGetActiveUniformBlockName, ARGS(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName))
LIB_PROC(void, glGetActiveUniformsiv, ARGS(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params))
LIB_PROC(void, glGetAttachedShaders, ARGS(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders))
LIB_PROC(void, glGetBooleani_v, ARGS(GLenum target, GLuint index, GLboolean *data))
LIB_PROC(void, glGetBooleanv, ARGS(GLenum pname, GLboolean *data))
LIB_PROC(void, glGetBufferParameteri64v, ARGS(GLenum target, GLenum pname, GLint64 *params))
LIB_PROC(void, glGetBufferParameteriv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetBufferPointerv, ARGS(GLenum target, GLenum pname, void **params))
LIB_PROC(void, glGetFloatv, ARGS(GLenum pname, GLfloat *data))
LIB_PROC(void, glGetFramebufferAttachmentParameteriv, ARGS(GLenum target, GLenum attachment, GLenum pname, GLint *params))
LIB_PROC(void, glGetFramebufferParameteriv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetInteger64i_v, ARGS(GLenum target, GLuint index, GLint64 *data))
LIB_PROC(void, glGetInteger64v, ARGS(GLenum pname, GLint64 *data))
LIB_PROC(void, glGetIntegeri_v, ARGS(GLenum target, GLuint index, GLint *data))
LIB_PROC(void, glGetIntegerv, ARGS(GLenum pname, GLint *data))
LIB_PROC(void, glGetInternalformativ, ARGS(GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params))
LIB_PROC(void, glGetMultisamplefv, ARGS(GLenum pname, GLuint index, GLfloat *val))
LIB_PROC(void, glGetnUniformfv, ARGS(GLuint program, GLint location, GLsizei bufSize, GLfloat *params))
LIB_PROC(void, glGetnUniformiv, ARGS(GLuint program, GLint location, GLsizei bufSize, GLint *params))
LIB_PROC(void, glGetnUniformuiv, ARGS(GLuint program, GLint location, GLsizei bufSize, GLuint *params))
LIB_PROC(void, glGetObjectLabel, ARGS(GLenum identifier, GLuint name, GLsizei bufSize, GLsizei *length, GLchar *label))
LIB_PROC(void, glGetObjectPtrLabel, ARGS(const void *ptr, GLsizei bufSize, GLsizei *length, GLchar *label))
LIB_PROC(void, glGetPointerv, ARGS(GLenum pname, void **params))
LIB_PROC(void, glGetProgramBinary, ARGS(GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary))
LIB_PROC(void, glGetProgramInfoLog, ARGS(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
LIB_PROC(void, glGetProgramInterfaceiv, ARGS(GLuint program, GLenum programInterface, GLenum pname, GLint *params))
LIB_PROC(void, glGetProgramiv, ARGS(GLuint program, GLenum pname, GLint *params))
LIB_PROC(void, glGetProgramPipelineInfoLog, ARGS(GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
LIB_PROC(void, glGetProgramPipelineiv, ARGS(GLuint pipeline, GLenum pname, GLint *params))
LIB_PROC(void, glGetProgramResourceiv, ARGS(GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params))
LIB_PROC(void, glGetProgramResourceName, ARGS(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name))
LIB_PROC(void, glGetQueryiv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetQueryObjectuiv, ARGS(GLuint id, GLenum pname, GLuint *params))
LIB_PROC(void, glGetRenderbufferParameteriv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetSamplerParameterfv, ARGS(GLuint sampler, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetSamplerParameterIiv, ARGS(GLuint sampler, GLenum pname, GLint *params))
LIB_PROC(void, glGetSamplerParameterIuiv, ARGS(GLuint sampler, GLenum pname, GLuint *params))
LIB_PROC(void, glGetSamplerParameteriv, ARGS(GLuint sampler, GLenum pname, GLint *params))
LIB_PROC(void, glGetShaderInfoLog, ARGS(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog))
LIB_PROC(void, glGetShaderiv, ARGS(GLuint shader, GLenum pname, GLint *params))
LIB_PROC(void, glGetShaderPrecisionFormat, ARGS(GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision))
LIB_PROC(void, glGetShaderSource, ARGS(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source))
LIB_PROC(void, glGetSynciv, ARGS(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values))
LIB_PROC(void, glGetTexLevelParameterfv, ARGS(GLenum target, GLint level, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetTexLevelParameteriv, ARGS(GLenum target, GLint level, GLenum pname, GLint *params))
LIB_PROC(void, glGetTexParameterfv, ARGS(GLenum target, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetTexParameterIiv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetTexParameterIuiv, ARGS(GLenum target, GLenum pname, GLuint *params))
LIB_PROC(void, glGetTexParameteriv, ARGS(GLenum target, GLenum pname, GLint *params))
LIB_PROC(void, glGetTransformFeedbackVarying, ARGS(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name))
LIB_PROC(void, glGetUniformfv, ARGS(GLuint program, GLint location, GLfloat *params))
LIB_PROC(void, glGetUniformIndices, ARGS(GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices))
LIB_PROC(void, glGetUniformiv, ARGS(GLuint program, GLint location, GLint *params))
LIB_PROC(void, glGetUniformuiv, ARGS(GLuint program, GLint location, GLuint *params))
LIB_PROC(void, glGetVertexAttribfv, ARGS(GLuint index, GLenum pname, GLfloat *params))
LIB_PROC(void, glGetVertexAttribIiv, ARGS(GLuint index, GLenum pname, GLint *params))
LIB_PROC(void, glGetVertexAttribIuiv, ARGS(GLuint index, GLenum pname, GLuint *params))
LIB_PROC(void, glGetVertexAttribiv, ARGS(GLuint index, GLenum pname, GLint *params))
LIB_PROC(void, glGetVertexAttribPointerv, ARGS(GLuint index, GLenum pname, void **pointer))
LIB_PROC(void, glHint, ARGS(GLenum target, GLenum mode))
LIB_PROC(void, glInvalidateFramebuffer, ARGS(GLenum target, GLsizei numAttachments, const GLenum *attachments))
LIB_PROC(void, glInvalidateSubFramebuffer, ARGS(GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glLineWidth, ARGS(GLfloat width))
LIB_PROC(void, glLinkProgram, ARGS(GLuint program))
LIB_PROC(void, glMemoryBarrier, ARGS(GLbitfield barriers))
LIB_PROC(void, glMemoryBarrierByRegion, ARGS(GLbitfield barriers))
LIB_PROC(void, glMinSampleShading, ARGS(GLfloat value))
LIB_PROC(void, glObjectLabel, ARGS(GLenum identifier, GLuint name, GLsizei length, const GLchar *label))
LIB_PROC(void, glObjectPtrLabel, ARGS(const void *ptr, GLsizei length, const GLchar *label))
LIB_PROC(void, glPatchParameteri, ARGS(GLenum pname, GLint value))
LIB_PROC(void, glPauseTransformFeedback, ARGS(void))
LIB_PROC(void, glPixelStorei, ARGS(GLenum pname, GLint param))
LIB_PROC(void, glPolygonOffset, ARGS(GLfloat factor, GLfloat units))
LIB_PROC(void, glPopDebugGroup, ARGS(void))
LIB_PROC(void, glPrimitiveBoundingBox, ARGS(GLfloat minX, GLfloat minY, GLfloat minZ, GLfloat minW, GLfloat maxX, GLfloat maxY, GLfloat maxZ, GLfloat maxW))
LIB_PROC(void, glProgramBinary, ARGS(GLuint program, GLenum binaryFormat, const void *binary, GLsizei length))
LIB_PROC(void, glProgramParameteri, ARGS(GLuint program, GLenum pname, GLint value))
LIB_PROC(void, glProgramUniform1f, ARGS(GLuint program, GLint location, GLfloat v0))
LIB_PROC(void, glProgramUniform1fv, ARGS(GLuint program, GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glProgramUniform1i, ARGS(GLuint program, GLint location, GLint v0))
LIB_PROC(void, glProgramUniform1iv, ARGS(GLuint program, GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glProgramUniform1ui, ARGS(GLuint program, GLint location, GLuint v0))
LIB_PROC(void, glProgramUniform1uiv, ARGS(GLuint program, GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glProgramUniform2f, ARGS(GLuint program, GLint location, GLfloat v0, GLfloat v1))
LIB_PROC(void, glProgramUniform2fv, ARGS(GLuint program, GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glProgramUniform2i, ARGS(GLuint program, GLint location, GLint v0, GLint v1))
LIB_PROC(void, glProgramUniform2iv, ARGS(GLuint program, GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glProgramUniform2ui, ARGS(GLuint program, GLint location, GLuint v0, GLuint v1))
LIB_PROC(void, glProgramUniform2uiv, ARGS(GLuint program, GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glProgramUniform3f, ARGS(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2))
LIB_PROC(void, glProgramUniform3fv, ARGS(GLuint program, GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glProgramUniform3i, ARGS(GLuint program, GLint location, GLint v0, GLint v1, GLint v2))
LIB_PROC(void, glProgramUniform3iv, ARGS(GLuint program, GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glProgramUniform3ui, ARGS(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2))
LIB_PROC(void, glProgramUniform3uiv, ARGS(GLuint program, GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glProgramUniform4f, ARGS(GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3))
LIB_PROC(void, glProgramUniform4fv, ARGS(GLuint program, GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glProgramUniform4i, ARGS(GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3))
LIB_PROC(void, glProgramUniform4iv, ARGS(GLuint program, GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glProgramUniform4ui, ARGS(GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3))
LIB_PROC(void, glProgramUniform4uiv, ARGS(GLuint program, GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glProgramUniformMatrix2fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix2x3fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix2x4fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix3fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix3x2fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix3x4fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix4fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix4x2fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glProgramUniformMatrix4x3fv, ARGS(GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glPushDebugGroup, ARGS(GLenum source, GLuint id, GLsizei length, const GLchar *message))
LIB_PROC(void, glReadBuffer, ARGS(GLenum src))
LIB_PROC(void, glReadnPixels, ARGS(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLsizei bufSize, void *data))
LIB_PROC(void, glReadPixels, ARGS(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels))
LIB_PROC(void, glReleaseShaderCompiler, ARGS(void))
LIB_PROC(void, glRenderbufferStorage, ARGS(GLenum target, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glRenderbufferStorageMultisample, ARGS(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glResumeTransformFeedback, ARGS(void))
LIB_PROC(void, glSampleCoverage, ARGS(GLfloat value, GLboolean invert))
LIB_PROC(void, glSampleMaski, ARGS(GLuint maskNumber, GLbitfield mask))
LIB_PROC(void, glSamplerParameterf, ARGS(GLuint sampler, GLenum pname, GLfloat param))
LIB_PROC(void, glSamplerParameterfv, ARGS(GLuint sampler, GLenum pname, const GLfloat *param))
LIB_PROC(void, glSamplerParameteri, ARGS(GLuint sampler, GLenum pname, GLint param))
LIB_PROC(void, glSamplerParameterIiv, ARGS(GLuint sampler, GLenum pname, const GLint *param))
LIB_PROC(void, glSamplerParameterIuiv, ARGS(GLuint sampler, GLenum pname, const GLuint *param))
LIB_PROC(void, glSamplerParameteriv, ARGS(GLuint sampler, GLenum pname, const GLint *param))
LIB_PROC(void, glScissor, ARGS(GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glShaderBinary, ARGS(GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length))
LIB_PROC(void, glShaderSource, ARGS(GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length))
LIB_PROC(void, glStencilFunc, ARGS(GLenum func, GLint ref, GLuint mask))
LIB_PROC(void, glStencilFuncSeparate, ARGS(GLenum face, GLenum func, GLint ref, GLuint mask))
LIB_PROC(void, glStencilMask, ARGS(GLuint mask))
LIB_PROC(void, glStencilMaskSeparate, ARGS(GLenum face, GLuint mask))
LIB_PROC(void, glStencilOp, ARGS(GLenum fail, GLenum zfail, GLenum zpass))
LIB_PROC(void, glStencilOpSeparate, ARGS(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass))
LIB_PROC(void, glTexBuffer, ARGS(GLenum target, GLenum internalformat, GLuint buffer))
LIB_PROC(void, glTexBufferRange, ARGS(GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size))
LIB_PROC(void, glTexImage2D, ARGS(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels))
LIB_PROC(void, glTexImage3D, ARGS(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels))
LIB_PROC(void, glTexParameterf, ARGS(GLenum target, GLenum pname, GLfloat param))
LIB_PROC(void, glTexParameterfv, ARGS(GLenum target, GLenum pname, const GLfloat *params))
LIB_PROC(void, glTexParameteri, ARGS(GLenum target, GLenum pname, GLint param))
LIB_PROC(void, glTexParameterIiv, ARGS(GLenum target, GLenum pname, const GLint *params))
LIB_PROC(void, glTexParameterIuiv, ARGS(GLenum target, GLenum pname, const GLuint *params))
LIB_PROC(void, glTexParameteriv, ARGS(GLenum target, GLenum pname, const GLint *params))
LIB_PROC(void, glTexStorage2D, ARGS(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height))
LIB_PROC(void, glTexStorage2DMultisample, ARGS(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations))
LIB_PROC(void, glTexStorage3D, ARGS(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth))
LIB_PROC(void, glTexStorage3DMultisample, ARGS(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations))
LIB_PROC(void, glTexSubImage2D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels))
LIB_PROC(void, glTexSubImage3D, ARGS(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels))
LIB_PROC(void, glTransformFeedbackVaryings, ARGS(GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode))
LIB_PROC(void, glUniform1f, ARGS(GLint location, GLfloat v0))
LIB_PROC(void, glUniform1fv, ARGS(GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glUniform1i, ARGS(GLint location, GLint v0))
LIB_PROC(void, glUniform1iv, ARGS(GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glUniform1ui, ARGS(GLint location, GLuint v0))
LIB_PROC(void, glUniform1uiv, ARGS(GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glUniform2f, ARGS(GLint location, GLfloat v0, GLfloat v1))
LIB_PROC(void, glUniform2fv, ARGS(GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glUniform2i, ARGS(GLint location, GLint v0, GLint v1))
LIB_PROC(void, glUniform2iv, ARGS(GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glUniform2ui, ARGS(GLint location, GLuint v0, GLuint v1))
LIB_PROC(void, glUniform2uiv, ARGS(GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glUniform3f, ARGS(GLint location, GLfloat v0, GLfloat v1, GLfloat v2))
LIB_PROC(void, glUniform3fv, ARGS(GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glUniform3i, ARGS(GLint location, GLint v0, GLint v1, GLint v2))
LIB_PROC(void, glUniform3iv, ARGS(GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glUniform3ui, ARGS(GLint location, GLuint v0, GLuint v1, GLuint v2))
LIB_PROC(void, glUniform3uiv, ARGS(GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glUniform4f, ARGS(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3))
LIB_PROC(void, glUniform4fv, ARGS(GLint location, GLsizei count, const GLfloat *value))
LIB_PROC(void, glUniform4i, ARGS(GLint location, GLint v0, GLint v1, GLint v2, GLint v3))
LIB_PROC(void, glUniform4iv, ARGS(GLint location, GLsizei count, const GLint *value))
LIB_PROC(void, glUniform4ui, ARGS(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3))
LIB_PROC(void, glUniform4uiv, ARGS(GLint location, GLsizei count, const GLuint *value))
LIB_PROC(void, glUniformBlockBinding, ARGS(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding))
LIB_PROC(void, glUniformMatrix2fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix2x3fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix2x4fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix3fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix3x2fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix3x4fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix4fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix4x2fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUniformMatrix4x3fv, ARGS(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value))
LIB_PROC(void, glUseProgram, ARGS(GLuint program))
LIB_PROC(void, glUseProgramStages, ARGS(GLuint pipeline, GLbitfield stages, GLuint program))
LIB_PROC(void, glValidateProgram, ARGS(GLuint program))
LIB_PROC(void, glValidateProgramPipeline, ARGS(GLuint pipeline))
LIB_PROC(void, glVertexAttrib1f, ARGS(GLuint index, GLfloat x))
LIB_PROC(void, glVertexAttrib1fv, ARGS(GLuint index, const GLfloat *v))
LIB_PROC(void, glVertexAttrib2f, ARGS(GLuint index, GLfloat x, GLfloat y))
LIB_PROC(void, glVertexAttrib2fv, ARGS(GLuint index, const GLfloat *v))
LIB_PROC(void, glVertexAttrib3f, ARGS(GLuint index, GLfloat x, GLfloat y, GLfloat z))
LIB_PROC(void, glVertexAttrib3fv, ARGS(GLuint index, const GLfloat *v))
LIB_PROC(void, glVertexAttrib4f, ARGS(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w))
LIB_PROC(void, glVertexAttrib4fv, ARGS(GLuint index, const GLfloat *v))
LIB_PROC(void, glVertexAttribBinding, ARGS(GLuint attribindex, GLuint bindingindex))
LIB_PROC(void, glVertexAttribDivisor, ARGS(GLuint index, GLuint divisor))
LIB_PROC(void, glVertexAttribFormat, ARGS(GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset))
LIB_PROC(void, glVertexAttribI4i, ARGS(GLuint index, GLint x, GLint y, GLint z, GLint w))
LIB_PROC(void, glVertexAttribI4iv, ARGS(GLuint index, const GLint *v))
LIB_PROC(void, glVertexAttribI4ui, ARGS(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w))
LIB_PROC(void, glVertexAttribI4uiv, ARGS(GLuint index, const GLuint *v))
LIB_PROC(void, glVertexAttribIFormat, ARGS(GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset))
LIB_PROC(void, glVertexAttribIPointer, ARGS(GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer))
LIB_PROC(void, glVertexAttribPointer, ARGS(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer))
LIB_PROC(void, glVertexBindingDivisor, ARGS(GLuint bindingindex, GLuint divisor))
LIB_PROC(void, glVertexBindingDivisor, ARGS(GLuint bindingindex, GLuint divisor))
LIB_PROC(void, glViewport, ARGS(GLint x, GLint y, GLsizei width, GLsizei height))
LIB_PROC(void, glWaitSync, ARGS(GLsync sync, GLbitfield flags, GLuint64 timeout))
