
#ifndef LIB_PROC
#define ARGS(...)
#define LIB_PROC(rv, name, args) 
#endif

LIB_PROC(Bool, glXBindSwapBarrierNV, ARGS(Display *dpy, GLuint group, GLuint barrier))
LIB_PROC(Bool, glXBindTexImageARB, ARGS(Display *dpy, GLXPbuffer pbuffer, int buffer))
LIB_PROC(Bool, glXDelayBeforeSwapNV, ARGS(Display *dpy, GLXDrawable drawable, GLfloat seconds))
LIB_PROC(Bool, glXDeleteAssociatedContextAMD, ARGS(GLXContext ctx))
LIB_PROC(Bool, glXDrawableAttribARB, ARGS(Display *dpy, GLXDrawable draw, const int *attribList))
LIB_PROC(Bool, glXGetMscRateOML, ARGS(Display *dpy, GLXDrawable drawable, int32_t *numerator, int32_t *denominator))
LIB_PROC(Bool, glXGetSyncValuesOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t *ust, int64_t *msc, int64_t *sbc))
LIB_PROC(Bool, glXIsDirect, ARGS(Display *dpy, GLXContext ctx))
LIB_PROC(Bool, glXJoinSwapGroupNV, ARGS(Display *dpy, GLXDrawable drawable, GLuint group))
LIB_PROC(Bool, glXMakeAssociatedContextCurrentAMD, ARGS(GLXContext ctx))
LIB_PROC(Bool, glXMakeContextCurrent, ARGS(Display *dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx))
LIB_PROC(Bool, glXMakeCurrentReadSGI, ARGS(Display *dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx))
LIB_PROC(Bool, glXQueryCurrentRendererIntegerMESA, ARGS(int attribute, unsigned int *value))
LIB_PROC(Bool, glXQueryExtension, ARGS(Display *dpy, int *errorb, int *event))
LIB_PROC(Bool, glXQueryFrameCountNV, ARGS(Display *dpy, int screen, GLuint *count))
LIB_PROC(Bool, glXQueryMaxSwapBarriersSGIX, ARGS(Display *dpy, int screen, int *max))
LIB_PROC(Bool, glXQueryMaxSwapGroupsNV, ARGS(Display *dpy, int screen, GLuint *maxGroups, GLuint *maxBarriers))
LIB_PROC(Bool, glXQueryRendererIntegerMESA, ARGS(Display *dpy, int screen, int renderer, int attribute, unsigned int *value))
LIB_PROC(Bool, glXQuerySwapGroupNV, ARGS(Display *dpy, GLXDrawable drawable, GLuint *group, GLuint *barrier))
LIB_PROC(Bool, glXQueryVersion, ARGS(Display *dpy, int *maj, int *min))
LIB_PROC(Bool, glXReleaseBuffersMESA, ARGS(Display *dpy, GLXDrawable drawable))
LIB_PROC(Bool, glXReleaseTexImageARB, ARGS(Display *dpy, GLXPbuffer pbuffer, int buffer))
LIB_PROC(Bool, glXResetFrameCountNV, ARGS(Display *dpy, int screen))
LIB_PROC(Bool, glXWaitForMscOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder, int64_t *ust, int64_t *msc, int64_t *sbc))
LIB_PROC(Bool, glXWaitForSbcOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t target_sbc, int64_t *ust, int64_t *msc, int64_t *sbc))
LIB_PROC(const char *, glXGetClientString, ARGS(Display *dpy, int name))
LIB_PROC(const char *, glXQueryCurrentRendererStringMESA, ARGS(int attribute))
LIB_PROC(const char *, glXQueryExtensionsString, ARGS(Display *dpy, int screen))
LIB_PROC(const char *, glXQueryRendererStringMESA, ARGS(Display *dpy, int screen, int renderer, int attribute))
LIB_PROC(const char *, glXQueryServerString, ARGS(Display *dpy, int screen, int name))
LIB_PROC(Display *, glXGetCurrentDisplay, ARGS(void))
LIB_PROC(Display *, glXGetCurrentDisplayEXT, ARGS(void))
LIB_PROC(GLboolean, glXSet3DfxModeMESA, ARGS(GLint mode))
LIB_PROC(GLXContext, glXCreateAssociatedContextAMD, ARGS(unsigned int id, GLXContext share_list))
LIB_PROC(GLXContext, glXCreateAssociatedContextAttribsAMD, ARGS(unsigned int id, GLXContext share_context, const int *attribList))
LIB_PROC(GLXContext, glXCreateContext, ARGS(Display *dpy, XVisualInfo *vis, GLXContext shareList, Bool direct))
LIB_PROC(GLXContext, glXCreateContextAttribsARB, ARGS(Display *dpy, GLXFBConfig config, GLXContext share_context, Bool direct, const int *attrib_list))
LIB_PROC(GLXContext, glXCreateContextAttribsARB, ARGS(Display *dpy, GLXFBConfig config, GLXContext share_context, int direct, const int *attrib_list))
LIB_PROC(GLXContext, glXCreateContextWithConfigSGIX, ARGS(Display *dpy, GLXFBConfigSGIX config, int render_type, GLXContext share_list, Bool direct))
LIB_PROC(GLXContext, glXCreateContextWithConfigSGIX, ARGS(Display *dpy, GLXFBConfigSGIX config, int render_type, GLXContext share_list, int direct))
LIB_PROC(GLXContext, glXCreateNewContext, ARGS(Display *dpy, GLXFBConfig config, int render_type, GLXContext share_list, Bool direct))
LIB_PROC(GLXContext, glXCreateNewContext, ARGS(Display *dpy, GLXFBConfig config, int renderType, GLXContext shareList, Bool direct))
LIB_PROC(GLXContext, glXGetCurrentAssociatedContextAMD, ARGS(void))
LIB_PROC(GLXContext, glXGetCurrentContext, ARGS(void))
LIB_PROC(GLXContext, glXImportContextEXT, ARGS(Display *dpy, GLXContextID contextID))
LIB_PROC(GLXContextID, glXGetContextIDEXT, ARGS(const GLXContext context))
LIB_PROC(GLXDrawable, glXGetCurrentDrawable, ARGS(void))
LIB_PROC(GLXDrawable, glXGetCurrentReadDrawable, ARGS(void))
LIB_PROC(GLXDrawable, glXGetCurrentReadDrawableSGI, ARGS(void))
LIB_PROC(__GLXextFuncPtr, glXGetProcAddressARB, ARGS(const GLubyte *procName))
LIB_PROC(__GLXextFuncPtr, glXGetProcAddress, ARGS(const GLubyte *procName))
LIB_PROC(GLXFBConfig *, glXChooseFBConfig, ARGS(Display *dpy, int screen, const int *attrib_list, int *nelements))
LIB_PROC(GLXFBConfig *, glXGetFBConfigs, ARGS(Display *dpy, int screen, int *nelements))
LIB_PROC(GLXFBConfigSGIX *, glXChooseFBConfigSGIX, ARGS(Display *dpy, int screen, int *attrib_list, int *nelements))
LIB_PROC(GLXFBConfigSGIX, glXGetFBConfigFromVisualSGIX, ARGS(Display *dpy, XVisualInfo *vis))
LIB_PROC(GLXHyperpipeConfigSGIX *, glXQueryHyperpipeConfigSGIX, ARGS(Display *dpy, int hpId, int *npipes))
LIB_PROC(GLXHyperpipeNetworkSGIX *, glXQueryHyperpipeNetworkSGIX, ARGS(Display *dpy, int *npipes))
LIB_PROC(GLXPbuffer, glXCreatePbuffer, ARGS(Display *dpy, GLXFBConfig config, const int *attrib_list))
LIB_PROC(GLXPbufferSGIX, glXCreateGLXPbufferSGIX, ARGS(Display *dpy, GLXFBConfigSGIX config, unsigned int width, unsigned int height, int *attrib_list))
LIB_PROC(GLXPixmap, glXCreateGLXPixmap, ARGS(Display *dpy, XVisualInfo *visual, Pixmap pixmap))
LIB_PROC(GLXPixmap, glXCreateGLXPixmapMESA, ARGS(Display *dpy, XVisualInfo *visual, Pixmap pixmap, Colormap cmap))
LIB_PROC(GLXPixmap, glXCreateGLXPixmapWithConfigSGIX, ARGS(Display *dpy, GLXFBConfigSGIX config, Pixmap pixmap))
LIB_PROC(GLXPixmap, glXCreatePixmap, ARGS(Display *dpy, GLXFBConfig config, Pixmap pixmap, const int *attrib_list))
LIB_PROC(GLXVideoCaptureDeviceNV *, glXEnumerateVideoCaptureDevicesNV, ARGS(Display *dpy, int screen, int *nelements))
LIB_PROC(GLXWindow, glXCreateWindow, ARGS(Display *dpy, GLXFBConfig config, Window win, const int *attrib_list))
LIB_PROC(int64_t, glXSwapBuffersMscOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder))
LIB_PROC(int, glXBeginFrameTrackingMESA, ARGS(Display *dpy, GLXDrawable drawable))
LIB_PROC(int, glXBindChannelToWindowSGIX, ARGS(Display *display, int screen, int channel, Window window))
LIB_PROC(int, glXBindHyperpipeSGIX, ARGS(Display *dpy, int hpId))
LIB_PROC(int, glXBindSwapBarrierNV, ARGS(Display *dpy, GLuint group, GLuint barrier))
LIB_PROC(int, glXBindVideoCaptureDeviceNV, ARGS(Display *dpy, unsigned int video_capture_slot, GLXVideoCaptureDeviceNV device))
LIB_PROC(int, glXBindVideoDeviceNV, ARGS(Display *dpy, unsigned int video_slot, unsigned int video_device, const int *attrib_list))
LIB_PROC(int, glXBindVideoImageNV, ARGS(Display *dpy, GLXVideoDeviceNV VideoDevice, GLXPbuffer pbuf, int iVideoBuffer))
LIB_PROC(int, glXChannelRectSGIX, ARGS(Display *display, int screen, int channel, int x, int y, int w, int h))
LIB_PROC(int, glXChannelRectSyncSGIX, ARGS(Display *display, int screen, int channel, GLenum synctype))
LIB_PROC(int, glXDelayBeforeSwapNV, ARGS(Display *dpy, GLXDrawable drawable, GLfloat seconds))
LIB_PROC(int, glXDeleteAssociatedContextAMD, ARGS(GLXContext ctx))
LIB_PROC(int, glXDestroyHyperpipeConfigSGIX, ARGS(Display *dpy, int hpId))
LIB_PROC(int, glXEndFrameTrackingMESA, ARGS(Display *dpy, GLXDrawable drawable))
LIB_PROC(int, glXGetConfig, ARGS(Display *dpy, XVisualInfo *visual, Pixmap pixmap))
LIB_PROC(int, glXGetFBConfigAttrib, ARGS(Display *dpy, GLXFBConfig config, int attribute, int *value))
LIB_PROC(int, glXGetFBConfigAttribSGIX, ARGS(Display *dpy, GLXFBConfigSGIX config, int attribute, int *value))
LIB_PROC(int, glXGetFrameUsageMESA, ARGS(Display *dpy, GLXDrawable drawable, float *usage))
LIB_PROC(int, glXGetGPUInfoAMD, ARGS(unsigned int id, int property, GLenum dataType, unsigned int size, void *data))
LIB_PROC(int, glXGetMscRateOML, ARGS(Display *dpy, GLXDrawable drawable, int32_t *numerator, int32_t *denominator))
LIB_PROC(int, glXGetSwapIntervalMESA, ARGS(void))
LIB_PROC(int, glXGetSyncValuesOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t *ust, int64_t *msc, int64_t *sbc))
LIB_PROC(int, glXGetTransparentIndexSUN, ARGS(Display *dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex))
LIB_PROC(int, glXGetVideoDeviceNV, ARGS(Display *dpy, int screen, int numVideoDevices, GLXVideoDeviceNV *pVideoDevice))
LIB_PROC(int, glXGetVideoInfoNV, ARGS(Display *dpy, int screen, GLXVideoDeviceNV VideoDevice, unsigned long *pulCounterOutputPbuffer, unsigned long *pulCounterOutputVideo))
LIB_PROC(int, glXGetVideoSyncSGI, ARGS(unsigned int *count))
LIB_PROC(int, glXHyperpipeAttribSGIX, ARGS(Display *dpy, int timeSlice, int attrib, int size, void *attribList))
LIB_PROC(int, glXHyperpipeConfigSGIX, ARGS(Display *dpy, int networkId, int npipes, GLXHyperpipeConfigSGIX *cfg, int *hpId))
LIB_PROC(int, glXJoinSwapGroupNV, ARGS(Display *dpy, GLXDrawable drawable, GLuint group))
LIB_PROC(int, glXMakeAssociatedContextCurrentAMD, ARGS(GLXContext ctx))
LIB_PROC(int, glXMakeCurrentReadSGI, ARGS(Display *dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx))
LIB_PROC(int, glXQueryChannelDeltasSGIX, ARGS(Display *display, int screen, int channel, int *x, int *y, int *w, int *h))
LIB_PROC(int, glXQueryChannelRectSGIX, ARGS(Display *display, int screen, int channel, int *dx, int *dy, int *dw, int *dh))
LIB_PROC(int, glXQueryContext, ARGS(Display *dpy, GLXContext ctx, int attribute, int *value))
LIB_PROC(int, glXQueryContextInfoEXT, ARGS(Display *dpy, GLXContext context, int attribute, int *value))
LIB_PROC(int, glXQueryCurrentRendererIntegerMESA, ARGS(int attribute, unsigned int *value))
LIB_PROC(int, glXQueryFrameCountNV, ARGS(Display *dpy, int screen, GLuint *count))
LIB_PROC(int, glXQueryFrameTrackingMESA, ARGS(Display *dpy, GLXDrawable drawable, int64_t *swapCount, int64_t *missedFrames, float *lastMissedUsage))
LIB_PROC(int, glXQueryHyperpipeAttribSGIX, ARGS(Display *dpy, int timeSlice, int attrib, int size, void *returnAttribList))
LIB_PROC(int, glXQueryHyperpipeBestAttribSGIX, ARGS(Display *dpy, int timeSlice, int attrib, int size, void *attribList, void *returnAttribList))
LIB_PROC(int, glXQueryMaxSwapBarriersSGIX, ARGS(Display *dpy, int screen, int *max))
LIB_PROC(int, glXQueryMaxSwapGroupsNV, ARGS(Display *dpy, int screen, GLuint *maxGroups, GLuint *maxBarriers))
LIB_PROC(int, glXQueryRendererIntegerMESA, ARGS(Display *dpy, int screen, int renderer, int attribute, unsigned int *value))
LIB_PROC(int, glXQuerySwapGroupNV, ARGS(Display *dpy, GLXDrawable drawable, GLuint *group, GLuint *barrier))
LIB_PROC(int, glXQueryVideoCaptureDeviceNV, ARGS(Display *dpy, GLXVideoCaptureDeviceNV device, int attribute, int *value))
LIB_PROC(int, glXReleaseBuffersMESA, ARGS(Display *dpy, GLXDrawable drawable))
LIB_PROC(int, glXReleaseVideoDeviceNV, ARGS(Display *dpy, int screen, GLXVideoDeviceNV VideoDevice))
LIB_PROC(int, glXReleaseVideoImageNV, ARGS(Display *dpy, GLXPbuffer pbuf))
LIB_PROC(int, glXResetFrameCountNV, ARGS(Display *dpy, int screen))
LIB_PROC(int, glXSendPbufferToVideoNV, ARGS(Display *dpy, GLXPbuffer pbuf, int iBufferType, unsigned long *pulCounterPbuffer, GLboolean bBlock))
LIB_PROC(int, glXSwapIntervalMESA, ARGS(unsigned int interval))
LIB_PROC(int, glXSwapIntervalSGI, ARGS(int interval))
LIB_PROC(int, glXWaitForMscOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder, int64_t *ust, int64_t *msc, int64_t *sbc))
LIB_PROC(int, glXWaitForSbcOML, ARGS(Display *dpy, GLXDrawable drawable, int64_t target_sbc, int64_t *ust, int64_t *msc, int64_t *sbc))
LIB_PROC(int, glXWaitVideoSyncSGI, ARGS(int divisor, int remainder, unsigned int *count))
LIB_PROC(Status, glXGetTransparentIndexSUN, ARGS(Display *dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex))
LIB_PROC(unsigned int *, glXEnumerateVideoDevicesNV, ARGS(Display *dpy, int screen, int *nelements))
LIB_PROC(unsigned int, glXGetAGPOffsetMESA, ARGS(const void *pointer))
LIB_PROC(unsigned int, glXGetContextGPUIDAMD, ARGS(GLXContext ctx))
LIB_PROC(unsigned int, glXGetGPUIDsAMD, ARGS(unsigned int maxCount, unsigned int *ids))
LIB_PROC(void *, glXAllocateMemoryNV, ARGS(GLsizei size, GLfloat readfreq, GLfloat writefreq, GLfloat priority))
LIB_PROC(void, glXBindSwapBarrierSGIX, ARGS(Display *dpy, GLXDrawable drawable, int barrier))
LIB_PROC(void, glXBindTexImageEXT, ARGS(Display *dpy, GLXDrawable drawable, int buffer, const int *attrib_list))
LIB_PROC(void, glXBlitContextFramebufferAMD, ARGS(GLXContext dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter))
LIB_PROC(void, glXCopyBufferSubDataNV, ARGS(Display *dpy, GLXContext readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size))
LIB_PROC(void, glXCopyContext, ARGS(Display *dpy, GLXContext src, GLXContext dst, unsigned long mask))
LIB_PROC(void, glXCopyImageSubDataNV, ARGS(Display *dpy, GLXContext srcCtx, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLXContext dstCtx, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth))
LIB_PROC(void, glXCopySubBufferMESA, ARGS(Display *dpy, GLXDrawable drawable, int x, int y, int width, int height))
LIB_PROC(void, glXCushionSGI, ARGS(Display *dpy, Window window, float cushion))
LIB_PROC(void, glXDestroyContext, ARGS(Display *dpy, GLXContext ctx))
LIB_PROC(void, glXDestroyGLXPbufferSGIX, ARGS(Display *dpy, GLXPbufferSGIX pbuf))
LIB_PROC(void, glXDestroyGLXPixmap, ARGS(Display *dpy, GLXPixmap pixmap))
LIB_PROC(void, glXDestroyPbuffer, ARGS(Display *dpy, GLXPbuffer pbuf))
LIB_PROC(void, glXDestroyPixmap, ARGS(Display *dpy, GLXPixmap pixmap))
LIB_PROC(void, glXDestroyWindow, ARGS(Display *dpy, GLXWindow window))
LIB_PROC(void, glXFreeContextEXT, ARGS(Display *dpy, GLXContext context))
LIB_PROC(void, glXFreeMemoryNV, ARGS(GLvoid *pointer))
LIB_PROC(void, glXGetSelectedEvent, ARGS(Display *dpy, GLXDrawable drawable, unsigned long *mask))
LIB_PROC(void, glXGetSelectedEventSGIX, ARGS(Display *dpy, GLXDrawable drawable, unsigned long *mask))
LIB_PROC(void, glXJoinSwapGroupSGIX, ARGS(Display *dpy, GLXDrawable drawable, GLXDrawable member))
LIB_PROC(void, glXLockVideoCaptureDeviceNV, ARGS(Display *dpy, GLXVideoCaptureDeviceNV device))
LIB_PROC(void, glXMakeCurrent, ARGS(Display *dpy, GLXDrawable drawable, GLXContext ctx))
LIB_PROC(void, glXNamedCopyBufferSubDataNV, ARGS(Display *dpy, GLXContext readCtx, GLXContext writeCtx, GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size))
LIB_PROC(void, glXQueryDrawable, ARGS(Display *dpy, GLXDrawable draw, int attribute, unsigned int *value))
LIB_PROC(void, glXQueryGLXPbufferSGIX, ARGS(Display *dpy, GLXPbufferSGIX pbuf, int attribute, unsigned int *value))
LIB_PROC(void, glXReleaseTexImageEXT, ARGS(Display *dpy, GLXDrawable drawable, int buffer))
LIB_PROC(void, glXReleaseVideoCaptureDeviceNV, ARGS(Display *dpy, GLXVideoCaptureDeviceNV device))
LIB_PROC(void, glXSelectEvent, ARGS(Display *dpy, GLXDrawable drawable, unsigned long mask))
LIB_PROC(void, glXSelectEvent, ARGS(Display *dpy, GLXDrawable draw, unsigned long event_mask))
LIB_PROC(void, glXSelectEventSGIX, ARGS(Display *dpy, GLXDrawable drawable, unsigned long mask))
LIB_PROC(void, glXSwapBuffers, ARGS(Display *dpy, GLXDrawable drawable))
LIB_PROC(void, glXSwapIntervalEXT, ARGS(Display *dpy, GLXDrawable drawable, int interval))
LIB_PROC(void, glXUseXFont, ARGS(Font font, int first, int count, int list))
LIB_PROC(void, glXWaitGL, ARGS(void))
LIB_PROC(void, glXWaitX, ARGS(void))
LIB_PROC(XVisualInfo*, glXChooseVisual, ARGS(Display *dpy, int screen, int *attribList))
LIB_PROC(XVisualInfo *, glXGetVisualFromFBConfig, ARGS(Display *dpy, GLXFBConfig config))
LIB_PROC(XVisualInfo *, glXGetVisualFromFBConfigSGIX, ARGS(Display *dpy, GLXFBConfigSGIX config))
