#!/usr/bin/python3
from ThunkHelpers import *

lib("libasound", "2")

fn("const char * snd_asoundlib_version()")
fn("int snd_dlpath(char *, size_t, const char *)")
fn("void * snd_dlopen(const char *, int, char *, size_t)")
fn("void * snd_dlsym(void *, const char *, const char *)")
fn("int snd_dlclose(void *)")
fn("int snd_async_add_handler(snd_async_handler_t **, int, snd_async_callback_t, void *)")
fn("int snd_async_del_handler(snd_async_handler_t *)")
fn("int snd_async_handler_get_fd(snd_async_handler_t *)")
fn("int snd_async_handler_get_signo(snd_async_handler_t *)")
fn("void * snd_async_handler_get_callback_private(snd_async_handler_t *)")
fn("struct snd_shm_area * snd_shm_area_create(int, void *)")
fn("struct snd_shm_area * snd_shm_area_share(struct snd_shm_area *)")
fn("int snd_shm_area_destroy(struct snd_shm_area *)")
fn("int snd_user_file(const char *, char **)")
fn("int snd_input_stdio_open(snd_input_t **, const char *, const char *)")
fn("int snd_input_stdio_attach(snd_input_t **, FILE *, int)")
fn("int snd_input_buffer_open(snd_input_t **, const char *, ssize_t)")
fn("int snd_input_close(snd_input_t *)")
fn("char * snd_input_gets(snd_input_t *, char *, size_t)")
fn("int snd_input_getc(snd_input_t *)")
fn("int snd_input_ungetc(snd_input_t *, int)")
fn("int snd_output_stdio_open(snd_output_t **, const char *, const char *)")
fn("int snd_output_stdio_attach(snd_output_t **, FILE *, int)")
fn("int snd_output_buffer_open(snd_output_t **)")
fn("size_t snd_output_buffer_string(snd_output_t *, char **)")
fn("int snd_output_close(snd_output_t *)")
# fn("int snd_output_vprintf(snd_output_t *, const char *, va_list)")
fn("int snd_output_puts(snd_output_t *, const char *)")
fn("int snd_output_putc(snd_output_t *, int)")
fn("int snd_output_flush(snd_output_t *)")
fn("const char * snd_strerror(int)")
fn("int snd_lib_error_set_handler(snd_lib_error_handler_t)")
fn("snd_local_error_handler_t snd_lib_error_set_local(snd_local_error_handler_t)")
fn("const char * snd_config_topdir()")
fn("int snd_config_top(snd_config_t **)")
fn("int snd_config_load(snd_config_t *, snd_input_t *)")
fn("int snd_config_load_override(snd_config_t *, snd_input_t *)")
fn("int snd_config_save(snd_config_t *, snd_output_t *)")
fn("int snd_config_update()")
fn("int snd_config_update_r(snd_config_t **, snd_config_update_t **, const char *)")
fn("int snd_config_update_free(snd_config_update_t *)")
fn("int snd_config_update_free_global()")
fn("int snd_config_update_ref(snd_config_t **)")
fn("void snd_config_ref(snd_config_t *)")
fn("void snd_config_unref(snd_config_t *)")
fn("int snd_config_search(snd_config_t *, const char *, snd_config_t **)")
# fn("int snd_config_searchv(snd_config_t *, snd_config_t **)")
fn("int snd_config_search_definition(snd_config_t *, const char *, const char *, snd_config_t **)")
fn("int snd_config_expand(snd_config_t *, snd_config_t *, const char *, snd_config_t *, snd_config_t **)")
fn("int snd_config_evaluate(snd_config_t *, snd_config_t *, snd_config_t *, snd_config_t **)")
fn("int snd_config_add(snd_config_t *, snd_config_t *)")
fn("int snd_config_add_before(snd_config_t *, snd_config_t *)")
fn("int snd_config_add_after(snd_config_t *, snd_config_t *)")
fn("int snd_config_remove(snd_config_t *)")
fn("int snd_config_delete(snd_config_t *)")
fn("int snd_config_delete_compound_members(const snd_config_t *)")
fn("int snd_config_copy(snd_config_t **, snd_config_t *)")
fn("int snd_config_make(snd_config_t **, const char *, snd_config_type_t)")
fn("int snd_config_make_integer(snd_config_t **, const char *)")
fn("int snd_config_make_integer64(snd_config_t **, const char *)")
fn("int snd_config_make_real(snd_config_t **, const char *)")
fn("int snd_config_make_string(snd_config_t **, const char *)")
fn("int snd_config_make_pointer(snd_config_t **, const char *)")
fn("int snd_config_make_compound(snd_config_t **, const char *, int)")
# fn("int snd_config_imake_integer(snd_config_t **, const char *, const long)")
# fn("int snd_config_imake_integer64(snd_config_t **, const char *, const long long)")
# fn("int snd_config_imake_real(snd_config_t **, const char *, const double)")
fn("int snd_config_imake_string(snd_config_t **, const char *, const char *)")
fn("int snd_config_imake_safe_string(snd_config_t **, const char *, const char *)")
fn("int snd_config_imake_pointer(snd_config_t **, const char *, const void *)")
fn("snd_config_type_t snd_config_get_type(const snd_config_t *)")
fn("int snd_config_is_array(const snd_config_t *)")
fn("int snd_config_set_id(snd_config_t *, const char *)")
fn("int snd_config_set_integer(snd_config_t *, long)")
fn("int snd_config_set_integer64(snd_config_t *, long long)")
fn("int snd_config_set_real(snd_config_t *, double)")
fn("int snd_config_set_string(snd_config_t *, const char *)")
fn("int snd_config_set_ascii(snd_config_t *, const char *)")
fn("int snd_config_set_pointer(snd_config_t *, const void *)")
fn("int snd_config_get_id(const snd_config_t *, const char **)")
fn("int snd_config_get_integer(const snd_config_t *, long *)")
fn("int snd_config_get_integer64(const snd_config_t *, long long *)")
fn("int snd_config_get_real(const snd_config_t *, double *)")
fn("int snd_config_get_ireal(const snd_config_t *, double *)")
fn("int snd_config_get_string(const snd_config_t *, const char **)")
fn("int snd_config_get_ascii(const snd_config_t *, char **)")
fn("int snd_config_get_pointer(const snd_config_t *, const void **)")
fn("int snd_config_test_id(const snd_config_t *, const char *)")
fn("snd_config_iterator_t snd_config_iterator_first(const snd_config_t *)")
# fn("snd_config_iterator_t snd_config_iterator_next(const snd_config_iterator_t)")
fn("snd_config_iterator_t snd_config_iterator_end(const snd_config_t *)")
# fn("snd_config_t * snd_config_iterator_entry(const snd_config_iterator_t)")
fn("int snd_config_get_bool_ascii(const char *)")
fn("int snd_config_get_bool(const snd_config_t *)")
fn("int snd_config_get_ctl_iface_ascii(const char *)")
fn("int snd_config_get_ctl_iface(const snd_config_t *)")
fn("int snd_names_list(const char *, snd_devname_t **)")
fn("void snd_names_list_free(snd_devname_t *)")
fn("int snd_pcm_open(snd_pcm_t **, const char *, snd_pcm_stream_t, int)")
fn("int snd_pcm_open_lconf(snd_pcm_t **, const char *, snd_pcm_stream_t, int, snd_config_t *)")
fn("int snd_pcm_open_fallback(snd_pcm_t **, snd_config_t *, const char *, const char *, snd_pcm_stream_t, int)")
fn("int snd_pcm_close(snd_pcm_t *)")
fn("const char * snd_pcm_name(snd_pcm_t *)")
fn("snd_pcm_type_t snd_pcm_type(snd_pcm_t *)")
fn("snd_pcm_stream_t snd_pcm_stream(snd_pcm_t *)")
fn("int snd_pcm_poll_descriptors_count(snd_pcm_t *)")
fn("int snd_pcm_poll_descriptors(snd_pcm_t *, struct pollfd *, unsigned int)")
fn("int snd_pcm_poll_descriptors_revents(snd_pcm_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_pcm_nonblock(snd_pcm_t *, int)")
fn("int snd_async_add_pcm_handler(snd_async_handler_t **, snd_pcm_t *, snd_async_callback_t, void *)")
fn("snd_pcm_t * snd_async_handler_get_pcm(snd_async_handler_t *)")
fn("int snd_pcm_info(snd_pcm_t *, snd_pcm_info_t *)")
fn("int snd_pcm_hw_params_current(snd_pcm_t *, snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params(snd_pcm_t *, snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_free(snd_pcm_t *)")
fn("int snd_pcm_sw_params_current(snd_pcm_t *, snd_pcm_sw_params_t *)")
fn("int snd_pcm_sw_params(snd_pcm_t *, snd_pcm_sw_params_t *)")
fn("int snd_pcm_prepare(snd_pcm_t *)")
fn("int snd_pcm_reset(snd_pcm_t *)")
fn("int snd_pcm_status(snd_pcm_t *, snd_pcm_status_t *)")
fn("int snd_pcm_start(snd_pcm_t *)")
fn("int snd_pcm_drop(snd_pcm_t *)")
fn("int snd_pcm_drain(snd_pcm_t *)")
fn("int snd_pcm_pause(snd_pcm_t *, int)")
fn("snd_pcm_state_t snd_pcm_state(snd_pcm_t *)")
fn("int snd_pcm_hwsync(snd_pcm_t *)")
fn("int snd_pcm_delay(snd_pcm_t *, snd_pcm_sframes_t *)")
fn("int snd_pcm_resume(snd_pcm_t *)")
fn("int snd_pcm_htimestamp(snd_pcm_t *, snd_pcm_uframes_t *, snd_htimestamp_t *)")
fn("snd_pcm_sframes_t snd_pcm_avail(snd_pcm_t *)")
fn("snd_pcm_sframes_t snd_pcm_avail_update(snd_pcm_t *)")
fn("int snd_pcm_avail_delay(snd_pcm_t *, snd_pcm_sframes_t *, snd_pcm_sframes_t *)")
fn("snd_pcm_sframes_t snd_pcm_rewindable(snd_pcm_t *)")
fn("snd_pcm_sframes_t snd_pcm_rewind(snd_pcm_t *, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_forwardable(snd_pcm_t *)")
fn("snd_pcm_sframes_t snd_pcm_forward(snd_pcm_t *, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_writei(snd_pcm_t *, const void *, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_readi(snd_pcm_t *, void *, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_writen(snd_pcm_t *, void **, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_readn(snd_pcm_t *, void **, snd_pcm_uframes_t)")
fn("int snd_pcm_wait(snd_pcm_t *, int)")
fn("int snd_pcm_link(snd_pcm_t *, snd_pcm_t *)")
fn("int snd_pcm_unlink(snd_pcm_t *)")
fn("snd_pcm_chmap_query_t ** snd_pcm_query_chmaps(snd_pcm_t *)")
fn("snd_pcm_chmap_query_t ** snd_pcm_query_chmaps_from_hw(int, int, int, snd_pcm_stream_t)")
fn("void snd_pcm_free_chmaps(snd_pcm_chmap_query_t **)")
fn("snd_pcm_chmap_t * snd_pcm_get_chmap(snd_pcm_t *)")
fn("int snd_pcm_set_chmap(snd_pcm_t *, const snd_pcm_chmap_t *)")
fn("const char * snd_pcm_chmap_type_name(enum snd_pcm_chmap_type)")
fn("const char * snd_pcm_chmap_name(enum snd_pcm_chmap_position)")
fn("const char * snd_pcm_chmap_long_name(enum snd_pcm_chmap_position)")
fn("int snd_pcm_chmap_print(const snd_pcm_chmap_t *, size_t, char *)")
fn("unsigned int snd_pcm_chmap_from_string(const char *)")
fn("snd_pcm_chmap_t * snd_pcm_chmap_parse_string(const char *)")
fn("int snd_pcm_recover(snd_pcm_t *, int, int)")
fn("int snd_pcm_set_params(snd_pcm_t *, snd_pcm_format_t, snd_pcm_access_t, unsigned int, unsigned int, int, unsigned int)")
fn("int snd_pcm_get_params(snd_pcm_t *, snd_pcm_uframes_t *, snd_pcm_uframes_t *)")
fn("size_t snd_pcm_info_sizeof()")
fn("int snd_pcm_info_malloc(snd_pcm_info_t **)")
fn("void snd_pcm_info_free(snd_pcm_info_t *)")
fn("void snd_pcm_info_copy(snd_pcm_info_t *, const snd_pcm_info_t *)")
fn("unsigned int snd_pcm_info_get_device(const snd_pcm_info_t *)")
fn("unsigned int snd_pcm_info_get_subdevice(const snd_pcm_info_t *)")
fn("snd_pcm_stream_t snd_pcm_info_get_stream(const snd_pcm_info_t *)")
fn("int snd_pcm_info_get_card(const snd_pcm_info_t *)")
fn("const char * snd_pcm_info_get_id(const snd_pcm_info_t *)")
fn("const char * snd_pcm_info_get_name(const snd_pcm_info_t *)")
fn("const char * snd_pcm_info_get_subdevice_name(const snd_pcm_info_t *)")
fn("snd_pcm_class_t snd_pcm_info_get_class(const snd_pcm_info_t *)")
fn("snd_pcm_subclass_t snd_pcm_info_get_subclass(const snd_pcm_info_t *)")
fn("unsigned int snd_pcm_info_get_subdevices_count(const snd_pcm_info_t *)")
fn("unsigned int snd_pcm_info_get_subdevices_avail(const snd_pcm_info_t *)")
fn("snd_pcm_sync_id_t snd_pcm_info_get_sync(const snd_pcm_info_t *)")
fn("void snd_pcm_info_set_device(snd_pcm_info_t *, unsigned int)")
fn("void snd_pcm_info_set_subdevice(snd_pcm_info_t *, unsigned int)")
fn("void snd_pcm_info_set_stream(snd_pcm_info_t *, snd_pcm_stream_t)")
fn("int snd_pcm_hw_params_any(snd_pcm_t *, snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_can_mmap_sample_resolution(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_is_double(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_is_batch(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_is_block_transfer(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_is_monotonic(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_can_overrange(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_can_pause(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_can_resume(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_is_half_duplex(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_is_joint_duplex(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_can_sync_start(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_can_disable_period_wakeup(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_supports_audio_wallclock_ts(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_supports_audio_ts_type(const snd_pcm_hw_params_t *, int)")
fn("int snd_pcm_hw_params_get_rate_numden(const snd_pcm_hw_params_t *, unsigned int *, unsigned int *)")
fn("int snd_pcm_hw_params_get_sbits(const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_get_fifo_size(const snd_pcm_hw_params_t *)")
fn("size_t snd_pcm_hw_params_sizeof()")
fn("int snd_pcm_hw_params_malloc(snd_pcm_hw_params_t **)")
fn("void snd_pcm_hw_params_free(snd_pcm_hw_params_t *)")
fn("void snd_pcm_hw_params_copy(snd_pcm_hw_params_t *, const snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_get_access(const snd_pcm_hw_params_t *, snd_pcm_access_t *)")
fn("int snd_pcm_hw_params_test_access(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_access_t)")
fn("int snd_pcm_hw_params_set_access(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_access_t)")
fn("int snd_pcm_hw_params_set_access_first(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_access_t *)")
fn("int snd_pcm_hw_params_set_access_last(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_access_t *)")
fn("int snd_pcm_hw_params_set_access_mask(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_access_mask_t *)")
fn("int snd_pcm_hw_params_get_access_mask(snd_pcm_hw_params_t *, snd_pcm_access_mask_t *)")
fn("int snd_pcm_hw_params_get_format(const snd_pcm_hw_params_t *, snd_pcm_format_t *)")
fn("int snd_pcm_hw_params_test_format(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_format_t)")
fn("int snd_pcm_hw_params_set_format(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_format_t)")
fn("int snd_pcm_hw_params_set_format_first(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_format_t *)")
fn("int snd_pcm_hw_params_set_format_last(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_format_t *)")
fn("int snd_pcm_hw_params_set_format_mask(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_format_mask_t *)")
fn("void snd_pcm_hw_params_get_format_mask(snd_pcm_hw_params_t *, snd_pcm_format_mask_t *)")
fn("int snd_pcm_hw_params_get_subformat(const snd_pcm_hw_params_t *, snd_pcm_subformat_t *)")
fn("int snd_pcm_hw_params_test_subformat(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_subformat_t)")
fn("int snd_pcm_hw_params_set_subformat(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_subformat_t)")
fn("int snd_pcm_hw_params_set_subformat_first(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_subformat_t *)")
fn("int snd_pcm_hw_params_set_subformat_last(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_subformat_t *)")
fn("int snd_pcm_hw_params_set_subformat_mask(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_subformat_mask_t *)")
fn("void snd_pcm_hw_params_get_subformat_mask(snd_pcm_hw_params_t *, snd_pcm_subformat_mask_t *)")
fn("int snd_pcm_hw_params_get_channels(const snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_get_channels_min(const snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_get_channels_max(const snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_test_channels(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int)")
fn("int snd_pcm_hw_params_set_channels(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int)")
fn("int snd_pcm_hw_params_set_channels_min(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_set_channels_max(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_set_channels_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, unsigned int *)")
fn("int snd_pcm_hw_params_set_channels_near(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_set_channels_first(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_set_channels_last(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_get_rate(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_rate_min(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_rate_max(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_test_rate(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_rate(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_rate_min(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_rate_max(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_rate_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_rate_near(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_rate_first(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_rate_last(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_rate_resample(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int)")
fn("int snd_pcm_hw_params_get_rate_resample(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_set_export_buffer(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int)")
fn("int snd_pcm_hw_params_get_export_buffer(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_set_period_wakeup(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int)")
fn("int snd_pcm_hw_params_get_period_wakeup(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *)")
fn("int snd_pcm_hw_params_get_period_time(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_period_time_min(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_period_time_max(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_test_period_time(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_period_time(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_period_time_min(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_period_time_max(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_period_time_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_period_time_near(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_period_time_first(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_period_time_last(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_period_size(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_get_period_size_min(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_get_period_size_max(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_test_period_size(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t, int)")
fn("int snd_pcm_hw_params_set_period_size(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t, int)")
fn("int snd_pcm_hw_params_set_period_size_min(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_set_period_size_max(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_set_period_size_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_set_period_size_near(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_set_period_size_first(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_set_period_size_last(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, int *)")
fn("int snd_pcm_hw_params_set_period_size_integer(snd_pcm_t *, snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_get_periods(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_periods_min(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_periods_max(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_test_periods(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_periods(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_periods_min(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_periods_max(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_periods_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_periods_near(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_periods_first(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_periods_last(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_periods_integer(snd_pcm_t *, snd_pcm_hw_params_t *)")
fn("int snd_pcm_hw_params_get_buffer_time(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_buffer_time_min(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_buffer_time_max(const snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_test_buffer_time(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_buffer_time(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int, int)")
fn("int snd_pcm_hw_params_set_buffer_time_min(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_buffer_time_max(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_buffer_time_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_buffer_time_near(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_buffer_time_first(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_set_buffer_time_last(snd_pcm_t *, snd_pcm_hw_params_t *, unsigned int *, int *)")
fn("int snd_pcm_hw_params_get_buffer_size(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_get_buffer_size_min(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_get_buffer_size_max(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_test_buffer_size(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_hw_params_set_buffer_size(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_hw_params_set_buffer_size_min(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_set_buffer_size_max(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_set_buffer_size_minmax(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_set_buffer_size_near(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_set_buffer_size_first(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_set_buffer_size_last(snd_pcm_t *, snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_hw_params_get_min_align(const snd_pcm_hw_params_t *, snd_pcm_uframes_t *)")
fn("size_t snd_pcm_sw_params_sizeof()")
fn("int snd_pcm_sw_params_malloc(snd_pcm_sw_params_t **)")
fn("void snd_pcm_sw_params_free(snd_pcm_sw_params_t *)")
fn("void snd_pcm_sw_params_copy(snd_pcm_sw_params_t *, const snd_pcm_sw_params_t *)")
fn("int snd_pcm_sw_params_get_boundary(const snd_pcm_sw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_sw_params_set_tstamp_mode(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_tstamp_t)")
fn("int snd_pcm_sw_params_get_tstamp_mode(const snd_pcm_sw_params_t *, snd_pcm_tstamp_t *)")
fn("int snd_pcm_sw_params_set_tstamp_type(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_tstamp_type_t)")
fn("int snd_pcm_sw_params_get_tstamp_type(const snd_pcm_sw_params_t *, snd_pcm_tstamp_type_t *)")
fn("int snd_pcm_sw_params_set_avail_min(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_sw_params_get_avail_min(const snd_pcm_sw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_sw_params_set_period_event(snd_pcm_t *, snd_pcm_sw_params_t *, int)")
fn("int snd_pcm_sw_params_get_period_event(const snd_pcm_sw_params_t *, int *)")
fn("int snd_pcm_sw_params_set_start_threshold(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_sw_params_get_start_threshold(const snd_pcm_sw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_sw_params_set_stop_threshold(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_sw_params_get_stop_threshold(const snd_pcm_sw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_sw_params_set_silence_threshold(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_sw_params_get_silence_threshold(const snd_pcm_sw_params_t *, snd_pcm_uframes_t *)")
fn("int snd_pcm_sw_params_set_silence_size(snd_pcm_t *, snd_pcm_sw_params_t *, snd_pcm_uframes_t)")
fn("int snd_pcm_sw_params_get_silence_size(const snd_pcm_sw_params_t *, snd_pcm_uframes_t *)")
fn("size_t snd_pcm_access_mask_sizeof()")
fn("int snd_pcm_access_mask_malloc(snd_pcm_access_mask_t **)")
fn("void snd_pcm_access_mask_free(snd_pcm_access_mask_t *)")
fn("void snd_pcm_access_mask_copy(snd_pcm_access_mask_t *, const snd_pcm_access_mask_t *)")
fn("void snd_pcm_access_mask_none(snd_pcm_access_mask_t *)")
fn("void snd_pcm_access_mask_any(snd_pcm_access_mask_t *)")
fn("int snd_pcm_access_mask_test(const snd_pcm_access_mask_t *, snd_pcm_access_t)")
fn("int snd_pcm_access_mask_empty(const snd_pcm_access_mask_t *)")
fn("void snd_pcm_access_mask_set(snd_pcm_access_mask_t *, snd_pcm_access_t)")
fn("void snd_pcm_access_mask_reset(snd_pcm_access_mask_t *, snd_pcm_access_t)")
fn("size_t snd_pcm_format_mask_sizeof()")
fn("int snd_pcm_format_mask_malloc(snd_pcm_format_mask_t **)")
fn("void snd_pcm_format_mask_free(snd_pcm_format_mask_t *)")
fn("void snd_pcm_format_mask_copy(snd_pcm_format_mask_t *, const snd_pcm_format_mask_t *)")
fn("void snd_pcm_format_mask_none(snd_pcm_format_mask_t *)")
fn("void snd_pcm_format_mask_any(snd_pcm_format_mask_t *)")
fn("int snd_pcm_format_mask_test(const snd_pcm_format_mask_t *, snd_pcm_format_t)")
fn("int snd_pcm_format_mask_empty(const snd_pcm_format_mask_t *)")
fn("void snd_pcm_format_mask_set(snd_pcm_format_mask_t *, snd_pcm_format_t)")
fn("void snd_pcm_format_mask_reset(snd_pcm_format_mask_t *, snd_pcm_format_t)")
fn("size_t snd_pcm_subformat_mask_sizeof()")
fn("int snd_pcm_subformat_mask_malloc(snd_pcm_subformat_mask_t **)")
fn("void snd_pcm_subformat_mask_free(snd_pcm_subformat_mask_t *)")
fn("void snd_pcm_subformat_mask_copy(snd_pcm_subformat_mask_t *, const snd_pcm_subformat_mask_t *)")
fn("void snd_pcm_subformat_mask_none(snd_pcm_subformat_mask_t *)")
fn("void snd_pcm_subformat_mask_any(snd_pcm_subformat_mask_t *)")
fn("int snd_pcm_subformat_mask_test(const snd_pcm_subformat_mask_t *, snd_pcm_subformat_t)")
fn("int snd_pcm_subformat_mask_empty(const snd_pcm_subformat_mask_t *)")
fn("void snd_pcm_subformat_mask_set(snd_pcm_subformat_mask_t *, snd_pcm_subformat_t)")
fn("void snd_pcm_subformat_mask_reset(snd_pcm_subformat_mask_t *, snd_pcm_subformat_t)")
fn("size_t snd_pcm_status_sizeof()")
fn("int snd_pcm_status_malloc(snd_pcm_status_t **)")
fn("void snd_pcm_status_free(snd_pcm_status_t *)")
fn("void snd_pcm_status_copy(snd_pcm_status_t *, const snd_pcm_status_t *)")
fn("snd_pcm_state_t snd_pcm_status_get_state(const snd_pcm_status_t *)")
fn("void snd_pcm_status_get_trigger_tstamp(const snd_pcm_status_t *, snd_timestamp_t *)")
fn("void snd_pcm_status_get_trigger_htstamp(const snd_pcm_status_t *, snd_htimestamp_t *)")
fn("void snd_pcm_status_get_tstamp(const snd_pcm_status_t *, snd_timestamp_t *)")
fn("void snd_pcm_status_get_htstamp(const snd_pcm_status_t *, snd_htimestamp_t *)")
fn("void snd_pcm_status_get_audio_htstamp(const snd_pcm_status_t *, snd_htimestamp_t *)")
fn("void snd_pcm_status_get_driver_htstamp(const snd_pcm_status_t *, snd_htimestamp_t *)")
fn("void snd_pcm_status_get_audio_htstamp_report(const snd_pcm_status_t *, snd_pcm_audio_tstamp_report_t *)")
fn("void snd_pcm_status_set_audio_htstamp_config(snd_pcm_status_t *, snd_pcm_audio_tstamp_config_t *)")
fn("snd_pcm_sframes_t snd_pcm_status_get_delay(const snd_pcm_status_t *)")
fn("snd_pcm_uframes_t snd_pcm_status_get_avail(const snd_pcm_status_t *)")
fn("snd_pcm_uframes_t snd_pcm_status_get_avail_max(const snd_pcm_status_t *)")
fn("snd_pcm_uframes_t snd_pcm_status_get_overrange(const snd_pcm_status_t *)")
fn("const char * snd_pcm_type_name(snd_pcm_type_t)")
#fn("const char * snd_pcm_stream_name(const snd_pcm_stream_t)")
#fn("const char * snd_pcm_access_name(const snd_pcm_access_t)")
#fn("const char * snd_pcm_format_name(const snd_pcm_format_t)")
#fn("const char * snd_pcm_format_description(const snd_pcm_format_t)")
#fn("const char * snd_pcm_subformat_name(const snd_pcm_subformat_t)")
#fn("const char * snd_pcm_subformat_description(const snd_pcm_subformat_t)")
fn("snd_pcm_format_t snd_pcm_format_value(const char *)")
# fn("const char * snd_pcm_tstamp_mode_name(const snd_pcm_tstamp_t)")
# fn("const char * snd_pcm_state_name(const snd_pcm_state_t)")
fn("int snd_pcm_dump(snd_pcm_t *, snd_output_t *)")
fn("int snd_pcm_dump_hw_setup(snd_pcm_t *, snd_output_t *)")
fn("int snd_pcm_dump_sw_setup(snd_pcm_t *, snd_output_t *)")
fn("int snd_pcm_dump_setup(snd_pcm_t *, snd_output_t *)")
fn("int snd_pcm_hw_params_dump(snd_pcm_hw_params_t *, snd_output_t *)")
fn("int snd_pcm_sw_params_dump(snd_pcm_sw_params_t *, snd_output_t *)")
fn("int snd_pcm_status_dump(snd_pcm_status_t *, snd_output_t *)")
fn("int snd_pcm_mmap_begin(snd_pcm_t *, const snd_pcm_channel_area_t **, snd_pcm_uframes_t *, snd_pcm_uframes_t *)")
fn("snd_pcm_sframes_t snd_pcm_mmap_commit(snd_pcm_t *, snd_pcm_uframes_t, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_mmap_writei(snd_pcm_t *, const void *, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_mmap_readi(snd_pcm_t *, void *, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_mmap_writen(snd_pcm_t *, void **, snd_pcm_uframes_t)")
fn("snd_pcm_sframes_t snd_pcm_mmap_readn(snd_pcm_t *, void **, snd_pcm_uframes_t)")
fn("int snd_pcm_format_signed(snd_pcm_format_t)")
fn("int snd_pcm_format_unsigned(snd_pcm_format_t)")
fn("int snd_pcm_format_linear(snd_pcm_format_t)")
fn("int snd_pcm_format_float(snd_pcm_format_t)")
fn("int snd_pcm_format_little_endian(snd_pcm_format_t)")
fn("int snd_pcm_format_big_endian(snd_pcm_format_t)")
fn("int snd_pcm_format_cpu_endian(snd_pcm_format_t)")
fn("int snd_pcm_format_width(snd_pcm_format_t)")
fn("int snd_pcm_format_physical_width(snd_pcm_format_t)")
fn("snd_pcm_format_t snd_pcm_build_linear_format(int, int, int, int)")
fn("ssize_t snd_pcm_format_size(snd_pcm_format_t, size_t)")
fn("uint8_t snd_pcm_format_silence(snd_pcm_format_t)")
fn("uint16_t snd_pcm_format_silence_16(snd_pcm_format_t)")
fn("uint32_t snd_pcm_format_silence_32(snd_pcm_format_t)")
fn("uint64_t snd_pcm_format_silence_64(snd_pcm_format_t)")
fn("int snd_pcm_format_set_silence(snd_pcm_format_t, void *, unsigned int)")
fn("snd_pcm_sframes_t snd_pcm_bytes_to_frames(snd_pcm_t *, ssize_t)")
fn("ssize_t snd_pcm_frames_to_bytes(snd_pcm_t *, snd_pcm_sframes_t)")
fn("long snd_pcm_bytes_to_samples(snd_pcm_t *, ssize_t)")
fn("ssize_t snd_pcm_samples_to_bytes(snd_pcm_t *, long)")
fn("int snd_pcm_area_silence(const snd_pcm_channel_area_t *, snd_pcm_uframes_t, unsigned int, snd_pcm_format_t)")
fn("int snd_pcm_areas_silence(const snd_pcm_channel_area_t *, snd_pcm_uframes_t, unsigned int, snd_pcm_uframes_t, snd_pcm_format_t)")
fn("int snd_pcm_area_copy(const snd_pcm_channel_area_t *, snd_pcm_uframes_t, const snd_pcm_channel_area_t *, snd_pcm_uframes_t, unsigned int, snd_pcm_format_t)")
fn("int snd_pcm_areas_copy(const snd_pcm_channel_area_t *, snd_pcm_uframes_t, const snd_pcm_channel_area_t *, snd_pcm_uframes_t, unsigned int, snd_pcm_uframes_t, snd_pcm_format_t)")
# fn("int snd_pcm_areas_copy_wrap(const snd_pcm_channel_area_t *, snd_pcm_uframes_t, const snd_pcm_uframes_t, const snd_pcm_channel_area_t *, snd_pcm_uframes_t, const snd_pcm_uframes_t, const unsigned int, snd_pcm_uframes_t, const snd_pcm_format_t)")
fn("snd_pcm_t * snd_pcm_hook_get_pcm(snd_pcm_hook_t *)")
fn("void * snd_pcm_hook_get_private(snd_pcm_hook_t *)")
fn("void snd_pcm_hook_set_private(snd_pcm_hook_t *, void *)")
fn("int snd_pcm_hook_add(snd_pcm_hook_t **, snd_pcm_t *, snd_pcm_hook_type_t, snd_pcm_hook_func_t, void *)")
fn("int snd_pcm_hook_remove(snd_pcm_hook_t *)")
fn("snd_pcm_uframes_t snd_pcm_meter_get_bufsize(snd_pcm_t *)")
fn("unsigned int snd_pcm_meter_get_channels(snd_pcm_t *)")
fn("unsigned int snd_pcm_meter_get_rate(snd_pcm_t *)")
fn("snd_pcm_uframes_t snd_pcm_meter_get_now(snd_pcm_t *)")
fn("snd_pcm_uframes_t snd_pcm_meter_get_boundary(snd_pcm_t *)")
fn("int snd_pcm_meter_add_scope(snd_pcm_t *, snd_pcm_scope_t *)")
fn("snd_pcm_scope_t * snd_pcm_meter_search_scope(snd_pcm_t *, const char *)")
fn("int snd_pcm_scope_malloc(snd_pcm_scope_t **)")
fn("void snd_pcm_scope_set_ops(snd_pcm_scope_t *, const snd_pcm_scope_ops_t *)")
fn("void snd_pcm_scope_set_name(snd_pcm_scope_t *, const char *)")
fn("const char * snd_pcm_scope_get_name(snd_pcm_scope_t *)")
fn("void * snd_pcm_scope_get_callback_private(snd_pcm_scope_t *)")
fn("void snd_pcm_scope_set_callback_private(snd_pcm_scope_t *, void *)")
fn("int snd_pcm_scope_s16_open(snd_pcm_t *, const char *, snd_pcm_scope_t **)")
fn("int16_t * snd_pcm_scope_s16_get_channel_buffer(snd_pcm_scope_t *, unsigned int)")
fn("int snd_spcm_init(snd_pcm_t *, unsigned int, unsigned int, snd_pcm_format_t, snd_pcm_subformat_t, snd_spcm_latency_t, snd_pcm_access_t, snd_spcm_xrun_type_t)")
fn("int snd_spcm_init_duplex(snd_pcm_t *, snd_pcm_t *, unsigned int, unsigned int, snd_pcm_format_t, snd_pcm_subformat_t, snd_spcm_latency_t, snd_pcm_access_t, snd_spcm_xrun_type_t, snd_spcm_duplex_type_t)")
fn("int snd_spcm_init_get_params(snd_pcm_t *, unsigned int *, snd_pcm_uframes_t *, snd_pcm_uframes_t *)")
fn("int snd_rawmidi_open(snd_rawmidi_t **, snd_rawmidi_t **, const char *, int)")
fn("int snd_rawmidi_open_lconf(snd_rawmidi_t **, snd_rawmidi_t **, const char *, int, snd_config_t *)")
fn("int snd_rawmidi_close(snd_rawmidi_t *)")
fn("int snd_rawmidi_poll_descriptors_count(snd_rawmidi_t *)")
fn("int snd_rawmidi_poll_descriptors(snd_rawmidi_t *, struct pollfd *, unsigned int)")
fn("int snd_rawmidi_poll_descriptors_revents(snd_rawmidi_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_rawmidi_nonblock(snd_rawmidi_t *, int)")
fn("size_t snd_rawmidi_info_sizeof()")
fn("int snd_rawmidi_info_malloc(snd_rawmidi_info_t **)")
fn("void snd_rawmidi_info_free(snd_rawmidi_info_t *)")
fn("void snd_rawmidi_info_copy(snd_rawmidi_info_t *, const snd_rawmidi_info_t *)")
fn("unsigned int snd_rawmidi_info_get_device(const snd_rawmidi_info_t *)")
fn("unsigned int snd_rawmidi_info_get_subdevice(const snd_rawmidi_info_t *)")
fn("snd_rawmidi_stream_t snd_rawmidi_info_get_stream(const snd_rawmidi_info_t *)")
fn("int snd_rawmidi_info_get_card(const snd_rawmidi_info_t *)")
fn("unsigned int snd_rawmidi_info_get_flags(const snd_rawmidi_info_t *)")
fn("const char * snd_rawmidi_info_get_id(const snd_rawmidi_info_t *)")
fn("const char * snd_rawmidi_info_get_name(const snd_rawmidi_info_t *)")
fn("const char * snd_rawmidi_info_get_subdevice_name(const snd_rawmidi_info_t *)")
fn("unsigned int snd_rawmidi_info_get_subdevices_count(const snd_rawmidi_info_t *)")
fn("unsigned int snd_rawmidi_info_get_subdevices_avail(const snd_rawmidi_info_t *)")
fn("void snd_rawmidi_info_set_device(snd_rawmidi_info_t *, unsigned int)")
fn("void snd_rawmidi_info_set_subdevice(snd_rawmidi_info_t *, unsigned int)")
fn("void snd_rawmidi_info_set_stream(snd_rawmidi_info_t *, snd_rawmidi_stream_t)")
fn("int snd_rawmidi_info(snd_rawmidi_t *, snd_rawmidi_info_t *)")
fn("size_t snd_rawmidi_params_sizeof()")
fn("int snd_rawmidi_params_malloc(snd_rawmidi_params_t **)")
fn("void snd_rawmidi_params_free(snd_rawmidi_params_t *)")
fn("void snd_rawmidi_params_copy(snd_rawmidi_params_t *, const snd_rawmidi_params_t *)")
fn("int snd_rawmidi_params_set_buffer_size(snd_rawmidi_t *, snd_rawmidi_params_t *, size_t)")
fn("size_t snd_rawmidi_params_get_buffer_size(const snd_rawmidi_params_t *)")
fn("int snd_rawmidi_params_set_avail_min(snd_rawmidi_t *, snd_rawmidi_params_t *, size_t)")
fn("size_t snd_rawmidi_params_get_avail_min(const snd_rawmidi_params_t *)")
fn("int snd_rawmidi_params_set_no_active_sensing(snd_rawmidi_t *, snd_rawmidi_params_t *, int)")
fn("int snd_rawmidi_params_get_no_active_sensing(const snd_rawmidi_params_t *)")
fn("int snd_rawmidi_params(snd_rawmidi_t *, snd_rawmidi_params_t *)")
fn("int snd_rawmidi_params_current(snd_rawmidi_t *, snd_rawmidi_params_t *)")
fn("size_t snd_rawmidi_status_sizeof()")
fn("int snd_rawmidi_status_malloc(snd_rawmidi_status_t **)")
fn("void snd_rawmidi_status_free(snd_rawmidi_status_t *)")
fn("void snd_rawmidi_status_copy(snd_rawmidi_status_t *, const snd_rawmidi_status_t *)")
fn("void snd_rawmidi_status_get_tstamp(const snd_rawmidi_status_t *, snd_htimestamp_t *)")
fn("size_t snd_rawmidi_status_get_avail(const snd_rawmidi_status_t *)")
fn("size_t snd_rawmidi_status_get_xruns(const snd_rawmidi_status_t *)")
fn("int snd_rawmidi_status(snd_rawmidi_t *, snd_rawmidi_status_t *)")
fn("int snd_rawmidi_drain(snd_rawmidi_t *)")
fn("int snd_rawmidi_drop(snd_rawmidi_t *)")
fn("ssize_t snd_rawmidi_write(snd_rawmidi_t *, const void *, size_t)")
fn("ssize_t snd_rawmidi_read(snd_rawmidi_t *, void *, size_t)")
fn("const char * snd_rawmidi_name(snd_rawmidi_t *)")
fn("snd_rawmidi_type_t snd_rawmidi_type(snd_rawmidi_t *)")
fn("snd_rawmidi_stream_t snd_rawmidi_stream(snd_rawmidi_t *)")
fn("int snd_timer_query_open(snd_timer_query_t **, const char *, int)")
fn("int snd_timer_query_open_lconf(snd_timer_query_t **, const char *, int, snd_config_t *)")
fn("int snd_timer_query_close(snd_timer_query_t *)")
fn("int snd_timer_query_next_device(snd_timer_query_t *, snd_timer_id_t *)")
fn("int snd_timer_query_info(snd_timer_query_t *, snd_timer_ginfo_t *)")
fn("int snd_timer_query_params(snd_timer_query_t *, snd_timer_gparams_t *)")
fn("int snd_timer_query_status(snd_timer_query_t *, snd_timer_gstatus_t *)")
fn("int snd_timer_open(snd_timer_t **, const char *, int)")
fn("int snd_timer_open_lconf(snd_timer_t **, const char *, int, snd_config_t *)")
fn("int snd_timer_close(snd_timer_t *)")
fn("int snd_async_add_timer_handler(snd_async_handler_t **, snd_timer_t *, snd_async_callback_t, void *)")
fn("snd_timer_t * snd_async_handler_get_timer(snd_async_handler_t *)")
fn("int snd_timer_poll_descriptors_count(snd_timer_t *)")
fn("int snd_timer_poll_descriptors(snd_timer_t *, struct pollfd *, unsigned int)")
fn("int snd_timer_poll_descriptors_revents(snd_timer_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_timer_info(snd_timer_t *, snd_timer_info_t *)")
fn("int snd_timer_params(snd_timer_t *, snd_timer_params_t *)")
fn("int snd_timer_status(snd_timer_t *, snd_timer_status_t *)")
fn("int snd_timer_start(snd_timer_t *)")
fn("int snd_timer_stop(snd_timer_t *)")
fn("int snd_timer_continue(snd_timer_t *)")
fn("ssize_t snd_timer_read(snd_timer_t *, void *, size_t)")
fn("size_t snd_timer_id_sizeof()")
fn("int snd_timer_id_malloc(snd_timer_id_t **)")
fn("void snd_timer_id_free(snd_timer_id_t *)")
fn("void snd_timer_id_copy(snd_timer_id_t *, const snd_timer_id_t *)")
fn("void snd_timer_id_set_class(snd_timer_id_t *, int)")
fn("int snd_timer_id_get_class(snd_timer_id_t *)")
fn("void snd_timer_id_set_sclass(snd_timer_id_t *, int)")
fn("int snd_timer_id_get_sclass(snd_timer_id_t *)")
fn("void snd_timer_id_set_card(snd_timer_id_t *, int)")
fn("int snd_timer_id_get_card(snd_timer_id_t *)")
fn("void snd_timer_id_set_device(snd_timer_id_t *, int)")
fn("int snd_timer_id_get_device(snd_timer_id_t *)")
fn("void snd_timer_id_set_subdevice(snd_timer_id_t *, int)")
fn("int snd_timer_id_get_subdevice(snd_timer_id_t *)")
fn("size_t snd_timer_ginfo_sizeof()")
fn("int snd_timer_ginfo_malloc(snd_timer_ginfo_t **)")
fn("void snd_timer_ginfo_free(snd_timer_ginfo_t *)")
fn("void snd_timer_ginfo_copy(snd_timer_ginfo_t *, const snd_timer_ginfo_t *)")
fn("int snd_timer_ginfo_set_tid(snd_timer_ginfo_t *, snd_timer_id_t *)")
fn("snd_timer_id_t * snd_timer_ginfo_get_tid(snd_timer_ginfo_t *)")
fn("unsigned int snd_timer_ginfo_get_flags(snd_timer_ginfo_t *)")
fn("int snd_timer_ginfo_get_card(snd_timer_ginfo_t *)")
fn("char * snd_timer_ginfo_get_id(snd_timer_ginfo_t *)")
fn("char * snd_timer_ginfo_get_name(snd_timer_ginfo_t *)")
fn("unsigned long snd_timer_ginfo_get_resolution(snd_timer_ginfo_t *)")
fn("unsigned long snd_timer_ginfo_get_resolution_min(snd_timer_ginfo_t *)")
fn("unsigned long snd_timer_ginfo_get_resolution_max(snd_timer_ginfo_t *)")
fn("unsigned int snd_timer_ginfo_get_clients(snd_timer_ginfo_t *)")
fn("size_t snd_timer_info_sizeof()")
fn("int snd_timer_info_malloc(snd_timer_info_t **)")
fn("void snd_timer_info_free(snd_timer_info_t *)")
fn("void snd_timer_info_copy(snd_timer_info_t *, const snd_timer_info_t *)")
fn("int snd_timer_info_is_slave(snd_timer_info_t *)")
fn("int snd_timer_info_get_card(snd_timer_info_t *)")
fn("const char * snd_timer_info_get_id(snd_timer_info_t *)")
fn("const char * snd_timer_info_get_name(snd_timer_info_t *)")
fn("long snd_timer_info_get_resolution(snd_timer_info_t *)")
fn("size_t snd_timer_params_sizeof()")
fn("int snd_timer_params_malloc(snd_timer_params_t **)")
fn("void snd_timer_params_free(snd_timer_params_t *)")
fn("void snd_timer_params_copy(snd_timer_params_t *, const snd_timer_params_t *)")
fn("int snd_timer_params_set_auto_start(snd_timer_params_t *, int)")
fn("int snd_timer_params_get_auto_start(snd_timer_params_t *)")
fn("int snd_timer_params_set_exclusive(snd_timer_params_t *, int)")
fn("int snd_timer_params_get_exclusive(snd_timer_params_t *)")
fn("int snd_timer_params_set_early_event(snd_timer_params_t *, int)")
fn("int snd_timer_params_get_early_event(snd_timer_params_t *)")
fn("void snd_timer_params_set_ticks(snd_timer_params_t *, long)")
fn("long snd_timer_params_get_ticks(snd_timer_params_t *)")
fn("void snd_timer_params_set_queue_size(snd_timer_params_t *, long)")
fn("long snd_timer_params_get_queue_size(snd_timer_params_t *)")
fn("void snd_timer_params_set_filter(snd_timer_params_t *, unsigned int)")
fn("unsigned int snd_timer_params_get_filter(snd_timer_params_t *)")
fn("size_t snd_timer_status_sizeof()")
fn("int snd_timer_status_malloc(snd_timer_status_t **)")
fn("void snd_timer_status_free(snd_timer_status_t *)")
fn("void snd_timer_status_copy(snd_timer_status_t *, const snd_timer_status_t *)")
fn("snd_htimestamp_t snd_timer_status_get_timestamp(snd_timer_status_t *)")
fn("long snd_timer_status_get_resolution(snd_timer_status_t *)")
fn("long snd_timer_status_get_lost(snd_timer_status_t *)")
fn("long snd_timer_status_get_overrun(snd_timer_status_t *)")
fn("long snd_timer_status_get_queue(snd_timer_status_t *)")
fn("long snd_timer_info_get_ticks(snd_timer_info_t *)")
fn("int snd_hwdep_open(snd_hwdep_t **, const char *, int)")
fn("int snd_hwdep_close(snd_hwdep_t *)")
fn("int snd_hwdep_poll_descriptors(snd_hwdep_t *, struct pollfd *, unsigned int)")
fn("int snd_hwdep_poll_descriptors_count(snd_hwdep_t *)")
fn("int snd_hwdep_poll_descriptors_revents(snd_hwdep_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_hwdep_nonblock(snd_hwdep_t *, int)")
fn("int snd_hwdep_info(snd_hwdep_t *, snd_hwdep_info_t *)")
fn("int snd_hwdep_dsp_status(snd_hwdep_t *, snd_hwdep_dsp_status_t *)")
fn("int snd_hwdep_dsp_load(snd_hwdep_t *, snd_hwdep_dsp_image_t *)")
fn("int snd_hwdep_ioctl(snd_hwdep_t *, unsigned int, void *)")
fn("ssize_t snd_hwdep_write(snd_hwdep_t *, const void *, size_t)")
fn("ssize_t snd_hwdep_read(snd_hwdep_t *, void *, size_t)")
fn("size_t snd_hwdep_info_sizeof()")
fn("int snd_hwdep_info_malloc(snd_hwdep_info_t **)")
fn("void snd_hwdep_info_free(snd_hwdep_info_t *)")
fn("void snd_hwdep_info_copy(snd_hwdep_info_t *, const snd_hwdep_info_t *)")
fn("unsigned int snd_hwdep_info_get_device(const snd_hwdep_info_t *)")
fn("int snd_hwdep_info_get_card(const snd_hwdep_info_t *)")
fn("const char * snd_hwdep_info_get_id(const snd_hwdep_info_t *)")
fn("const char * snd_hwdep_info_get_name(const snd_hwdep_info_t *)")
fn("snd_hwdep_iface_t snd_hwdep_info_get_iface(const snd_hwdep_info_t *)")
fn("void snd_hwdep_info_set_device(snd_hwdep_info_t *, unsigned int)")
fn("size_t snd_hwdep_dsp_status_sizeof()")
fn("int snd_hwdep_dsp_status_malloc(snd_hwdep_dsp_status_t **)")
fn("void snd_hwdep_dsp_status_free(snd_hwdep_dsp_status_t *)")
fn("void snd_hwdep_dsp_status_copy(snd_hwdep_dsp_status_t *, const snd_hwdep_dsp_status_t *)")
fn("unsigned int snd_hwdep_dsp_status_get_version(const snd_hwdep_dsp_status_t *)")
fn("const char * snd_hwdep_dsp_status_get_id(const snd_hwdep_dsp_status_t *)")
fn("unsigned int snd_hwdep_dsp_status_get_num_dsps(const snd_hwdep_dsp_status_t *)")
fn("unsigned int snd_hwdep_dsp_status_get_dsp_loaded(const snd_hwdep_dsp_status_t *)")
fn("unsigned int snd_hwdep_dsp_status_get_chip_ready(const snd_hwdep_dsp_status_t *)")
fn("size_t snd_hwdep_dsp_image_sizeof()")
fn("int snd_hwdep_dsp_image_malloc(snd_hwdep_dsp_image_t **)")
fn("void snd_hwdep_dsp_image_free(snd_hwdep_dsp_image_t *)")
fn("void snd_hwdep_dsp_image_copy(snd_hwdep_dsp_image_t *, const snd_hwdep_dsp_image_t *)")
fn("unsigned int snd_hwdep_dsp_image_get_index(const snd_hwdep_dsp_image_t *)")
fn("const char * snd_hwdep_dsp_image_get_name(const snd_hwdep_dsp_image_t *)")
fn("const void * snd_hwdep_dsp_image_get_image(const snd_hwdep_dsp_image_t *)")
fn("size_t snd_hwdep_dsp_image_get_length(const snd_hwdep_dsp_image_t *)")
fn("void snd_hwdep_dsp_image_set_index(snd_hwdep_dsp_image_t *, unsigned int)")
fn("void snd_hwdep_dsp_image_set_name(snd_hwdep_dsp_image_t *, const char *)")
fn("void snd_hwdep_dsp_image_set_image(snd_hwdep_dsp_image_t *, void *)")
fn("void snd_hwdep_dsp_image_set_length(snd_hwdep_dsp_image_t *, size_t)")
fn("int snd_card_load(int)")
fn("int snd_card_next(int *)")
fn("int snd_card_get_index(const char *)")
fn("int snd_card_get_name(int, char **)")
fn("int snd_card_get_longname(int, char **)")
fn("int snd_device_name_hint(int, const char *, void ***)")
fn("int snd_device_name_free_hint(void **)")
fn("char * snd_device_name_get_hint(const void *, const char *)")
fn("int snd_ctl_open(snd_ctl_t **, const char *, int)")
fn("int snd_ctl_open_lconf(snd_ctl_t **, const char *, int, snd_config_t *)")
fn("int snd_ctl_open_fallback(snd_ctl_t **, snd_config_t *, const char *, const char *, int)")
fn("int snd_ctl_close(snd_ctl_t *)")
fn("int snd_ctl_nonblock(snd_ctl_t *, int)")
fn("int snd_async_add_ctl_handler(snd_async_handler_t **, snd_ctl_t *, snd_async_callback_t, void *)")
fn("snd_ctl_t * snd_async_handler_get_ctl(snd_async_handler_t *)")
fn("int snd_ctl_poll_descriptors_count(snd_ctl_t *)")
fn("int snd_ctl_poll_descriptors(snd_ctl_t *, struct pollfd *, unsigned int)")
fn("int snd_ctl_poll_descriptors_revents(snd_ctl_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_ctl_subscribe_events(snd_ctl_t *, int)")
fn("int snd_ctl_card_info(snd_ctl_t *, snd_ctl_card_info_t *)")
fn("int snd_ctl_elem_list(snd_ctl_t *, snd_ctl_elem_list_t *)")
fn("int snd_ctl_elem_info(snd_ctl_t *, snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_read(snd_ctl_t *, snd_ctl_elem_value_t *)")
fn("int snd_ctl_elem_write(snd_ctl_t *, snd_ctl_elem_value_t *)")
fn("int snd_ctl_elem_lock(snd_ctl_t *, snd_ctl_elem_id_t *)")
fn("int snd_ctl_elem_unlock(snd_ctl_t *, snd_ctl_elem_id_t *)")
fn("int snd_ctl_elem_tlv_read(snd_ctl_t *, const snd_ctl_elem_id_t *, unsigned int *, unsigned int)")
fn("int snd_ctl_elem_tlv_write(snd_ctl_t *, const snd_ctl_elem_id_t *, const unsigned int *)")
fn("int snd_ctl_elem_tlv_command(snd_ctl_t *, const snd_ctl_elem_id_t *, const unsigned int *)")
fn("int snd_ctl_hwdep_next_device(snd_ctl_t *, int *)")
fn("int snd_ctl_hwdep_info(snd_ctl_t *, snd_hwdep_info_t *)")
fn("int snd_ctl_pcm_next_device(snd_ctl_t *, int *)")
fn("int snd_ctl_pcm_info(snd_ctl_t *, snd_pcm_info_t *)")
fn("int snd_ctl_pcm_prefer_subdevice(snd_ctl_t *, int)")
fn("int snd_ctl_rawmidi_next_device(snd_ctl_t *, int *)")
fn("int snd_ctl_rawmidi_info(snd_ctl_t *, snd_rawmidi_info_t *)")
fn("int snd_ctl_rawmidi_prefer_subdevice(snd_ctl_t *, int)")
fn("int snd_ctl_set_power_state(snd_ctl_t *, unsigned int)")
fn("int snd_ctl_get_power_state(snd_ctl_t *, unsigned int *)")
fn("int snd_ctl_read(snd_ctl_t *, snd_ctl_event_t *)")
fn("int snd_ctl_wait(snd_ctl_t *, int)")
fn("const char * snd_ctl_name(snd_ctl_t *)")
fn("snd_ctl_type_t snd_ctl_type(snd_ctl_t *)")
fn("const char * snd_ctl_elem_type_name(snd_ctl_elem_type_t)")
fn("const char * snd_ctl_elem_iface_name(snd_ctl_elem_iface_t)")
fn("const char * snd_ctl_event_type_name(snd_ctl_event_type_t)")
fn("unsigned int snd_ctl_event_elem_get_mask(const snd_ctl_event_t *)")
fn("unsigned int snd_ctl_event_elem_get_numid(const snd_ctl_event_t *)")
fn("void snd_ctl_event_elem_get_id(const snd_ctl_event_t *, snd_ctl_elem_id_t *)")
fn("snd_ctl_elem_iface_t snd_ctl_event_elem_get_interface(const snd_ctl_event_t *)")
fn("unsigned int snd_ctl_event_elem_get_device(const snd_ctl_event_t *)")
fn("unsigned int snd_ctl_event_elem_get_subdevice(const snd_ctl_event_t *)")
fn("const char * snd_ctl_event_elem_get_name(const snd_ctl_event_t *)")
fn("unsigned int snd_ctl_event_elem_get_index(const snd_ctl_event_t *)")
fn("int snd_ctl_elem_list_alloc_space(snd_ctl_elem_list_t *, unsigned int)")
fn("void snd_ctl_elem_list_free_space(snd_ctl_elem_list_t *)")
fn("char * snd_ctl_ascii_elem_id_get(snd_ctl_elem_id_t *)")
fn("int snd_ctl_ascii_elem_id_parse(snd_ctl_elem_id_t *, const char *)")
fn("int snd_ctl_ascii_value_parse(snd_ctl_t *, snd_ctl_elem_value_t *, snd_ctl_elem_info_t *, const char *)")
fn("size_t snd_ctl_elem_id_sizeof()")
fn("int snd_ctl_elem_id_malloc(snd_ctl_elem_id_t **)")
fn("void snd_ctl_elem_id_free(snd_ctl_elem_id_t *)")
fn("void snd_ctl_elem_id_clear(snd_ctl_elem_id_t *)")
fn("void snd_ctl_elem_id_copy(snd_ctl_elem_id_t *, const snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_id_get_numid(const snd_ctl_elem_id_t *)")
fn("snd_ctl_elem_iface_t snd_ctl_elem_id_get_interface(const snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_id_get_device(const snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_id_get_subdevice(const snd_ctl_elem_id_t *)")
fn("const char * snd_ctl_elem_id_get_name(const snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_id_get_index(const snd_ctl_elem_id_t *)")
fn("void snd_ctl_elem_id_set_numid(snd_ctl_elem_id_t *, unsigned int)")
fn("void snd_ctl_elem_id_set_interface(snd_ctl_elem_id_t *, snd_ctl_elem_iface_t)")
fn("void snd_ctl_elem_id_set_device(snd_ctl_elem_id_t *, unsigned int)")
fn("void snd_ctl_elem_id_set_subdevice(snd_ctl_elem_id_t *, unsigned int)")
fn("void snd_ctl_elem_id_set_name(snd_ctl_elem_id_t *, const char *)")
fn("void snd_ctl_elem_id_set_index(snd_ctl_elem_id_t *, unsigned int)")
fn("size_t snd_ctl_card_info_sizeof()")
fn("int snd_ctl_card_info_malloc(snd_ctl_card_info_t **)")
fn("void snd_ctl_card_info_free(snd_ctl_card_info_t *)")
fn("void snd_ctl_card_info_clear(snd_ctl_card_info_t *)")
fn("void snd_ctl_card_info_copy(snd_ctl_card_info_t *, const snd_ctl_card_info_t *)")
fn("int snd_ctl_card_info_get_card(const snd_ctl_card_info_t *)")
fn("const char * snd_ctl_card_info_get_id(const snd_ctl_card_info_t *)")
fn("const char * snd_ctl_card_info_get_driver(const snd_ctl_card_info_t *)")
fn("const char * snd_ctl_card_info_get_name(const snd_ctl_card_info_t *)")
fn("const char * snd_ctl_card_info_get_longname(const snd_ctl_card_info_t *)")
fn("const char * snd_ctl_card_info_get_mixername(const snd_ctl_card_info_t *)")
fn("const char * snd_ctl_card_info_get_components(const snd_ctl_card_info_t *)")
fn("size_t snd_ctl_event_sizeof()")
fn("int snd_ctl_event_malloc(snd_ctl_event_t **)")
fn("void snd_ctl_event_free(snd_ctl_event_t *)")
fn("void snd_ctl_event_clear(snd_ctl_event_t *)")
fn("void snd_ctl_event_copy(snd_ctl_event_t *, const snd_ctl_event_t *)")
fn("snd_ctl_event_type_t snd_ctl_event_get_type(const snd_ctl_event_t *)")
fn("size_t snd_ctl_elem_list_sizeof()")
fn("int snd_ctl_elem_list_malloc(snd_ctl_elem_list_t **)")
fn("void snd_ctl_elem_list_free(snd_ctl_elem_list_t *)")
fn("void snd_ctl_elem_list_clear(snd_ctl_elem_list_t *)")
fn("void snd_ctl_elem_list_copy(snd_ctl_elem_list_t *, const snd_ctl_elem_list_t *)")
fn("void snd_ctl_elem_list_set_offset(snd_ctl_elem_list_t *, unsigned int)")
fn("unsigned int snd_ctl_elem_list_get_used(const snd_ctl_elem_list_t *)")
fn("unsigned int snd_ctl_elem_list_get_count(const snd_ctl_elem_list_t *)")
fn("void snd_ctl_elem_list_get_id(const snd_ctl_elem_list_t *, unsigned int, snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_list_get_numid(const snd_ctl_elem_list_t *, unsigned int)")
fn("snd_ctl_elem_iface_t snd_ctl_elem_list_get_interface(const snd_ctl_elem_list_t *, unsigned int)")
fn("unsigned int snd_ctl_elem_list_get_device(const snd_ctl_elem_list_t *, unsigned int)")
fn("unsigned int snd_ctl_elem_list_get_subdevice(const snd_ctl_elem_list_t *, unsigned int)")
fn("const char * snd_ctl_elem_list_get_name(const snd_ctl_elem_list_t *, unsigned int)")
fn("unsigned int snd_ctl_elem_list_get_index(const snd_ctl_elem_list_t *, unsigned int)")
fn("size_t snd_ctl_elem_info_sizeof()")
fn("int snd_ctl_elem_info_malloc(snd_ctl_elem_info_t **)")
fn("void snd_ctl_elem_info_free(snd_ctl_elem_info_t *)")
fn("void snd_ctl_elem_info_clear(snd_ctl_elem_info_t *)")
fn("void snd_ctl_elem_info_copy(snd_ctl_elem_info_t *, const snd_ctl_elem_info_t *)")
fn("snd_ctl_elem_type_t snd_ctl_elem_info_get_type(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_readable(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_writable(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_volatile(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_inactive(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_locked(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_tlv_readable(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_tlv_writable(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_tlv_commandable(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_owner(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_is_user(const snd_ctl_elem_info_t *)")
fn("pid_t snd_ctl_elem_info_get_owner(const snd_ctl_elem_info_t *)")
fn("unsigned int snd_ctl_elem_info_get_count(const snd_ctl_elem_info_t *)")
fn("long snd_ctl_elem_info_get_min(const snd_ctl_elem_info_t *)")
fn("long snd_ctl_elem_info_get_max(const snd_ctl_elem_info_t *)")
fn("long snd_ctl_elem_info_get_step(const snd_ctl_elem_info_t *)")
fn("long long snd_ctl_elem_info_get_min64(const snd_ctl_elem_info_t *)")
fn("long long snd_ctl_elem_info_get_max64(const snd_ctl_elem_info_t *)")
fn("long long snd_ctl_elem_info_get_step64(const snd_ctl_elem_info_t *)")
fn("unsigned int snd_ctl_elem_info_get_items(const snd_ctl_elem_info_t *)")
fn("void snd_ctl_elem_info_set_item(snd_ctl_elem_info_t *, unsigned int)")
fn("const char * snd_ctl_elem_info_get_item_name(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_get_dimensions(const snd_ctl_elem_info_t *)")
fn("int snd_ctl_elem_info_get_dimension(const snd_ctl_elem_info_t *, unsigned int)")
# fn("int snd_ctl_elem_info_set_dimension(snd_ctl_elem_info_t *, const int [4])")
fn("void snd_ctl_elem_info_get_id(const snd_ctl_elem_info_t *, snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_info_get_numid(const snd_ctl_elem_info_t *)")
fn("snd_ctl_elem_iface_t snd_ctl_elem_info_get_interface(const snd_ctl_elem_info_t *)")
fn("unsigned int snd_ctl_elem_info_get_device(const snd_ctl_elem_info_t *)")
fn("unsigned int snd_ctl_elem_info_get_subdevice(const snd_ctl_elem_info_t *)")
fn("const char * snd_ctl_elem_info_get_name(const snd_ctl_elem_info_t *)")
fn("unsigned int snd_ctl_elem_info_get_index(const snd_ctl_elem_info_t *)")
fn("void snd_ctl_elem_info_set_id(snd_ctl_elem_info_t *, const snd_ctl_elem_id_t *)")
fn("void snd_ctl_elem_info_set_numid(snd_ctl_elem_info_t *, unsigned int)")
fn("void snd_ctl_elem_info_set_interface(snd_ctl_elem_info_t *, snd_ctl_elem_iface_t)")
fn("void snd_ctl_elem_info_set_device(snd_ctl_elem_info_t *, unsigned int)")
fn("void snd_ctl_elem_info_set_subdevice(snd_ctl_elem_info_t *, unsigned int)")
fn("void snd_ctl_elem_info_set_name(snd_ctl_elem_info_t *, const char *)")
fn("void snd_ctl_elem_info_set_index(snd_ctl_elem_info_t *, unsigned int)")
fn("int snd_ctl_add_integer_elem_set(snd_ctl_t *, snd_ctl_elem_info_t *, unsigned int, unsigned int, long, long, long)")
fn("int snd_ctl_add_integer64_elem_set(snd_ctl_t *, snd_ctl_elem_info_t *, unsigned int, unsigned int, long long, long long, long long)")
fn("int snd_ctl_add_boolean_elem_set(snd_ctl_t *, snd_ctl_elem_info_t *, unsigned int, unsigned int)")
# fn("int snd_ctl_add_enumerated_elem_set(snd_ctl_t *, snd_ctl_elem_info_t *, unsigned int, unsigned int, unsigned int, const char *const [])")
fn("int snd_ctl_add_bytes_elem_set(snd_ctl_t *, snd_ctl_elem_info_t *, unsigned int, unsigned int)")
fn("int snd_ctl_elem_add_integer(snd_ctl_t *, const snd_ctl_elem_id_t *, unsigned int, long, long, long)")
fn("int snd_ctl_elem_add_integer64(snd_ctl_t *, const snd_ctl_elem_id_t *, unsigned int, long long, long long, long long)")
fn("int snd_ctl_elem_add_boolean(snd_ctl_t *, const snd_ctl_elem_id_t *, unsigned int)")
# fn("int snd_ctl_elem_add_enumerated(snd_ctl_t *, const snd_ctl_elem_id_t *, unsigned int, unsigned int, const char *const [])")
fn("int snd_ctl_elem_add_iec958(snd_ctl_t *, const snd_ctl_elem_id_t *)")
fn("int snd_ctl_elem_remove(snd_ctl_t *, snd_ctl_elem_id_t *)")
fn("size_t snd_ctl_elem_value_sizeof()")
fn("int snd_ctl_elem_value_malloc(snd_ctl_elem_value_t **)")
fn("void snd_ctl_elem_value_free(snd_ctl_elem_value_t *)")
fn("void snd_ctl_elem_value_clear(snd_ctl_elem_value_t *)")
fn("void snd_ctl_elem_value_copy(snd_ctl_elem_value_t *, const snd_ctl_elem_value_t *)")
fn("int snd_ctl_elem_value_compare(snd_ctl_elem_value_t *, const snd_ctl_elem_value_t *)")
fn("void snd_ctl_elem_value_get_id(const snd_ctl_elem_value_t *, snd_ctl_elem_id_t *)")
fn("unsigned int snd_ctl_elem_value_get_numid(const snd_ctl_elem_value_t *)")
fn("snd_ctl_elem_iface_t snd_ctl_elem_value_get_interface(const snd_ctl_elem_value_t *)")
fn("unsigned int snd_ctl_elem_value_get_device(const snd_ctl_elem_value_t *)")
fn("unsigned int snd_ctl_elem_value_get_subdevice(const snd_ctl_elem_value_t *)")
fn("const char * snd_ctl_elem_value_get_name(const snd_ctl_elem_value_t *)")
fn("unsigned int snd_ctl_elem_value_get_index(const snd_ctl_elem_value_t *)")
fn("void snd_ctl_elem_value_set_id(snd_ctl_elem_value_t *, const snd_ctl_elem_id_t *)")
fn("void snd_ctl_elem_value_set_numid(snd_ctl_elem_value_t *, unsigned int)")
fn("void snd_ctl_elem_value_set_interface(snd_ctl_elem_value_t *, snd_ctl_elem_iface_t)")
fn("void snd_ctl_elem_value_set_device(snd_ctl_elem_value_t *, unsigned int)")
fn("void snd_ctl_elem_value_set_subdevice(snd_ctl_elem_value_t *, unsigned int)")
fn("void snd_ctl_elem_value_set_name(snd_ctl_elem_value_t *, const char *)")
fn("void snd_ctl_elem_value_set_index(snd_ctl_elem_value_t *, unsigned int)")
fn("int snd_ctl_elem_value_get_boolean(const snd_ctl_elem_value_t *, unsigned int)")
fn("long snd_ctl_elem_value_get_integer(const snd_ctl_elem_value_t *, unsigned int)")
fn("long long snd_ctl_elem_value_get_integer64(const snd_ctl_elem_value_t *, unsigned int)")
fn("unsigned int snd_ctl_elem_value_get_enumerated(const snd_ctl_elem_value_t *, unsigned int)")
fn("unsigned char snd_ctl_elem_value_get_byte(const snd_ctl_elem_value_t *, unsigned int)")
fn("void snd_ctl_elem_value_set_boolean(snd_ctl_elem_value_t *, unsigned int, long)")
fn("void snd_ctl_elem_value_set_integer(snd_ctl_elem_value_t *, unsigned int, long)")
fn("void snd_ctl_elem_value_set_integer64(snd_ctl_elem_value_t *, unsigned int, long long)")
fn("void snd_ctl_elem_value_set_enumerated(snd_ctl_elem_value_t *, unsigned int, unsigned int)")
fn("void snd_ctl_elem_value_set_byte(snd_ctl_elem_value_t *, unsigned int, unsigned char)")
fn("void snd_ctl_elem_set_bytes(snd_ctl_elem_value_t *, void *, size_t)")
fn("const void * snd_ctl_elem_value_get_bytes(const snd_ctl_elem_value_t *)")
fn("void snd_ctl_elem_value_get_iec958(const snd_ctl_elem_value_t *, snd_aes_iec958_t *)")
fn("void snd_ctl_elem_value_set_iec958(snd_ctl_elem_value_t *, const snd_aes_iec958_t *)")
fn("int snd_tlv_parse_dB_info(unsigned int *, unsigned int, unsigned int **)")
fn("int snd_tlv_get_dB_range(unsigned int *, long, long, long *, long *)")
fn("int snd_tlv_convert_to_dB(unsigned int *, long, long, long, long *)")
fn("int snd_tlv_convert_from_dB(unsigned int *, long, long, long, long *, int)")
fn("int snd_ctl_get_dB_range(snd_ctl_t *, const snd_ctl_elem_id_t *, long *, long *)")
fn("int snd_ctl_convert_to_dB(snd_ctl_t *, const snd_ctl_elem_id_t *, long, long *)")
fn("int snd_ctl_convert_from_dB(snd_ctl_t *, const snd_ctl_elem_id_t *, long, long *, int)")
fn("int snd_hctl_compare_fast(const snd_hctl_elem_t *, const snd_hctl_elem_t *)")
fn("int snd_hctl_open(snd_hctl_t **, const char *, int)")
fn("int snd_hctl_open_ctl(snd_hctl_t **, snd_ctl_t *)")
fn("int snd_hctl_close(snd_hctl_t *)")
fn("int snd_hctl_nonblock(snd_hctl_t *, int)")
fn("int snd_hctl_poll_descriptors_count(snd_hctl_t *)")
fn("int snd_hctl_poll_descriptors(snd_hctl_t *, struct pollfd *, unsigned int)")
fn("int snd_hctl_poll_descriptors_revents(snd_hctl_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("unsigned int snd_hctl_get_count(snd_hctl_t *)")
fn("int snd_hctl_set_compare(snd_hctl_t *, snd_hctl_compare_t)")
fn("snd_hctl_elem_t * snd_hctl_first_elem(snd_hctl_t *)")
fn("snd_hctl_elem_t * snd_hctl_last_elem(snd_hctl_t *)")
fn("snd_hctl_elem_t * snd_hctl_find_elem(snd_hctl_t *, const snd_ctl_elem_id_t *)")
fn("void snd_hctl_set_callback(snd_hctl_t *, snd_hctl_callback_t)")
fn("void snd_hctl_set_callback_private(snd_hctl_t *, void *)")
fn("void * snd_hctl_get_callback_private(snd_hctl_t *)")
fn("int snd_hctl_load(snd_hctl_t *)")
fn("int snd_hctl_free(snd_hctl_t *)")
fn("int snd_hctl_handle_events(snd_hctl_t *)")
fn("const char * snd_hctl_name(snd_hctl_t *)")
fn("int snd_hctl_wait(snd_hctl_t *, int)")
fn("snd_ctl_t * snd_hctl_ctl(snd_hctl_t *)")
fn("snd_hctl_elem_t * snd_hctl_elem_next(snd_hctl_elem_t *)")
fn("snd_hctl_elem_t * snd_hctl_elem_prev(snd_hctl_elem_t *)")
fn("int snd_hctl_elem_info(snd_hctl_elem_t *, snd_ctl_elem_info_t *)")
fn("int snd_hctl_elem_read(snd_hctl_elem_t *, snd_ctl_elem_value_t *)")
fn("int snd_hctl_elem_write(snd_hctl_elem_t *, snd_ctl_elem_value_t *)")
fn("int snd_hctl_elem_tlv_read(snd_hctl_elem_t *, unsigned int *, unsigned int)")
fn("int snd_hctl_elem_tlv_write(snd_hctl_elem_t *, const unsigned int *)")
fn("int snd_hctl_elem_tlv_command(snd_hctl_elem_t *, const unsigned int *)")
fn("snd_hctl_t * snd_hctl_elem_get_hctl(snd_hctl_elem_t *)")
fn("void snd_hctl_elem_get_id(const snd_hctl_elem_t *, snd_ctl_elem_id_t *)")
fn("unsigned int snd_hctl_elem_get_numid(const snd_hctl_elem_t *)")
fn("snd_ctl_elem_iface_t snd_hctl_elem_get_interface(const snd_hctl_elem_t *)")
fn("unsigned int snd_hctl_elem_get_device(const snd_hctl_elem_t *)")
fn("unsigned int snd_hctl_elem_get_subdevice(const snd_hctl_elem_t *)")
fn("const char * snd_hctl_elem_get_name(const snd_hctl_elem_t *)")
fn("unsigned int snd_hctl_elem_get_index(const snd_hctl_elem_t *)")
fn("void snd_hctl_elem_set_callback(snd_hctl_elem_t *, snd_hctl_elem_callback_t)")
fn("void * snd_hctl_elem_get_callback_private(const snd_hctl_elem_t *)")
fn("void snd_hctl_elem_set_callback_private(snd_hctl_elem_t *, void *)")
fn("int snd_sctl_build(snd_sctl_t **, snd_ctl_t *, snd_config_t *, snd_config_t *, int)")
fn("int snd_sctl_free(snd_sctl_t *)")
fn("int snd_sctl_install(snd_sctl_t *)")
fn("int snd_sctl_remove(snd_sctl_t *)")
fn("int snd_mixer_open(snd_mixer_t **, int)")
fn("int snd_mixer_close(snd_mixer_t *)")
fn("snd_mixer_elem_t * snd_mixer_first_elem(snd_mixer_t *)")
fn("snd_mixer_elem_t * snd_mixer_last_elem(snd_mixer_t *)")
fn("int snd_mixer_handle_events(snd_mixer_t *)")
fn("int snd_mixer_attach(snd_mixer_t *, const char *)")
fn("int snd_mixer_attach_hctl(snd_mixer_t *, snd_hctl_t *)")
fn("int snd_mixer_detach(snd_mixer_t *, const char *)")
fn("int snd_mixer_detach_hctl(snd_mixer_t *, snd_hctl_t *)")
fn("int snd_mixer_get_hctl(snd_mixer_t *, const char *, snd_hctl_t **)")
fn("int snd_mixer_poll_descriptors_count(snd_mixer_t *)")
fn("int snd_mixer_poll_descriptors(snd_mixer_t *, struct pollfd *, unsigned int)")
fn("int snd_mixer_poll_descriptors_revents(snd_mixer_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_mixer_load(snd_mixer_t *)")
fn("void snd_mixer_free(snd_mixer_t *)")
fn("int snd_mixer_wait(snd_mixer_t *, int)")
fn("int snd_mixer_set_compare(snd_mixer_t *, snd_mixer_compare_t)")
fn("void snd_mixer_set_callback(snd_mixer_t *, snd_mixer_callback_t)")
fn("void * snd_mixer_get_callback_private(const snd_mixer_t *)")
fn("void snd_mixer_set_callback_private(snd_mixer_t *, void *)")
fn("unsigned int snd_mixer_get_count(const snd_mixer_t *)")
fn("int snd_mixer_class_unregister(snd_mixer_class_t *)")
fn("snd_mixer_elem_t * snd_mixer_elem_next(snd_mixer_elem_t *)")
fn("snd_mixer_elem_t * snd_mixer_elem_prev(snd_mixer_elem_t *)")
fn("void snd_mixer_elem_set_callback(snd_mixer_elem_t *, snd_mixer_elem_callback_t)")
fn("void * snd_mixer_elem_get_callback_private(const snd_mixer_elem_t *)")
fn("void snd_mixer_elem_set_callback_private(snd_mixer_elem_t *, void *)")
fn("snd_mixer_elem_type_t snd_mixer_elem_get_type(const snd_mixer_elem_t *)")
fn("int snd_mixer_class_register(snd_mixer_class_t *, snd_mixer_t *)")
# fn("int snd_mixer_elem_new(snd_mixer_elem_t **, snd_mixer_elem_type_t, int, void *, void (*)(snd_mixer_elem_t *))")
fn("int snd_mixer_elem_add(snd_mixer_elem_t *, snd_mixer_class_t *)")
fn("int snd_mixer_elem_remove(snd_mixer_elem_t *)")
fn("void snd_mixer_elem_free(snd_mixer_elem_t *)")
fn("int snd_mixer_elem_info(snd_mixer_elem_t *)")
fn("int snd_mixer_elem_value(snd_mixer_elem_t *)")
fn("int snd_mixer_elem_attach(snd_mixer_elem_t *, snd_hctl_elem_t *)")
fn("int snd_mixer_elem_detach(snd_mixer_elem_t *, snd_hctl_elem_t *)")
fn("int snd_mixer_elem_empty(snd_mixer_elem_t *)")
fn("void * snd_mixer_elem_get_private(const snd_mixer_elem_t *)")
fn("size_t snd_mixer_class_sizeof()")
fn("int snd_mixer_class_malloc(snd_mixer_class_t **)")
fn("void snd_mixer_class_free(snd_mixer_class_t *)")
fn("void snd_mixer_class_copy(snd_mixer_class_t *, const snd_mixer_class_t *)")
fn("snd_mixer_t * snd_mixer_class_get_mixer(const snd_mixer_class_t *)")
fn("snd_mixer_event_t snd_mixer_class_get_event(const snd_mixer_class_t *)")
fn("void * snd_mixer_class_get_private(const snd_mixer_class_t *)")
fn("snd_mixer_compare_t snd_mixer_class_get_compare(const snd_mixer_class_t *)")
fn("int snd_mixer_class_set_event(snd_mixer_class_t *, snd_mixer_event_t)")
fn("int snd_mixer_class_set_private(snd_mixer_class_t *, void *)")
# fn("int snd_mixer_class_set_private_free(snd_mixer_class_t *, void (*)(snd_mixer_class_t *))")
fn("int snd_mixer_class_set_compare(snd_mixer_class_t *, snd_mixer_compare_t)")
fn("const char * snd_mixer_selem_channel_name(snd_mixer_selem_channel_id_t)")
fn("int snd_mixer_selem_register(snd_mixer_t *, struct snd_mixer_selem_regopt *, snd_mixer_class_t **)")
fn("void snd_mixer_selem_get_id(snd_mixer_elem_t *, snd_mixer_selem_id_t *)")
fn("const char * snd_mixer_selem_get_name(snd_mixer_elem_t *)")
fn("unsigned int snd_mixer_selem_get_index(snd_mixer_elem_t *)")
fn("snd_mixer_elem_t * snd_mixer_find_selem(snd_mixer_t *, const snd_mixer_selem_id_t *)")
fn("int snd_mixer_selem_is_active(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_is_playback_mono(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_playback_channel(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t)")
fn("int snd_mixer_selem_is_capture_mono(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_capture_channel(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t)")
fn("int snd_mixer_selem_get_capture_group(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_common_volume(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_playback_volume(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_playback_volume_joined(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_capture_volume(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_capture_volume_joined(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_common_switch(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_playback_switch(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_playback_switch_joined(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_capture_switch(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_capture_switch_joined(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_has_capture_switch_exclusive(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_ask_playback_vol_dB(snd_mixer_elem_t *, long, long *)")
fn("int snd_mixer_selem_ask_capture_vol_dB(snd_mixer_elem_t *, long, long *)")
fn("int snd_mixer_selem_ask_playback_dB_vol(snd_mixer_elem_t *, long, int, long *)")
fn("int snd_mixer_selem_ask_capture_dB_vol(snd_mixer_elem_t *, long, int, long *)")
fn("int snd_mixer_selem_get_playback_volume(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long *)")
fn("int snd_mixer_selem_get_capture_volume(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long *)")
fn("int snd_mixer_selem_get_playback_dB(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long *)")
fn("int snd_mixer_selem_get_capture_dB(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long *)")
fn("int snd_mixer_selem_get_playback_switch(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, int *)")
fn("int snd_mixer_selem_get_capture_switch(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, int *)")
fn("int snd_mixer_selem_set_playback_volume(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long)")
fn("int snd_mixer_selem_set_capture_volume(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long)")
fn("int snd_mixer_selem_set_playback_dB(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long, int)")
fn("int snd_mixer_selem_set_capture_dB(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, long, int)")
fn("int snd_mixer_selem_set_playback_volume_all(snd_mixer_elem_t *, long)")
fn("int snd_mixer_selem_set_capture_volume_all(snd_mixer_elem_t *, long)")
fn("int snd_mixer_selem_set_playback_dB_all(snd_mixer_elem_t *, long, int)")
fn("int snd_mixer_selem_set_capture_dB_all(snd_mixer_elem_t *, long, int)")
fn("int snd_mixer_selem_set_playback_switch(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, int)")
fn("int snd_mixer_selem_set_capture_switch(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, int)")
fn("int snd_mixer_selem_set_playback_switch_all(snd_mixer_elem_t *, int)")
fn("int snd_mixer_selem_set_capture_switch_all(snd_mixer_elem_t *, int)")
fn("int snd_mixer_selem_get_playback_volume_range(snd_mixer_elem_t *, long *, long *)")
fn("int snd_mixer_selem_get_playback_dB_range(snd_mixer_elem_t *, long *, long *)")
fn("int snd_mixer_selem_set_playback_volume_range(snd_mixer_elem_t *, long, long)")
fn("int snd_mixer_selem_get_capture_volume_range(snd_mixer_elem_t *, long *, long *)")
fn("int snd_mixer_selem_get_capture_dB_range(snd_mixer_elem_t *, long *, long *)")
fn("int snd_mixer_selem_set_capture_volume_range(snd_mixer_elem_t *, long, long)")
fn("int snd_mixer_selem_is_enumerated(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_is_enum_playback(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_is_enum_capture(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_get_enum_items(snd_mixer_elem_t *)")
fn("int snd_mixer_selem_get_enum_item_name(snd_mixer_elem_t *, unsigned int, size_t, char *)")
fn("int snd_mixer_selem_get_enum_item(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, unsigned int *)")
fn("int snd_mixer_selem_set_enum_item(snd_mixer_elem_t *, snd_mixer_selem_channel_id_t, unsigned int)")
fn("size_t snd_mixer_selem_id_sizeof()")
fn("int snd_mixer_selem_id_malloc(snd_mixer_selem_id_t **)")
fn("void snd_mixer_selem_id_free(snd_mixer_selem_id_t *)")
fn("void snd_mixer_selem_id_copy(snd_mixer_selem_id_t *, const snd_mixer_selem_id_t *)")
fn("const char * snd_mixer_selem_id_get_name(const snd_mixer_selem_id_t *)")
fn("unsigned int snd_mixer_selem_id_get_index(const snd_mixer_selem_id_t *)")
fn("void snd_mixer_selem_id_set_name(snd_mixer_selem_id_t *, const char *)")
fn("void snd_mixer_selem_id_set_index(snd_mixer_selem_id_t *, unsigned int)")
fn("int snd_mixer_selem_id_parse(snd_mixer_selem_id_t *, const char *)")
fn("int snd_seq_open(snd_seq_t **, const char *, int, int)")
fn("int snd_seq_open_lconf(snd_seq_t **, const char *, int, int, snd_config_t *)")
fn("const char * snd_seq_name(snd_seq_t *)")
fn("snd_seq_type_t snd_seq_type(snd_seq_t *)")
fn("int snd_seq_close(snd_seq_t *)")
fn("int snd_seq_poll_descriptors_count(snd_seq_t *, short)")
fn("int snd_seq_poll_descriptors(snd_seq_t *, struct pollfd *, unsigned int, short)")
fn("int snd_seq_poll_descriptors_revents(snd_seq_t *, struct pollfd *, unsigned int, unsigned short *)")
fn("int snd_seq_nonblock(snd_seq_t *, int)")
fn("int snd_seq_client_id(snd_seq_t *)")
fn("size_t snd_seq_get_output_buffer_size(snd_seq_t *)")
fn("size_t snd_seq_get_input_buffer_size(snd_seq_t *)")
fn("int snd_seq_set_output_buffer_size(snd_seq_t *, size_t)")
fn("int snd_seq_set_input_buffer_size(snd_seq_t *, size_t)")
fn("size_t snd_seq_system_info_sizeof()")
fn("int snd_seq_system_info_malloc(snd_seq_system_info_t **)")
fn("void snd_seq_system_info_free(snd_seq_system_info_t *)")
fn("void snd_seq_system_info_copy(snd_seq_system_info_t *, const snd_seq_system_info_t *)")
fn("int snd_seq_system_info_get_queues(const snd_seq_system_info_t *)")
fn("int snd_seq_system_info_get_clients(const snd_seq_system_info_t *)")
fn("int snd_seq_system_info_get_ports(const snd_seq_system_info_t *)")
fn("int snd_seq_system_info_get_channels(const snd_seq_system_info_t *)")
fn("int snd_seq_system_info_get_cur_clients(const snd_seq_system_info_t *)")
fn("int snd_seq_system_info_get_cur_queues(const snd_seq_system_info_t *)")
fn("int snd_seq_system_info(snd_seq_t *, snd_seq_system_info_t *)")
fn("size_t snd_seq_client_info_sizeof()")
fn("int snd_seq_client_info_malloc(snd_seq_client_info_t **)")
fn("void snd_seq_client_info_free(snd_seq_client_info_t *)")
fn("void snd_seq_client_info_copy(snd_seq_client_info_t *, const snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_client(const snd_seq_client_info_t *)")
fn("snd_seq_client_type_t snd_seq_client_info_get_type(const snd_seq_client_info_t *)")
fn("const char * snd_seq_client_info_get_name(snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_broadcast_filter(const snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_error_bounce(const snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_card(const snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_pid(const snd_seq_client_info_t *)")
fn("const unsigned char * snd_seq_client_info_get_event_filter(const snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_num_ports(const snd_seq_client_info_t *)")
fn("int snd_seq_client_info_get_event_lost(const snd_seq_client_info_t *)")
fn("void snd_seq_client_info_set_client(snd_seq_client_info_t *, int)")
fn("void snd_seq_client_info_set_name(snd_seq_client_info_t *, const char *)")
fn("void snd_seq_client_info_set_broadcast_filter(snd_seq_client_info_t *, int)")
fn("void snd_seq_client_info_set_error_bounce(snd_seq_client_info_t *, int)")
fn("void snd_seq_client_info_set_event_filter(snd_seq_client_info_t *, unsigned char *)")
fn("void snd_seq_client_info_event_filter_clear(snd_seq_client_info_t *)")
fn("void snd_seq_client_info_event_filter_add(snd_seq_client_info_t *, int)")
fn("void snd_seq_client_info_event_filter_del(snd_seq_client_info_t *, int)")
fn("int snd_seq_client_info_event_filter_check(snd_seq_client_info_t *, int)")
fn("int snd_seq_get_client_info(snd_seq_t *, snd_seq_client_info_t *)")
fn("int snd_seq_get_any_client_info(snd_seq_t *, int, snd_seq_client_info_t *)")
fn("int snd_seq_set_client_info(snd_seq_t *, snd_seq_client_info_t *)")
fn("int snd_seq_query_next_client(snd_seq_t *, snd_seq_client_info_t *)")
fn("size_t snd_seq_client_pool_sizeof()")
fn("int snd_seq_client_pool_malloc(snd_seq_client_pool_t **)")
fn("void snd_seq_client_pool_free(snd_seq_client_pool_t *)")
fn("void snd_seq_client_pool_copy(snd_seq_client_pool_t *, const snd_seq_client_pool_t *)")
fn("int snd_seq_client_pool_get_client(const snd_seq_client_pool_t *)")
fn("size_t snd_seq_client_pool_get_output_pool(const snd_seq_client_pool_t *)")
fn("size_t snd_seq_client_pool_get_input_pool(const snd_seq_client_pool_t *)")
fn("size_t snd_seq_client_pool_get_output_room(const snd_seq_client_pool_t *)")
fn("size_t snd_seq_client_pool_get_output_free(const snd_seq_client_pool_t *)")
fn("size_t snd_seq_client_pool_get_input_free(const snd_seq_client_pool_t *)")
fn("void snd_seq_client_pool_set_output_pool(snd_seq_client_pool_t *, size_t)")
fn("void snd_seq_client_pool_set_input_pool(snd_seq_client_pool_t *, size_t)")
fn("void snd_seq_client_pool_set_output_room(snd_seq_client_pool_t *, size_t)")
fn("int snd_seq_get_client_pool(snd_seq_t *, snd_seq_client_pool_t *)")
fn("int snd_seq_set_client_pool(snd_seq_t *, snd_seq_client_pool_t *)")
fn("size_t snd_seq_port_info_sizeof()")
fn("int snd_seq_port_info_malloc(snd_seq_port_info_t **)")
fn("void snd_seq_port_info_free(snd_seq_port_info_t *)")
fn("void snd_seq_port_info_copy(snd_seq_port_info_t *, const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_client(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_port(const snd_seq_port_info_t *)")
fn("const snd_seq_addr_t * snd_seq_port_info_get_addr(const snd_seq_port_info_t *)")
fn("const char * snd_seq_port_info_get_name(const snd_seq_port_info_t *)")
fn("unsigned int snd_seq_port_info_get_capability(const snd_seq_port_info_t *)")
fn("unsigned int snd_seq_port_info_get_type(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_midi_channels(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_midi_voices(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_synth_voices(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_read_use(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_write_use(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_port_specified(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_timestamping(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_timestamp_real(const snd_seq_port_info_t *)")
fn("int snd_seq_port_info_get_timestamp_queue(const snd_seq_port_info_t *)")
fn("void snd_seq_port_info_set_client(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_port(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_addr(snd_seq_port_info_t *, const snd_seq_addr_t *)")
fn("void snd_seq_port_info_set_name(snd_seq_port_info_t *, const char *)")
fn("void snd_seq_port_info_set_capability(snd_seq_port_info_t *, unsigned int)")
fn("void snd_seq_port_info_set_type(snd_seq_port_info_t *, unsigned int)")
fn("void snd_seq_port_info_set_midi_channels(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_midi_voices(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_synth_voices(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_port_specified(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_timestamping(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_timestamp_real(snd_seq_port_info_t *, int)")
fn("void snd_seq_port_info_set_timestamp_queue(snd_seq_port_info_t *, int)")
fn("int snd_seq_create_port(snd_seq_t *, snd_seq_port_info_t *)")
fn("int snd_seq_delete_port(snd_seq_t *, int)")
fn("int snd_seq_get_port_info(snd_seq_t *, int, snd_seq_port_info_t *)")
fn("int snd_seq_get_any_port_info(snd_seq_t *, int, int, snd_seq_port_info_t *)")
fn("int snd_seq_set_port_info(snd_seq_t *, int, snd_seq_port_info_t *)")
fn("int snd_seq_query_next_port(snd_seq_t *, snd_seq_port_info_t *)")
fn("size_t snd_seq_port_subscribe_sizeof()")
fn("int snd_seq_port_subscribe_malloc(snd_seq_port_subscribe_t **)")
fn("void snd_seq_port_subscribe_free(snd_seq_port_subscribe_t *)")
fn("void snd_seq_port_subscribe_copy(snd_seq_port_subscribe_t *, const snd_seq_port_subscribe_t *)")
fn("const snd_seq_addr_t * snd_seq_port_subscribe_get_sender(const snd_seq_port_subscribe_t *)")
fn("const snd_seq_addr_t * snd_seq_port_subscribe_get_dest(const snd_seq_port_subscribe_t *)")
fn("int snd_seq_port_subscribe_get_queue(const snd_seq_port_subscribe_t *)")
fn("int snd_seq_port_subscribe_get_exclusive(const snd_seq_port_subscribe_t *)")
fn("int snd_seq_port_subscribe_get_time_update(const snd_seq_port_subscribe_t *)")
fn("int snd_seq_port_subscribe_get_time_real(const snd_seq_port_subscribe_t *)")
fn("void snd_seq_port_subscribe_set_sender(snd_seq_port_subscribe_t *, const snd_seq_addr_t *)")
fn("void snd_seq_port_subscribe_set_dest(snd_seq_port_subscribe_t *, const snd_seq_addr_t *)")
fn("void snd_seq_port_subscribe_set_queue(snd_seq_port_subscribe_t *, int)")
fn("void snd_seq_port_subscribe_set_exclusive(snd_seq_port_subscribe_t *, int)")
fn("void snd_seq_port_subscribe_set_time_update(snd_seq_port_subscribe_t *, int)")
fn("void snd_seq_port_subscribe_set_time_real(snd_seq_port_subscribe_t *, int)")
fn("int snd_seq_get_port_subscription(snd_seq_t *, snd_seq_port_subscribe_t *)")
fn("int snd_seq_subscribe_port(snd_seq_t *, snd_seq_port_subscribe_t *)")
fn("int snd_seq_unsubscribe_port(snd_seq_t *, snd_seq_port_subscribe_t *)")
fn("size_t snd_seq_query_subscribe_sizeof()")
fn("int snd_seq_query_subscribe_malloc(snd_seq_query_subscribe_t **)")
fn("void snd_seq_query_subscribe_free(snd_seq_query_subscribe_t *)")
fn("void snd_seq_query_subscribe_copy(snd_seq_query_subscribe_t *, const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_client(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_port(const snd_seq_query_subscribe_t *)")
fn("const snd_seq_addr_t * snd_seq_query_subscribe_get_root(const snd_seq_query_subscribe_t *)")
fn("snd_seq_query_subs_type_t snd_seq_query_subscribe_get_type(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_index(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_num_subs(const snd_seq_query_subscribe_t *)")
fn("const snd_seq_addr_t * snd_seq_query_subscribe_get_addr(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_queue(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_exclusive(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_time_update(const snd_seq_query_subscribe_t *)")
fn("int snd_seq_query_subscribe_get_time_real(const snd_seq_query_subscribe_t *)")
fn("void snd_seq_query_subscribe_set_client(snd_seq_query_subscribe_t *, int)")
fn("void snd_seq_query_subscribe_set_port(snd_seq_query_subscribe_t *, int)")
fn("void snd_seq_query_subscribe_set_root(snd_seq_query_subscribe_t *, const snd_seq_addr_t *)")
fn("void snd_seq_query_subscribe_set_type(snd_seq_query_subscribe_t *, snd_seq_query_subs_type_t)")
fn("void snd_seq_query_subscribe_set_index(snd_seq_query_subscribe_t *, int)")
fn("int snd_seq_query_port_subscribers(snd_seq_t *, snd_seq_query_subscribe_t *)")
fn("size_t snd_seq_queue_info_sizeof()")
fn("int snd_seq_queue_info_malloc(snd_seq_queue_info_t **)")
fn("void snd_seq_queue_info_free(snd_seq_queue_info_t *)")
fn("void snd_seq_queue_info_copy(snd_seq_queue_info_t *, const snd_seq_queue_info_t *)")
fn("int snd_seq_queue_info_get_queue(const snd_seq_queue_info_t *)")
fn("const char * snd_seq_queue_info_get_name(const snd_seq_queue_info_t *)")
fn("int snd_seq_queue_info_get_owner(const snd_seq_queue_info_t *)")
fn("int snd_seq_queue_info_get_locked(const snd_seq_queue_info_t *)")
fn("unsigned int snd_seq_queue_info_get_flags(const snd_seq_queue_info_t *)")
fn("void snd_seq_queue_info_set_name(snd_seq_queue_info_t *, const char *)")
fn("void snd_seq_queue_info_set_owner(snd_seq_queue_info_t *, int)")
fn("void snd_seq_queue_info_set_locked(snd_seq_queue_info_t *, int)")
fn("void snd_seq_queue_info_set_flags(snd_seq_queue_info_t *, unsigned int)")
fn("int snd_seq_create_queue(snd_seq_t *, snd_seq_queue_info_t *)")
fn("int snd_seq_alloc_named_queue(snd_seq_t *, const char *)")
fn("int snd_seq_alloc_queue(snd_seq_t *)")
fn("int snd_seq_free_queue(snd_seq_t *, int)")
fn("int snd_seq_get_queue_info(snd_seq_t *, int, snd_seq_queue_info_t *)")
fn("int snd_seq_set_queue_info(snd_seq_t *, int, snd_seq_queue_info_t *)")
fn("int snd_seq_query_named_queue(snd_seq_t *, const char *)")
fn("int snd_seq_get_queue_usage(snd_seq_t *, int)")
fn("int snd_seq_set_queue_usage(snd_seq_t *, int, int)")
fn("size_t snd_seq_queue_status_sizeof()")
fn("int snd_seq_queue_status_malloc(snd_seq_queue_status_t **)")
fn("void snd_seq_queue_status_free(snd_seq_queue_status_t *)")
fn("void snd_seq_queue_status_copy(snd_seq_queue_status_t *, const snd_seq_queue_status_t *)")
fn("int snd_seq_queue_status_get_queue(const snd_seq_queue_status_t *)")
fn("int snd_seq_queue_status_get_events(const snd_seq_queue_status_t *)")
fn("snd_seq_tick_time_t snd_seq_queue_status_get_tick_time(const snd_seq_queue_status_t *)")
fn("const snd_seq_real_time_t * snd_seq_queue_status_get_real_time(const snd_seq_queue_status_t *)")
fn("unsigned int snd_seq_queue_status_get_status(const snd_seq_queue_status_t *)")
fn("int snd_seq_get_queue_status(snd_seq_t *, int, snd_seq_queue_status_t *)")
fn("size_t snd_seq_queue_tempo_sizeof()")
fn("int snd_seq_queue_tempo_malloc(snd_seq_queue_tempo_t **)")
fn("void snd_seq_queue_tempo_free(snd_seq_queue_tempo_t *)")
fn("void snd_seq_queue_tempo_copy(snd_seq_queue_tempo_t *, const snd_seq_queue_tempo_t *)")
fn("int snd_seq_queue_tempo_get_queue(const snd_seq_queue_tempo_t *)")
fn("unsigned int snd_seq_queue_tempo_get_tempo(const snd_seq_queue_tempo_t *)")
fn("int snd_seq_queue_tempo_get_ppq(const snd_seq_queue_tempo_t *)")
fn("unsigned int snd_seq_queue_tempo_get_skew(const snd_seq_queue_tempo_t *)")
fn("unsigned int snd_seq_queue_tempo_get_skew_base(const snd_seq_queue_tempo_t *)")
fn("void snd_seq_queue_tempo_set_tempo(snd_seq_queue_tempo_t *, unsigned int)")
fn("void snd_seq_queue_tempo_set_ppq(snd_seq_queue_tempo_t *, int)")
fn("void snd_seq_queue_tempo_set_skew(snd_seq_queue_tempo_t *, unsigned int)")
fn("void snd_seq_queue_tempo_set_skew_base(snd_seq_queue_tempo_t *, unsigned int)")
fn("int snd_seq_get_queue_tempo(snd_seq_t *, int, snd_seq_queue_tempo_t *)")
fn("int snd_seq_set_queue_tempo(snd_seq_t *, int, snd_seq_queue_tempo_t *)")
fn("size_t snd_seq_queue_timer_sizeof()")
fn("int snd_seq_queue_timer_malloc(snd_seq_queue_timer_t **)")
fn("void snd_seq_queue_timer_free(snd_seq_queue_timer_t *)")
fn("void snd_seq_queue_timer_copy(snd_seq_queue_timer_t *, const snd_seq_queue_timer_t *)")
fn("int snd_seq_queue_timer_get_queue(const snd_seq_queue_timer_t *)")
fn("snd_seq_queue_timer_type_t snd_seq_queue_timer_get_type(const snd_seq_queue_timer_t *)")
fn("const snd_timer_id_t * snd_seq_queue_timer_get_id(const snd_seq_queue_timer_t *)")
fn("unsigned int snd_seq_queue_timer_get_resolution(const snd_seq_queue_timer_t *)")
fn("void snd_seq_queue_timer_set_type(snd_seq_queue_timer_t *, snd_seq_queue_timer_type_t)")
fn("void snd_seq_queue_timer_set_id(snd_seq_queue_timer_t *, const snd_timer_id_t *)")
fn("void snd_seq_queue_timer_set_resolution(snd_seq_queue_timer_t *, unsigned int)")
fn("int snd_seq_get_queue_timer(snd_seq_t *, int, snd_seq_queue_timer_t *)")
fn("int snd_seq_set_queue_timer(snd_seq_t *, int, snd_seq_queue_timer_t *)")
fn("int snd_seq_free_event(snd_seq_event_t *)")
fn("ssize_t snd_seq_event_length(snd_seq_event_t *)")
fn("int snd_seq_event_output(snd_seq_t *, snd_seq_event_t *)")
fn("int snd_seq_event_output_buffer(snd_seq_t *, snd_seq_event_t *)")
fn("int snd_seq_event_output_direct(snd_seq_t *, snd_seq_event_t *)")
fn("int snd_seq_event_input(snd_seq_t *, snd_seq_event_t **)")
fn("int snd_seq_event_input_pending(snd_seq_t *, int)")
fn("int snd_seq_drain_output(snd_seq_t *)")
fn("int snd_seq_event_output_pending(snd_seq_t *)")
fn("int snd_seq_extract_output(snd_seq_t *, snd_seq_event_t **)")
fn("int snd_seq_drop_output(snd_seq_t *)")
fn("int snd_seq_drop_output_buffer(snd_seq_t *)")
fn("int snd_seq_drop_input(snd_seq_t *)")
fn("int snd_seq_drop_input_buffer(snd_seq_t *)")
fn("size_t snd_seq_remove_events_sizeof()")
fn("int snd_seq_remove_events_malloc(snd_seq_remove_events_t **)")
fn("void snd_seq_remove_events_free(snd_seq_remove_events_t *)")
fn("void snd_seq_remove_events_copy(snd_seq_remove_events_t *, const snd_seq_remove_events_t *)")
fn("unsigned int snd_seq_remove_events_get_condition(const snd_seq_remove_events_t *)")
fn("int snd_seq_remove_events_get_queue(const snd_seq_remove_events_t *)")
fn("const snd_seq_timestamp_t * snd_seq_remove_events_get_time(const snd_seq_remove_events_t *)")
fn("const snd_seq_addr_t * snd_seq_remove_events_get_dest(const snd_seq_remove_events_t *)")
fn("int snd_seq_remove_events_get_channel(const snd_seq_remove_events_t *)")
fn("int snd_seq_remove_events_get_event_type(const snd_seq_remove_events_t *)")
fn("int snd_seq_remove_events_get_tag(const snd_seq_remove_events_t *)")
fn("void snd_seq_remove_events_set_condition(snd_seq_remove_events_t *, unsigned int)")
fn("void snd_seq_remove_events_set_queue(snd_seq_remove_events_t *, int)")
fn("void snd_seq_remove_events_set_time(snd_seq_remove_events_t *, const snd_seq_timestamp_t *)")
fn("void snd_seq_remove_events_set_dest(snd_seq_remove_events_t *, const snd_seq_addr_t *)")
fn("void snd_seq_remove_events_set_channel(snd_seq_remove_events_t *, int)")
fn("void snd_seq_remove_events_set_event_type(snd_seq_remove_events_t *, int)")
fn("void snd_seq_remove_events_set_tag(snd_seq_remove_events_t *, int)")
fn("int snd_seq_remove_events(snd_seq_t *, snd_seq_remove_events_t *)")
fn("void snd_seq_set_bit(int, void *)")
fn("void snd_seq_unset_bit(int, void *)")
fn("int snd_seq_change_bit(int, void *)")
fn("int snd_seq_get_bit(int, void *)")
fn("int snd_seq_control_queue(snd_seq_t *, int, int, int, snd_seq_event_t *)")
fn("int snd_seq_create_simple_port(snd_seq_t *, const char *, unsigned int, unsigned int)")
fn("int snd_seq_delete_simple_port(snd_seq_t *, int)")
fn("int snd_seq_connect_from(snd_seq_t *, int, int, int)")
fn("int snd_seq_connect_to(snd_seq_t *, int, int, int)")
fn("int snd_seq_disconnect_from(snd_seq_t *, int, int, int)")
fn("int snd_seq_disconnect_to(snd_seq_t *, int, int, int)")
fn("int snd_seq_set_client_name(snd_seq_t *, const char *)")
fn("int snd_seq_set_client_event_filter(snd_seq_t *, int)")
fn("int snd_seq_set_client_pool_output(snd_seq_t *, size_t)")
fn("int snd_seq_set_client_pool_output_room(snd_seq_t *, size_t)")
fn("int snd_seq_set_client_pool_input(snd_seq_t *, size_t)")
fn("int snd_seq_sync_output_queue(snd_seq_t *)")
fn("int snd_seq_parse_address(snd_seq_t *, snd_seq_addr_t *, const char *)")
fn("int snd_seq_reset_pool_output(snd_seq_t *)")
fn("int snd_seq_reset_pool_input(snd_seq_t *)")
fn("int snd_midi_event_new(size_t, snd_midi_event_t **)")
fn("int snd_midi_event_resize_buffer(snd_midi_event_t *, size_t)")
fn("void snd_midi_event_free(snd_midi_event_t *)")
fn("void snd_midi_event_init(snd_midi_event_t *)")
fn("void snd_midi_event_reset_encode(snd_midi_event_t *)")
fn("void snd_midi_event_reset_decode(snd_midi_event_t *)")
fn("void snd_midi_event_no_status(snd_midi_event_t *, int)")
fn("long snd_midi_event_encode(snd_midi_event_t *, const unsigned char *, long, snd_seq_event_t *)")
fn("int snd_midi_event_encode_byte(snd_midi_event_t *, int, snd_seq_event_t *)")
fn("long snd_midi_event_decode(snd_midi_event_t *, unsigned char *, long, const snd_seq_event_t *)")
Generate()
