#!/usr/bin/python3
from ThunkHelpers import *

lib("libXfixes")

fn("const char* XFixesGetCursorName(Display*, Cursor, Atom*)")
fn("int XFixesQueryExtension(Display*, int*, int*)")
fn("int XFixesQueryVersion(Display*, int*, int*)")
fn("int XFixesVersion()")
fn("PointerBarrier XFixesCreatePointerBarrier(Display*, Window, int, int, int, int, int, int, int*)")
fn("void XFixesChangeCursorByName(Display*, Cursor, const char*)")
fn("void XFixesChangeCursor(Display*, Cursor, Cursor)")
fn("void XFixesChangeSaveSet(Display*, Window, int, int, int)")
fn("void XFixesCopyRegion(Display*, XserverRegion, XserverRegion)")
fn("void XFixesDestroyPointerBarrier(Display*, PointerBarrier)")
fn("void XFixesDestroyRegion(Display*, XserverRegion)")
fn("void XFixesExpandRegion(Display*, XserverRegion, XserverRegion, unsigned int, unsigned int, unsigned int, unsigned int)")
fn("void XFixesHideCursor(Display*, Window)")
fn("void XFixesIntersectRegion(Display*, XserverRegion, XserverRegion, XserverRegion)")
fn("void XFixesInvertRegion(Display*, XserverRegion, XRectangle*, XserverRegion)")
fn("void XFixesRegionExtents(Display*, XserverRegion, XserverRegion)")
fn("void XFixesSelectCursorInput(Display*, Window, long unsigned int)")
fn("void XFixesSelectSelectionInput(Display*, Window, Atom, long unsigned int)")
fn("void XFixesSetCursorName(Display*, Cursor, const char*)")
fn("void XFixesSetGCClipRegion(Display*, GC, int, int, XserverRegion)")
fn("void XFixesSetPictureClipRegion(Display*, XID, int, int, XserverRegion)")
fn("void XFixesSetRegion(Display*, XserverRegion, XRectangle*, int)")
fn("void XFixesSetWindowShapeRegion(Display*, Window, int, int, int, XserverRegion)")
fn("void XFixesShowCursor(Display*, Window)")
fn("void XFixesSubtractRegion(Display*, XserverRegion, XserverRegion, XserverRegion)")
fn("void XFixesTranslateRegion(Display*, XserverRegion, int, int)")
fn("void XFixesUnionRegion(Display*, XserverRegion, XserverRegion, XserverRegion)")
fn("XFixesCursorImage* XFixesGetCursorImage(Display*)")
fn("XRectangle* XFixesFetchRegionAndBounds(Display*, XserverRegion, int*, XRectangle*)")
fn("XRectangle* XFixesFetchRegion(Display*, XserverRegion, int*)")
fn("XserverRegion XFixesCreateRegion(Display*, XRectangle*, int)")
fn("XserverRegion XFixesCreateRegionFromBitmap(Display*, Pixmap)")
fn("XserverRegion XFixesCreateRegionFromGC(Display*, GC)")
fn("XserverRegion XFixesCreateRegionFromPicture(Display*, XID)")
fn("XserverRegion XFixesCreateRegionFromWindow(Display*, Window, int)")


Generate()