#!/usr/bin/python3
from ThunkHelpers import *

lib("libXext")

# needs function pointer
# fn("int (* XSetExtensionErrorHandler(XextErrorHandler))(Display*, const char*, const char*)")

fn("int DPMSCapable(Display*)")
fn("int DPMSDisable(Display*)")
fn("int DPMSEnable(Display*)")
fn("int DPMSForceLevel(Display*, CARD16)")
fn("int DPMSGetTimeouts(Display*, CARD16*, CARD16*, CARD16*)")
fn("int DPMSGetVersion(Display*, int*, int*)")
fn("int DPMSInfo(Display*, CARD16*, BOOL*)")
fn("int DPMSQueryExtension(Display*, int*, int*)")
fn("int DPMSSetTimeouts(Display*, CARD16, CARD16, CARD16)")
fn("int XeviGetVisualInfo(Display*, VisualID*, int, ExtendedVisualInfo**, int*)")
fn("int XeviQueryExtension(Display*)")
fn("int XeviQueryVersion(Display*, int*, int*)")
fn("int XGEQueryExtension(Display*, int*, int*)")
fn("int XGEQueryVersion(Display*, int*, int*)")
fn("int XLbxGetEventBase(Display*)")
fn("int XLbxQueryExtension(Display*, int*, int*, int*)")
fn("int XLbxQueryVersion(Display*, int*, int*)")
fn("int XmbufCreateBuffers(Display*, Window, int, int, int, Multibuffer*)")
fn("int XmbufGetBufferAttributes(Display*, Multibuffer, XmbufBufferAttributes*)")
fn("int XmbufGetScreenInfo(Display*, Drawable, int*, XmbufBufferInfo**, int*, XmbufBufferInfo**)")
fn("int XmbufGetVersion(Display*, int*, int*)")
fn("int XmbufGetWindowAttributes(Display*, Window, XmbufWindowAttributes*)")
fn("int XmbufQueryExtension(Display*, int*, int*)")
fn("int XMissingExtension(Display*, const char*)")
fn("int XMITMiscGetBugMode(Display*)")
fn("int XMITMiscQueryExtension(Display*, int*, int*)")
fn("int XMITMiscSetBugMode(Display*, int)")
fn("int XSecurityQueryExtension(Display*, int*, int*)")
fn("int XSecurityRevokeAuthorization(Display*, XSecurityAuthorization)")
fn("int XShapeQueryExtension(Display*, int*, int*)")
fn("int XShapeQueryExtents(Display*, Window, int*, int*, int*, unsigned int*, unsigned int*, int*, int*, int*, unsigned int*, unsigned int*)")
fn("int XShapeQueryVersion(Display*, int*, int*)")
fn("int XShmAttach(Display*, XShmSegmentInfo*)")
fn("int XShmDetach(Display*, XShmSegmentInfo*)")
fn("int XShmGetEventBase(Display*)")
fn("int XShmGetImage(Display*, Drawable, XImage*, int, int, long unsigned int)")
fn("int XShmPixmapFormat(Display*)")
fn("int XShmPutImage(Display*, Drawable, GC, XImage*, int, int, int, int, unsigned int, unsigned int, int)")
fn("int XShmQueryExtension(Display*)")
fn("int XShmQueryVersion(Display*, int*, int*, int*)")
fn("int XSyncAwait(Display*, XSyncWaitCondition*, int)")
fn("int XSyncAwaitFence(Display*, const XSyncFence*, int)")
fn("int XSyncChangeAlarm(Display*, XSyncAlarm, long unsigned int, XSyncAlarmAttributes*)")
fn("int XSyncChangeCounter(Display*, XSyncCounter, XSyncValue)")
fn("int XSyncDestroyAlarm(Display*, XSyncAlarm)")
fn("int XSyncDestroyCounter(Display*, XSyncCounter)")
fn("int XSyncDestroyFence(Display*, XSyncFence)")
fn("int XSyncGetPriority(Display*, XID, int*)")
fn("int XSyncInitialize(Display*, int*, int*)")
fn("int XSyncQueryAlarm(Display*, XSyncAlarm, XSyncAlarmAttributes*)")
fn("int XSyncQueryCounter(Display*, XSyncCounter, XSyncValue*)")
fn("int XSyncQueryExtension(Display*, int*, int*)")
fn("int XSyncQueryFence(Display*, XSyncFence, int*)")
fn("int XSyncResetFence(Display*, XSyncFence)")
fn("int XSyncSetCounter(Display*, XSyncCounter, XSyncValue)")
fn("int XSyncSetPriority(Display*, XID, int)")
fn("int XSyncTriggerFence(Display*, XSyncFence)")
fn("int XSyncValueEqual(XSyncValue, XSyncValue)")
fn("int XSyncValueGreaterOrEqual(XSyncValue, XSyncValue)")
fn("int XSyncValueGreaterThan(XSyncValue, XSyncValue)")
fn("int XSyncValueHigh32(XSyncValue)")
fn("int XSyncValueIsNegative(XSyncValue)")
fn("int XSyncValueIsPositive(XSyncValue)")
fn("int XSyncValueIsZero(XSyncValue)")
fn("int XSyncValueLessOrEqual(XSyncValue, XSyncValue)")
fn("int XSyncValueLessThan(XSyncValue, XSyncValue)")
fn("long unsigned int XShapeInputSelected(Display*, Window)")
fn("Pixmap XShmCreatePixmap(Display*, Drawable, char*, XShmSegmentInfo*, unsigned int, unsigned int, unsigned int)")
fn("unsigned int XSyncValueLow32(XSyncValue)")
fn("void XmbufChangeBufferAttributes(Display*, Multibuffer, long unsigned int, XmbufSetBufferAttributes*)")
fn("void XmbufChangeWindowAttributes(Display*, Window, long unsigned int, XmbufSetWindowAttributes*)")
fn("void XmbufClearBufferArea(Display*, Multibuffer, int, int, unsigned int, unsigned int, int)")
fn("void XmbufDestroyBuffers(Display*, Window)")
fn("void XmbufDisplayBuffers(Display*, int, Multibuffer*, int, int)")
fn("void XSecurityFreeXauth(Xauth*)")
fn("void XShapeCombineMask(Display*, Window, int, int, int, Pixmap, int)")
fn("void XShapeCombineRectangles(Display*, Window, int, int, int, XRectangle*, int, int, int)")
fn("void XShapeCombineRegion(Display*, Window, int, int, int, Region, int)")
fn("void XShapeCombineShape(Display*, Window, int, int, int, Window, int, int)")
fn("void XShapeOffsetShape(Display*, Window, int, int, int)")
fn("void XShapeSelectInput(Display*, Window, long unsigned int)")
fn("void XSyncFreeSystemCounterList(XSyncSystemCounter*)")
fn("void XSyncIntsToValue(XSyncValue*, unsigned int, int)")
fn("void XSyncIntToValue(XSyncValue*, int)")
fn("void XSyncMaxValue(XSyncValue*)")
fn("void XSyncMinValue(XSyncValue*)")
fn("void XSyncValueAdd(XSyncValue*, XSyncValue, XSyncValue, int*)")
fn("void XSyncValueSubtract(XSyncValue*, XSyncValue, XSyncValue, int*)")
fn("Window XmbufCreateStereoWindow(Display*, Window, int, int, unsigned int, unsigned int, unsigned int, int, unsigned int, Visual*, long unsigned int, XSetWindowAttributes*, Multibuffer*, Multibuffer*)")
fn("Xauth* XSecurityAllocXauth()")
fn("Xauth* XSecurityGenerateAuthorization(Display*, Xauth*, long unsigned int, XSecurityAuthorizationAttributes*, XSecurityAuthorization*)")
fn("XImage* XShmCreateImage(Display*, Visual*, unsigned int, int, char*, XShmSegmentInfo*, unsigned int, unsigned int)")
fn("XRectangle* XShapeGetRectangles(Display*, Window, int, int*, int*)")
fn("XSyncAlarm XSyncCreateAlarm(Display*, long unsigned int, XSyncAlarmAttributes*)")
fn("XSyncCounter XSyncCreateCounter(Display*, XSyncValue)")
fn("XSyncFence XSyncCreateFence(Display*, Drawable, int)")
fn("XSyncSystemCounter* XSyncListSystemCounters(Display*, int*)")



Generate()