#!/usr/bin/python3
from ThunkHelpers import *

lib("libXrender")

fn("Cursor XRenderCreateAnimCursor(Display*, int, XAnimCursor*)")
fn("Cursor XRenderCreateCursor(Display*, Picture, unsigned int, unsigned int)")
fn("GlyphSet XRenderCreateGlyphSet(Display*, const XRenderPictFormat*)")
fn("GlyphSet XRenderReferenceGlyphSet(Display*, GlyphSet)")
fn("int XRenderParseColor(Display*, char*, XRenderColor*)")
fn("int XRenderQueryExtension(Display*, int*, int*)")
fn("int XRenderQueryFormats(Display*)")
fn("int XRenderQuerySubpixelOrder(Display*, int)")
fn("int XRenderQueryVersion(Display*, int*, int*)")
fn("int XRenderSetSubpixelOrder(Display*, int, int)")
fn("Picture XRenderCreateConicalGradient(Display*, const XConicalGradient*, const XFixed*, const XRenderColor*, int)")
fn("Picture XRenderCreateLinearGradient(Display*, const XLinearGradient*, const XFixed*, const XRenderColor*, int)")
fn("Picture XRenderCreatePicture(Display*, Drawable, const XRenderPictFormat*, long unsigned int, const XRenderPictureAttributes*)")
fn("Picture XRenderCreateRadialGradient(Display*, const XRadialGradient*, const XFixed*, const XRenderColor*, int)")
fn("Picture XRenderCreateSolidFill(Display*, const XRenderColor*)")
fn("void XRenderAddGlyphs(Display*, GlyphSet, const Glyph*, const XGlyphInfo*, int, const char*, int)")
fn("void XRenderAddTraps(Display*, Picture, int, int, const XTrap*, int)")
fn("void XRenderChangePicture(Display*, Picture, long unsigned int, const XRenderPictureAttributes*)")
fn("void XRenderComposite(Display*, int, Picture, Picture, Picture, int, int, int, int, int, int, unsigned int, unsigned int)")
fn("void XRenderCompositeDoublePoly(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, int, int, const XPointDouble*, int, int)")
fn("void XRenderCompositeString16(Display*, int, Picture, Picture, const XRenderPictFormat*, GlyphSet, int, int, int, int, const short unsigned int*, int)")
fn("void XRenderCompositeString32(Display*, int, Picture, Picture, const XRenderPictFormat*, GlyphSet, int, int, int, int, const unsigned int*, int)")
fn("void XRenderCompositeString8(Display*, int, Picture, Picture, const XRenderPictFormat*, GlyphSet, int, int, int, int, const char*, int)")
fn("void XRenderCompositeText16(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, int, int, const XGlyphElt16*, int)")
fn("void XRenderCompositeText32(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, int, int, const XGlyphElt32*, int)")
fn("void XRenderCompositeText8(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, int, int, const XGlyphElt8*, int)")
fn("void XRenderCompositeTrapezoids(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, const XTrapezoid*, int)")
fn("void XRenderCompositeTriangles(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, const XTriangle*, int)")
fn("void XRenderCompositeTriFan(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, const XPointFixed*, int)")
fn("void XRenderCompositeTriStrip(Display*, int, Picture, Picture, const XRenderPictFormat*, int, int, const XPointFixed*, int)")
fn("void XRenderFillRectangle(Display*, int, Picture, const XRenderColor*, int, int, unsigned int, unsigned int)")
fn("void XRenderFillRectangles(Display*, int, Picture, const XRenderColor*, const XRectangle*, int)")
fn("void XRenderFreeGlyphs(Display*, GlyphSet, const Glyph*, int)")
fn("void XRenderFreeGlyphSet(Display*, GlyphSet)")
fn("void XRenderFreePicture(Display*, Picture)")
fn("void XRenderSetPictureClipRectangles(Display*, Picture, int, int, const XRectangle*, int)")
fn("void XRenderSetPictureClipRegion(Display*, Picture, Region)")
fn("void XRenderSetPictureFilter(Display*, Picture, const char*, XFixed*, int)")
fn("void XRenderSetPictureTransform(Display*, Picture, XTransform*)")
fn("XFilters* XRenderQueryFilters(Display*, Drawable)")
fn("XIndexValue* XRenderQueryPictIndexValues(Display*, const XRenderPictFormat*, int*)")
fn("XRenderPictFormat* XRenderFindFormat(Display*, long unsigned int, const XRenderPictFormat*, int)")
fn("XRenderPictFormat* XRenderFindStandardFormat(Display*, int)")
fn("XRenderPictFormat* XRenderFindVisualFormat(Display*, const Visual*)")


Generate()