#!/usr/bin/python3
from ThunkHelpers import *

lib("libX11")

# will have to peek on the source for these
# function("_XAllocScratch");
# function("_XAllocTemp");
# function("_XDeqAsyncHandler");
# function("_XEatData");
# function("_XEatDataWords");
# function("_XFlushGCCache");
# function("_XFlushIt");
# function("_XFreeTemp");
# function("_XGetAsyncReply");
# function("_XGetBitsPerPixel");
# function("_XGetRequest");
# function("_XGetScanlinePad");
# function("_Xglobal_lock");
# function("_Xglobal_lock_p");
# function("_XInitImageFuncPtrs");
# function("_XIOError");
# function("_XLockMutex_fn");
# function("_XLockMutex_fn_p");
# function("_XRead");
# function("_XReadPad");
# function("_XReply");
# function("_XSend");
# function("_XSetLastRequestRead");
# function("_Xsetlocale");
# function("_Xthread_init");
# function("_Xthread_waiter");
# function("_XUnlockMutex_fn");
# function("_XUnlockMutex_fn_p");
# function("_XVIDtoVisual");

# VArgs support needs manual work
# fn("char* XSetICValues(XIC, ...)") # TODO VARGS
# fn("void* XVaCreateNestedList(int, ...)") # TODO VARGS
# fn("char* XGetIMValues(XIM, ...)") # TODO VARGS
# fn("void* XVaCreateNestedList(int, ...)")
# fn("_XOC* XCreateOC(XOM, ...)")
# fn("char* XGetIMValues(XIM, ...)")
# fn("char* XGetOCValues(XOC, ...)")
# fn("char* XGetOMValues(XOM, ...)")
# fn("char* XSetICValues(XIC, ...)")
# fn("char* XSetIMValues(XIM, ...)")
# fn("char* XSetOCValues(XOC, ...)")
# fn("char* XSetOMValues(XOM, ...)")

# Needs function pointer
# fn("int XCheckIfEvent(Display*, XEvent*, int (*)(Display*, XEvent*, XPointer), XPointer)")
# fn("int XPeekIfEvent(Display*, XEvent*, int (*)(Display*, XEvent*, XPointer), XPointer)")
# fn("int (* XSetIOErrorHandler(XIOErrorHandler))(Display*)")
# fn("int (* XSynchronize(Display*, int))(Display*)")
# fn("int XrmEnumerateDatabase(XrmDatabase, XrmNameList, XrmClassList, int, int (*)(_XrmHashBucketRec**, XrmBindingList, XrmQuarkList, XrmRepresentation*, XrmValue*, XPointer), XPointer)")
# fn("int (* XESetCloseDisplay(Display*, int, int (*)()))()")
# fn("int XrmEnumerateDatabase(XrmDatabase, XrmNameList, XrmClassList, int, int (*)(_XrmHashBucketRec**, XrmBindingList, XrmQuarkList, XrmRepresentation*, XrmValue*, XPointer), XPointer)")
# fn("int (* XSetAfterFunction(Display*, int (*)(Display*)))(Display*)")

# symbols from objdump -T
#function("_XEatData")
#function("_XEatDataWords")
#function("XAllocColorCells")
#function("XAllowEvents")
#function("XAllocColorPlanes")
#function("XAutoRepeatOn")
#function("XAutoRepeatOff")
#function("XSetWindowBackground")
#function("XSetWindowBorderWidth")
#function("XBell")
#function("XSetWindowBorder")
#function("XSetAccessControl")
#function("XEnableAccessControl")
#function("XDisableAccessControl")
#function("XChangeActivePointerGrab")
#function("XSetCloseDownMode")
#function("XSetWindowColormap")
#function("XChangeGC")
#function("XChangeKeyboardControl")
#function("XCheckMaskEvent")
#function("XCheckTypedEvent")
#function("XCheckTypedWindowEvent")
#function("XCheckWindowEvent")
#function("XChangePointerControl")
#function("XChangeProperty")
#function("XChangeSaveSet")
#function("XAddToSaveSet")
#function("XRemoveFromSaveSet")
#function("XChangeWindowAttributes")
#function("XResizeWindow")
#function("XCirculateSubwindows")
#function("XCirculateSubwindowsDown")
#function("XCirculateSubwindowsUp")
#function("XCloseDisplay")
#function("XClearArea")
#function("XClearWindow")
#function("XMoveResizeWindow")
#function("XSaveContext")
#function("XFindContext")
#function("XDeleteContext")
#function("XConvertSelection")
#function("XCopyArea")
#function("XCopyColormapAndFree")
#function("XCopyGC")
#function("XCopyPlane")
#function("XCreateBitmapFromData")
#function("XCreateColormap")
#function("XCreatePixmapCursor")
#function("_XUpdateGCCache")
#function("XCreateGC")
#function("_XFlushGCCache")
#function("XFlushGC")
#function("XGContextFromGC")
#function("_XNoticeCreateBitmap")
#function("_XNoticePutBitmap")
#function("_XTryShapeBitmapCursor")
#function("XCreateGlyphCursor")
#function("XCreatePixmapFromBitmapData")
#function("XCreatePixmap")
#function("XCreateSimpleWindow")
#function("XCreateFontCursor")
#function("XDefineCursor")
#function("XDeleteProperty")
#function("XListDepths")
#function("XDestroySubwindows")
#function("XDestroyWindow")
#function("XDisplayName")
#function("XDrawArc")
#function("XDrawArcs")
#function("XDrawLine")
#function("XDrawLines")
#function("XDrawPoint")
#function("XDrawPoints")
#function("XDrawRectangle")
#function("XDrawRectangles")
#function("XDrawSegments")
#function("XGetErrorDatabaseText")
#function("XGetErrorText")
#function("XSetErrorHandler")
#function("_XEventToWire")
#function("XFetchName")
#function("XGetIconName")
#function("XFillArc")
#function("XFillArcs")
#function("XFillPolygon")
#function("XFillRectangle")
#function("XFillRectangles")
#function("XFilterEvent")
#function("XFlush")
#function("XQueryFont")
#function("_XF86BigfontFreeFontMetrics")
#function("XFreeFont")
#function("_XF86LoadQueryLocaleFont")
#function("XLoadQueryFont")
#function("XListFontsWithInfo")
#function("XFreeFontInfo")
#function("XListFonts")
#function("XFreeFontNames")
#function("XFreeColormap")
#function("XFreeColors")
#function("XFreeCursor")
#function("_XFreeExtData")
#function("XFreeEventData")
#function("XFreeGC")
#function("XFreePixmap")
#function("XForceScreenSaver")
#function("XActivateScreenSaver")
#function("XResetScreenSaver")
#function("_XParseBaseFontNameList")
#function("XCreateFontSet")
#function("XFontsOfFontSet")
#function("XBaseFontNameListOfFontSet")
#function("XLocaleOfFontSet")
#function("XContextDependentDrawing")
#function("XDirectionalDependentDrawing")
#function("XContextualDrawing")
#function("XExtentsOfFontSet")
#function("XFreeFontSet")
#function("XSetArcMode")
#function("XSetFillRule")
#function("XSetFillStyle")
#function("XSetGraphicsExposures")
#function("XSetSubwindowMode")
#function("XGeometry")
#function("XGetAtomName")
#function("XGetAtomNames")
#function("XAllocNamedColor")
#function("XGetDefault")
#function("XGetEventData")
#function("XGetFontPath")
#function("XFreeFontPath")
#function("XGetFontProperty")
#function("XGetGCValues")
#function("XGetGeometry")
#function("XAllocColor")
#function("XGetSizeHints")
#function("XGetWMHints")
#function("XGetZoomHints")
#function("XGetNormalHints")
#function("XGetIconSizes")
#function("XGetCommand")
#function("XGetTransientForHint")
#function("XGetClassHint")
#function("XGetInputFocus")
#function("XGetImage")
#function("XGetSubImage")
#function("XGetKeyboardControl")
#function("XGetMotionEvents")
#function("XGetWMSizeHints")
#function("XGetWMNormalHints")
#function("XGetPointerControl")
#function("XGetPointerMapping")
#function("XGetKeyboardMapping")
#function("XGetWindowProperty")
#function("XGetRGBColormaps")
#function("XGetSelectionOwner")
#function("XGetScreenSaver")
#function("XGetStandardColormap")
#function("XGetTextProperty")
#function("XGetWMName")
#function("XGetWMIconName")
#function("XGetWMClientMachine")
#function("_XGetWindowAttributes")
#function("XGetWindowAttributes")
#function("XGetWMColormapWindows")
#function("XGetWMProtocols")
#function("XGrabButton")
#function("XGrabKeyboard")
#function("XGrabKey")
#function("XGrabPointer")
#function("XGrabServer")
#function("XAddHost")
#function("XRemoveHost")
#function("XAddHosts")
#function("XRemoveHosts")
#function("XIconifyWindow")
#function("XIfEvent")
#function("_XimGetLocaleCode")
#function("_XimGetCharCode")
#function("_XimLookupMBText")
#function("_XimLookupWCText")
#function("_XimLookupUTF8Text")
#function("XDrawImageString16")
#function("XDrawImageString")
#function("_XGetScanlinePad")
#function("_XGetBitsPerPixel")
#function("_XInitImageFuncPtrs")
#function("XCreateImage")
#function("XInitImage")
#function("_XSetImage")
#function("XInitExtension")
#function("XAddExtension")
#function("XEHeadOfExtensionList")
#function("XAddToExtensionList")
#function("XFindOnExtensionList")
#function("XESetCreateGC")
#function("XESetCopyGC")
#function("XESetFlushGC")
#function("XESetFreeGC")
#function("XESetCreateFont")
#function("XESetFreeFont")
#function("XESetWireToEvent")
#function("XESetWireToEventCookie")
#function("XESetCopyEventCookie")
#function("XESetEventToWire")
#function("XESetWireToError")
#function("XESetError")
#function("XESetErrorString")
#function("XESetPrintErrorValues")
#function("XESetBeforeFlush")
#function("XInstallColormap")
#function("_XFreeAtomTable")
#function("_XUpdateAtomCache")
#function("XInternAtom")
#function("XInternAtoms")
#function("XConvertCase")
#function("_XRefreshKeyboardMapping")
#function("_XKeyInitialize")
#function("_XKeycodeToKeysym")
#function("_XKeysymToKeycode")
#function("_XLookupKeysym")
#function("_XTranslateKey")
#function("_XTranslateKeySym")
#function("_XLookupString")
#function("XRebindKeysym")
#function("_XKeysymToModifiers")
#function("XKeysymToString")
#function("XKillClient")
#function("XListHosts")
#function("XListInstalledColormaps")
#function("XListExtensions")
#function("XFreeExtensionList")
#function("XLoadFont")
#function("XLockDisplay")
#function("XUnlockDisplay")
#function("XInitThreads")
#function("XLookupColor")
#function("XLowerWindow")
#function("XConnectionNumber")
#function("XRootWindow")
#function("XDefaultScreen")
#function("XDefaultRootWindow")
#function("XDefaultVisual")
#function("XDefaultGC")
#function("XBlackPixel")
#function("XWhitePixel")
#function("XAllPlanes")
#function("XQLength")
#function("XDisplayWidth")
#function("XDisplayHeight")
#function("XDisplayWidthMM")
#function("XDisplayHeightMM")
#function("XDisplayPlanes")
#function("XDisplayCells")
#function("XScreenCount")
#function("XServerVendor")
#function("XProtocolVersion")
#function("XProtocolRevision")
#function("XVendorRelease")
#function("XDisplayString")
#function("XDefaultDepth")
#function("XDefaultColormap")
#function("XBitmapUnit")
#function("XBitmapBitOrder")
#function("XBitmapPad")
#function("XImageByteOrder")
#function("XNextRequest")
#function("XLastKnownRequestProcessed")
#function("XScreenOfDisplay")
#function("XDefaultScreenOfDisplay")
#function("XDisplayOfScreen")
#function("XRootWindowOfScreen")
#function("XBlackPixelOfScreen")
#function("XWhitePixelOfScreen")
#function("XDefaultColormapOfScreen")
#function("XDefaultDepthOfScreen")
#function("XDefaultGCOfScreen")
#function("XDefaultVisualOfScreen")
#function("XWidthOfScreen")
#function("XHeightOfScreen")
#function("XWidthMMOfScreen")
#function("XHeightMMOfScreen")
#function("XPlanesOfScreen")
#function("XCellsOfScreen")
#function("XMinCmapsOfScreen")
#function("XMaxCmapsOfScreen")
#function("XDoesSaveUnders")
#function("XDoesBackingStore")
#function("XEventMaskOfScreen")
#function("XScreenNumberOfScreen")
##function("XDestroyImage")
##function("XGetPixel")
##function("XPutPixel")
##function("XSubImage")
##function("XAddPixel")
#function("XNoOp")
#function("XMapRaised")
#function("XMapSubwindows")
#function("XMapWindow")
#function("XMaskEvent")
#function("XMaxRequestSize")
#function("XResourceManagerString")
#function("XDisplayMotionBufferSize")
#function("XDisplayKeycodes")
#function("XVisualIDFromVisual")
#function("XExtendedMaxRequestSize")
#function("XGetModifierMapping")
#function("XSetModifierMapping")
#function("XNewModifiermap")
#function("XFreeModifiermap")
#function("XInsertModifiermapEntry")
#function("XDeleteModifiermapEntry")
#function("XMoveWindow")
#function("XNextEvent")
## function("XCreateOC")
#function("XDestroyOC")
#function("XOMOfOC")
## function("XSetOCValues")
## function("XGetOCValues")
#function("XOpenOM")
#function("XCloseOM")
## function("XSetOMValues")
## function("XGetOMValues")
#function("XDisplayOfOM")
#function("XLocaleOfOM")
#function("_XFreeDisplayStructure")
#function("XOpenDisplay")
#function("XrmParseCommand")
#function("XParseColor")
#function("XParseGeometry")
#function("XPeekEvent")
## function("XPeekIfEvent")
#function("XEventsQueued")
#function("XPending")
#function("XListPixmapFormats")
#function("XSetWindowBackgroundPixmap")
#function("XSetWindowBorderPixmap")
#function("XPolygonRegion")
#function("XDrawText16")
#function("XDrawText")
#function("XAllocSizeHints")
#function("XAllocStandardColormap")
#function("XAllocWMHints")
#function("XAllocClassHint")
#function("XAllocIconSize")
#function("_XPutBackEvent")
#function("XPutBackEvent")
#function("_XReverse_Bytes")
#function("XPutImage")
#function("Xpermalloc")
#function("_XrmInternalStringToQuark")
#function("XrmStringToQuark")
#function("XrmPermStringToQuark")
#function("XrmUniqueQuark")
#function("XrmQuarkToString")
#function("XQueryBestSize")
#function("XQueryColor")
#function("XQueryColors")
#function("XQueryBestCursor")
#function("XQueryExtension")
#function("XQueryKeymap")
#function("XQueryPointer")
#function("XQueryBestStipple")
#function("XQueryTextExtents16")
#function("XQueryTextExtents")
#function("XQueryBestTile")
#function("XQueryTree")
#function("XRaiseWindow")
#function("XReadBitmapFileData")
#function("XReadBitmapFile")
#function("XRecolorCursor")
#function("XConfigureWindow")
#function("XReconfigureWMWindow")
#function("XCreateRegion")
#function("XClipBox")
#function("XSetRegion")
#function("XDestroyRegion")
#function("XOffsetRegion")
#function("XIntersectRegion")
#function("XUnionRegion")
#function("XUnionRectWithRegion")
#function("XShrinkRegion")
#function("XSubtractRegion")
#function("XXorRegion")
#function("XEmptyRegion")
#function("XEqualRegion")
#function("XPointInRegion")
#function("XRectInRegion")
#function("_XRegisterFilterByMask")
#function("_XRegisterFilterByType")
#function("_XUnregisterFilter")
#function("XReparentWindow")
#function("XRestackWindows")
#function("XRotateWindowProperties")
#function("XScreenResourceString")
#function("XSelectInput")
#function("XSendEvent")
#function("XSetBackground")
#function("XSetClipMask")
#function("XSetClipOrigin")
#function("_XSetClipRectangles")
#function("XSetClipRectangles")
#function("XSetDashes")
#function("XSetFont")
#function("XSetForeground")
#function("XSetFontPath")
#function("XSetFunction")
#function("XSetSizeHints")
#function("XSetWMHints")
#function("XSetZoomHints")
#function("XSetNormalHints")
#function("XSetIconSizes")
#function("XSetCommand")
#function("XSetStandardProperties")
#function("XSetTransientForHint")
#function("XSetClassHint")
#function("XSetInputFocus")
#function("_XlcMapOSLocaleName")
#function("XSetLineAttributes")
#function("XSetWMSizeHints")
#function("XSetWMNormalHints")
#function("XSetPlaneMask")
#function("XSetPointerMapping")
#function("XChangeKeyboardMapping")
#function("XSetRGBColormaps")
#function("XSetSelectionOwner")
#function("XSetScreenSaver")
#function("XSetState")
#function("XSetStandardColormap")
#function("XSetStipple")
#function("XSetTile")
#function("XSetTSOrigin")
#function("XSetTextProperty")
#function("XSetWMName")
#function("XSetWMIconName")
#function("XSetWMClientMachine")
#function("XSetWMColormapWindows")
#function("XSetWMProtocols")
#function("XRotateBuffers")
#function("XFetchBuffer")
#function("XFetchBytes")
#function("XStoreBuffer")
#function("XStoreBytes")
#function("XStoreColor")
#function("XStoreColors")
#function("XStoreName")
#function("XSetIconName")
#function("XStoreNamedColor")
#function("_XInitKeysymDB")
#function("XStringToKeysym")
#function("XStringListToTextProperty")
#function("XSync")
## function("XSynchronize")
## function("XSetAfterFunction")
#function("XDrawString16")
#function("XDrawString")
#function("XTextExtents16")
#function("XTextWidth16")
#function("_XTextHeight16")
#function("XTextExtents")
#function("XTextWidth")
#function("_XTextHeight")
#function("XTextPropertyToStringList")
#function("XFreeStringList")
#function("XTranslateCoordinates")
#function("XUndefineCursor")
#function("XUngrabButton")
#function("XUngrabKeyboard")
#function("XUngrabKey")
#function("XUngrabPointer")
#function("XUngrabServer")
#function("XUninstallColormap")
#function("XUnloadFont")
#function("XUnmapSubwindows")
#function("XUnmapWindow")
#function("XGetVisualInfo")
#function("XMatchVisualInfo")
#function("XWarpPointer")
#function("_XProcessWindowAttributes")
#function("XCreateWindow")
#function("XWindowEvent")
#function("XWithdrawWindow")
#function("XWMGeometry")
#function("XSetWMProperties")
#function("XWriteBitmapFile")
#function("XSetAuthorization")
#function("_XConnectXCB")
#function("_XFreeX11XCBStructure")
#function("_XSend")
#function("_XEventsQueued")
#function("_XReadEvents")
#function("_XFlush")
#function("_XAllocID")
#function("_XAllocIDs")
#function("_XReply")
#function("_XRead")
#function("_XReadPad")
#function("_XAsyncErrorHandler")
#function("_XDeqAsyncHandler")
#function("_XGetAsyncReply")
#function("_XGetAsyncData")
#function("_XPollfdCacheInit")
#function("_XPollfdCacheAdd")
#function("_XPollfdCacheDel")
#function("_XRead32")
#function("_XSetLastRequestRead")
#function("_XRegisterInternalConnection")
#function("_XUnregisterInternalConnection")
#function("XInternalConnectionNumbers")
#function("_XProcessInternalConnection")
#function("XProcessInternalConnection")
#function("XAddConnectionWatch")
#function("XRemoveConnectionWatch")
#function("_XIsEventCookie")
#function("_XFetchEventCookie")
#function("_XCopyEventCookie")
#function("_XDeq")
#function("_XUnknownWireEvent")
#function("_XUnknownWireEventCookie")
#function("_XUnknownCopyEventCookie")
#function("_XUnknownNativeEvent")
#function("_XWireToEvent")
#function("_XDefaultIOError")
#function("_XDefaultError")
#function("_XDefaultWireError")
#function("_XError")
#function("_XIOError")
#function("_XStoreEventCookie")
#function("_XEnq")
#function("_XAllocScratch")
#function("_XAllocTemp")
#function("_XFreeTemp")
#function("_XVIDtoVisual")
#function("XFree")
#function("_XFreeEventCookies")
#function("_XData32")
#function("_XGetHostname")
#function("_XScreenOfWindow")
#function("_XGetRequest")
#function("XrmInitialize")
#function("XrmGetDatabase")
#function("XrmStringToQuarkList")
#function("XrmStringToBindingQuarkList")
#function("XrmCombineDatabase")
#function("XrmMergeDatabases")
#function("XrmQPutResource")
#function("XrmPutResource")
#function("XrmQPutStringResource")
#function("XrmPutStringResource")
#function("XrmPutLineResource")
#function("XrmGetStringDatabase")
#function("XrmGetFileDatabase")
#function("XrmCombineFileDatabase")
## function("XrmEnumerateDatabase")
#function("XrmPutFileDatabase")
#function("XrmQGetSearchList")
#function("XrmQGetSearchResource")
#function("XrmQGetResource")
#function("XrmGetResource")
#function("XrmLocaleOfDatabase")
#function("XrmDestroyDatabase")
#function("XrmSetDatabase")
#function("_XDefaultOpenIM")
#function("_XDefaultOpenOM")
#function("_XimXTransFreeConnInfo")
#function("_XimXTransSetOption")
#function("_XimXTransBytesReadable")
#function("_XimXTransRead")
#function("_XimXTransWrite")
#function("_XimXTransReadv")
#function("_XimXTransWritev")
#function("_XimXTransDisconnect")
#function("_XimXTransClose")
#function("_XimXTransCloseForCloning")
#function("_XimXTransIsLocal")
#function("_XimXTransGetPeerAddr")
#function("_XimXTransGetConnectionNumber")
#function("_XimXTransGetHostname")
#function("_XimXTransConnect")
#function("_XimXTransOpenCOTSClient")
## function("XVaCreateNestedList")
## function("XSetIMValues")
## function("XGetIMValues")
#function("XCreateIC")
#function("XDestroyIC")
## function("XGetICValues")
## function("XSetICValues")
#function("XSetICFocus")
#function("XUnsetICFocus")
#function("XIMOfIC")
#function("XmbResetIC")
#function("XwcResetIC")
#function("Xutf8ResetIC")
#function("XmbLookupString")
#function("XwcLookupString")
#function("Xutf8LookupString")
#function("_XIMCompileResourceList")
#function("_XCopyToArg")
#function("XOpenIM")
#function("XCloseIM")
#function("XDisplayOfIM")
#function("XLocaleOfIM")
#function("XRegisterIMInstantiateCallback")
#function("XUnregisterIMInstantiateCallback")
#function("KeySymToUcs4")
#function("_XlcParseCharSet")
#function("_XlcAddCT")
#function("_XlcInitCTInfo")
#function("_XlcGetCharSet")
#function("_XlcGetCharSetWithSide")
#function("_XlcAddCharSet")
#function("_XlcGetCSValues")
#function("_XlcCreateDefaultCharSet")
#function("_XlcSetConverter")
#function("_XlcOpenConverter")
#function("_XlcCloseConverter")
#function("_XlcConvert")
#function("_XlcResetConverter")
#function("_XlcGetResource")
#function("_XlcGetLocaleDataBase")
#function("_XlcDestroyLocaleDataBase")
#function("_XlcCreateLocaleDataBase")
#function("xlocaledir")
#function("_XlcFileName")
#function("_XlcResolveLocaleName")
#function("_XlcResolveI18NPath")
#function("_XlcLocaleDirName")
#function("_XlcLocaleLibDirName")
#function("_XlcParse_scopemaps")
#function("_XlcDbg_printValue")
#function("_XlcInitLoader")
#function("_XlcDeInitLoader")
#function("_XmbTextPropertyToTextList")
#function("_XwcTextPropertyToTextList")
#function("_Xutf8TextPropertyToTextList")
#function("_XwcFreeStringList")
#function("_XGetLCValues")
#function("_XlcDestroyLC")
#function("_XlcCreateLC")
#function("_XrmDefaultInitParseInfo")
#function("_Xlcmbtowc")
#function("_Xlcwctomb")
#function("_Xlcmbstowcs")
#function("_Xmbtowc")
#function("_Xmblen")
#function("_Xwctomb")
#function("_Xmbstowcs")
#function("_Xwcscpy")
#function("_Xwcsncpy")
#function("_Xwcslen")
#function("_Xlcwcstombs")
#function("_Xwcstombs")
#function("_Xwcscmp")
#function("_Xwcsncmp")
#function("_Xlcmbstoutf8")
#function("_Xmbstoutf8")
#function("_XmbTextListToTextProperty")
#function("_XwcTextListToTextProperty")
#function("_Xutf8TextListToTextProperty")
#function("_Utf8GetConvByName")
#function("_XlcAddUtf8Converters")
#function("_XlcAddUtf8LocaleConverters")
#function("_XlcAddGB18030LocaleConverters")
#function("_XlcCompareISOLatin1")
#function("_XlcNCompareISOLatin1")
#function("_XlcValidModSyntax")
#function("_XlcDefaultMapModifiers")
#function("_XlcRemoveLoader")
#function("_XlcAddLoader")
#function("_XOpenLC")
#function("_XCloseLC")
#function("_XlcCurrentLC")
#function("XSetLocaleModifiers")
#function("XSupportsLocale")
#function("_XrmInitParseInfo")
#function("XmbTextPropertyToTextList")
#function("XwcTextPropertyToTextList")
#function("Xutf8TextPropertyToTextList")
#function("XmbTextListToTextProperty")
#function("XwcTextListToTextProperty")
#function("Xutf8TextListToTextProperty")
#function("XwcFreeStringList")
#function("XDefaultString")
#function("_XlcCopyFromArg")
#function("_XlcCopyToArg")
#function("_XlcCountVaList")
#function("_XlcVaToArgList")
#function("_XlcCompileResourceList")
#function("_XlcGetValues")
#function("_XlcSetValues")
#function("XmbSetWMProperties")
#function("XmbDrawText")
#function("XmbDrawString")
#function("XmbDrawImageString")
#function("XmbTextEscapement")
#function("XmbTextExtents")
#function("XmbTextPerCharExtents")
#function("Xutf8SetWMProperties")
#function("Xutf8DrawText")
#function("Xutf8DrawString")
#function("Xutf8DrawImageString")
#function("Xutf8TextEscapement")
#function("Xutf8TextExtents")
#function("Xutf8TextPerCharExtents")
#function("XwcDrawText")
#function("XwcDrawString")
#function("XwcDrawImageString")
#function("XwcTextEscapement")
#function("XwcTextExtents")
#function("XwcTextPerCharExtents")
#function("_XimCbDispatch")
#function("_XimRegisterFilter")
#function("_XimUnregisterFilter")
#function("_XimReregisterFilter")
#function("_XimRegisterServerFilter")
#function("_XimUnregisterServerFilter")
#function("_XimProtoCreateIC")
#function("_XimCheckDataSize")
#function("_XimSetHeader")
#function("_XimGetMyEndian")
#function("_XimProtoIMFree")
#function("_XimProtoOpenIM")
#function("_XimICOfXICID")
#function("_XimSetEventMaskCallback")
#function("_XimProcSyncReply")
#function("_XimRespSyncReply")
#function("_XimSyncCallback")
#function("_XimForwardEventCallback")
#function("_XimGetWindowEventmask")
#function("_XimFreeCommitInfo")
#function("_XimProcError")
#function("_XimSync")
#function("_XimForwardEvent")
#function("_XimTriggerNotify")
#function("_XimErrorCallback")
#function("_XimError")
#function("_XimRegisterTriggerKeysCallback")
#function("_XimCommitCallback")
#function("_Ximctstombs")
#function("_Ximctstowcs")
#function("_Ximctstoutf8")
#function("_XimProtoMbLookupString")
#function("_XimProtoWcLookupString")
#function("_XimProtoUtf8LookupString")
#function("_XimRegProtoIntrCallback")
#function("_XimFreeProtoIntrCallback")
#function("_XimDispatchInit")
#function("_XimProtoEventToWire")
#function("_XimProtoWireToEvent")
#function("_XimExtension")
#function("_XimRegisterIMInstantiateCallback")
#function("_XimUnRegisterIMInstantiateCallback")
#function("_XimResetIMInstantiateCallback")
#function("_XimOpenIM")
#function("_XimDestroyIMStructureList")
#function("_XimServerDestroy")
#function("_XInitIM")
#function("_XimLocalFilter")
#function("_XimLocalGetICValues")
#function("_XimLocalCreateIC")
#function("_XimLocalGetIMValues")
#function("_XimLocalSetIMValues")
#function("_XimCheckIfLocalProcessing")
#function("_XimLocalIMFree")
#function("_XimLocalOpenIM")
#function("_XimLocalMbLookupString")
#function("_XimLocalWcLookupString")
#function("_XimLocalUtf8LookupString")
#function("_XimLcctstombs")
#function("_XimLcctstowcs")
#function("_XimLcctstoutf8")
#function("_XimParseStringFile")
#function("_XimLocalSetICValues")
#function("_XimSetIMResourceList")
#function("_XimSetICResourceList")
#function("_XimSetInnerIMResourceList")
#function("_XimSetInnerICResourceList")
#function("_XimCheckCreateICValues")
#function("_XimGetResourceListRecByQuark")
#function("_XimGetResourceListRec")
#function("_XimSetIMMode")
#function("_XimCheckIMMode")
#function("_XimSetICMode")
#function("_XimCheckICMode")
#function("_XimSetLocalIMDefaults")
#function("_XimSetICDefaults")
#function("_XimEncodeLocalIMAttr")
#function("_XimSetIMValueData")
#function("_XimEncodeLocalICAttr")
#function("_XimSetICValueData")
#function("_XimCheckLocalInputStyle")
#function("_XimDecodeLocalIMAttr")
#function("_XimGetIMValueData")
#function("_XimDecodeLocalICAttr")
#function("_XimGetICValueData")
#function("_XimGetCurrentIMValues")
#function("_XimSetCurrentIMValues")
#function("_XimGetCurrentICValues")
#function("_XimSetCurrentICValues")
#function("_XimInitialResourceInfo")
#function("_XimMakeIMAttrIDList")
#function("_XimMakeICAttrIDList")
#function("_XimDecodeIMATTRIBUTE")
#function("_XimDecodeICATTRIBUTE")
#function("_XimEncodeIMATTRIBUTE")
#function("_XimEncodeICATTRIBUTE")
#function("_XimGetAttributeID")
#function("_XimThaiFilter")
#function("_XimThaiCreateIC")
#function("_XimCheckIfThaiProcessing")
#function("_XimThaiIMFree")
#function("_XimThaiOpenIM")
#function("_XimThaiCloseIM")
#function("_XimXConf")
#function("_XimTransCallDispatcher")
#function("_XimTransFlush")
#function("_XimTransRegisterDispatcher")
#function("_XimTransFilterWaitEvent")
#function("_XimTransWrite")
#function("_XimTransRead")
#function("_XimTransInternalConnection")
#function("_XimFreeTransIntrCallback")
#function("_XimTransConf")
#function("_XimConnect")
#function("_XimShutdown")
#function("_XimWrite")
#function("_XimRead")
#function("_XimRegisterDispatcher")
#function("_XimFlush")
#function("_XimFilterWaitEvent")
#function("_XlcDefaultLoader")
#function("_XlcGenericLoader")
#function("_XlcUtf8Loader")
#function("_XmbDefaultTextEscapement")
#function("_XwcDefaultTextEscapement")
#function("_Xutf8DefaultTextEscapement")
#function("_XmbDefaultTextExtents")
#function("_XwcDefaultTextExtents")
#function("_Xutf8DefaultTextExtents")
#function("_XmbDefaultTextPerCharExtents")
#function("_XwcDefaultTextPerCharExtents")
#function("_Xutf8DefaultTextPerCharExtents")
#function("_XmbDefaultDrawString")
#function("_XwcDefaultDrawString")
#function("_Xutf8DefaultDrawString")
#function("_XmbDefaultDrawImageString")
#function("_XwcDefaultDrawImageString")
#function("_Xutf8DefaultDrawImageString")
#function("read_EncodingInfo")
#function("_XomGenericOpenOM")
#function("_XInitOM")
#function("_XmbGenericDrawImageString")
#function("_XwcGenericDrawImageString")
#function("_Xutf8GenericDrawImageString")
#function("_XomGenericDrawString")
#function("_XmbGenericDrawString")
#function("_XwcGenericDrawString")
#function("_Xutf8GenericDrawString")
#function("_XmbGenericTextEscapement")
#function("_XwcGenericTextEscapement")
#function("_Xutf8GenericTextEscapement")
#function("_XomGenericTextExtents")
#function("_XmbGenericTextExtents")
#function("_XwcGenericTextExtents")
#function("_Xutf8GenericTextExtents")
#function("_XmbGenericTextPerCharExtents")
#function("_XwcGenericTextPerCharExtents")
#function("_Xutf8GenericTextPerCharExtents")
#function("_XomGetFontDataFromFontSet")
#function("_XomConvert")
#function("_XomInitConverter")
#function("XcmsAddColorSpace")
#function("XcmsAddFunctionSet")
#function("XcmsDefaultCCC")
#function("XcmsCreateCCC")
#function("XcmsFreeCCC")
#function("_XcmsConvertColorsWithWhitePt")
#function("_XcmsDIConvertColors")
#function("_XcmsEqualWhitePts")
#function("_XcmsDDConvertColors")
#function("XcmsConvertColors")
#function("_XcmsRegFormatOfPrefix")
#function("XcmsCIEuvYToTekHVC")
#function("XcmsTekHVCToCIEuvY")
#function("_XcmsTekHVC_CheckModify")
#function("XcmsTekHVCClipC")
#function("XcmsTekHVCClipV")
#function("XcmsTekHVCClipVC")
#function("XcmsTekHVCQueryMinV")
#function("XcmsTekHVCQueryMaxC")
#function("XcmsTekHVCQueryMaxV")
#function("_XcmsTekHVCQueryMaxVCRGB")
#function("XcmsTekHVCQueryMaxVC")
#function("XcmsTekHVCQueryMaxVSamples")
#function("XcmsTekHVCWhiteShiftColors")
#function("XcmsFormatOfPrefix")
#function("XcmsCIEXYZToRGBi")
#function("XcmsRGBiToCIEXYZ")
#function("XcmsRGBToRGBi")
#function("XcmsRGBiToRGB")
#function("_XcmsLRGB_InitScrnDefault")
#function("XcmsCIELabToCIEXYZ")
#function("XcmsCIEXYZToCIELab")
#function("XcmsCIELabClipab")
#function("XcmsCIELabClipL")
#function("XcmsCIELabClipLab")
#function("XcmsCIELabQueryMinL")
#function("XcmsCIELabQueryMaxC")
#function("XcmsCIELabQueryMaxL")
#function("_XcmsCIELabQueryMaxLCRGB")
#function("XcmsCIELabQueryMaxLC")
#function("XcmsCIELabWhiteShiftColors")
#function("XcmsCIELuvToCIEuvY")
#function("XcmsCIEuvYToCIELuv")
#function("XcmsCIELuvClipuv")
#function("XcmsCIELuvClipL")
#function("XcmsCIELuvClipLuv")
#function("XcmsCIELuvQueryMinL")
#function("XcmsCIELuvQueryMaxC")
#function("XcmsCIELuvQueryMaxL")
#function("_XcmsCIELuvQueryMaxLCRGB")
#function("XcmsCIELuvQueryMaxLC")
#function("XcmsCIELuvWhiteShiftColors")
#function("XcmsDisplayOfCCC")
#function("XcmsVisualOfCCC")
#function("XcmsScreenNumberOfCCC")
#function("XcmsScreenWhitePointOfCCC")
#function("XcmsClientWhitePointOfCCC")
#function("XcmsPrefixOfFormat")
#function("XcmsQueryBlack")
#function("XcmsQueryBlue")
#function("XcmsQueryGreen")
#function("XcmsQueryRed")
#function("XcmsQueryWhite")
#function("XcmsQueryColor")
#function("XcmsQueryColors")
#function("XcmsSetWhitePoint")
#function("XcmsSetCompressionProc")
#function("XcmsSetWhiteAdjustProc")
#function("_XcmsSetGetColor")
#function("_XcmsSetGetColors")
#function("XcmsStoreColor")
#function("XcmsStoreColors")
#function("_XcmsRGB_to_XColor")
#function("_XColor_to_XcmsRGB")
#function("_XcmsResolveColor")
#function("_XcmsUnresolveColor")
#function("_XUnresolveColor")
#function("_XcmsCIEXYZ_ValidSpec")
#function("XcmsAllocColor")
#function("XcmsAllocNamedColor")
#function("_XcmsAddCmapRec")
#function("_XcmsCopyCmapRecAndFree")
#function("_XcmsDeleteCmapRec")
#function("XcmsCCCOfColormap")
#function("XcmsSetCCCOfColormap")
#function("_XcmsCopyISOLatin1Lowered")
#function("_XcmsResolveColorString")
#function("_XcmsCopyPointerArray")
#function("_XcmsFreePointerArray")
#function("_XcmsPushPointerArray")
#function("_XcmsInitDefaultCCCs")
#function("_XcmsInitScrnInfo")
#function("_XcmsFreeIntensityMaps")
#function("_XcmsGetIntensityMap")
#function("XcmsLookupColor")
#function("_XcmsCubeRoot")
#function("_XcmsSquareRoot")
#function("_XcmsGetElement")
#function("_XcmsGetProperty")
#function("_XcmsSine")
#function("_XcmsCosine")
#function("_XcmsArcTangent")
#function("XcmsCIEXYZToCIEuvY")
#function("_XcmsCIEuvY_ValidSpec")
#function("XcmsCIEuvYToCIEXYZ")
#function("XcmsCIExyYToCIEXYZ")
#function("XcmsCIEXYZToCIExyY")
#function("XkbQueryExtension")
#function("XkbLibraryVersion")
#function("XkbSelectEvents")
#function("XkbSelectEventDetails")
#function("XkbLockModifiers")
#function("XkbLatchModifiers")
#function("XkbLockGroup")
#function("XkbLatchGroup")
#function("XkbSetXlibControls")
#function("XkbGetXlibControls")
#function("XkbXlibControlsImplemented")
#function("XkbSetDebuggingFlags")
#function("XkbComputeEffectiveMap")
#function("XkbGetState")
#function("XkbSetDetectableAutoRepeat")
#function("XkbGetDetectableAutoRepeat")
#function("XkbSetAutoResetControls")
#function("XkbGetAutoResetControls")
#function("XkbSetPerClientControls")
#function("XkbGetPerClientControls")
#function("XkbOpenDisplay")
#function("XkbSetAtomFuncs")
#function("XkbTranslateKeyCode")
#function("_XkbReloadDpy")
#function("XkbKeycodeToKeysym")
#function("XKeycodeToKeysym")
#function("XKeysymToKeycode")
#function("XkbKeysymToModifiers")
#function("XLookupKeysym")
#function("XkbLookupKeySym")
#function("XkbTranslateKey")
#function("XkbRefreshKeyboardMapping")
#function("XRefreshKeyboardMapping")
#function("XkbLookupKeyBinding")
#function("XkbToControl")
#function("XkbTranslateKeySym")
#function("XLookupString")
#function("_XkbReadGetCompatMapReply")
#function("XkbGetCompatMap")
#function("XkbSetCompatMap")
#function("XkbSetAutoRepeatRate")
#function("XkbGetAutoRepeatRate")
#function("XkbSetServerInternalMods")
#function("XkbSetIgnoreLockMods")
#function("XkbChangeEnabledControls")
#function("XkbGetControls")
#function("XkbSetControls")
#function("XkbNoteControlsChanges")
#function("_XkbGetConverters")
#function("_XkbGetCharset")
#function("_XkbReadGetMapReply")
#function("XkbGetUpdatedMap")
#function("XkbGetMap")
#function("XkbGetKeyTypes")
#function("XkbGetKeyActions")
#function("XkbGetKeySyms")
#function("XkbGetKeyBehaviors")
#function("XkbGetVirtualMods")
#function("XkbGetKeyExplicitComponents")
#function("XkbGetKeyModifierMap")
#function("XkbGetKeyVirtualModMap")
#function("XkbGetMapChanges")
#function("XkbGetKeyboardByName")
#function("XkbGetKeyboard")
#function("_XkbReadGetNamesReply")
#function("XkbGetNames")
#function("XkbSetNames")
#function("XkbChangeNames")
#function("XkbNoteNameChanges")
#function("_XkbInitReadBuffer")
#function("_XkbSkipReadBufferData")
#function("_XkbCopyFromReadBuffer")
#function("_XkbReadCopyKeySyms")
#function("_XkbReadBufferCopyKeySyms")
#function("_XkbReadCopyData32")
#function("_XkbReadBufferCopy32")
#function("_XkbWriteCopyData32")
#function("_XkbWriteCopyKeySyms")
#function("_XkbPeekAtReadBuffer")
#function("_XkbGetReadBufferPtr")
#function("_XkbFreeReadBuffer")
#function("_XkbGetReadBufferCountedString")
#function("XkbSetMap")
#function("XkbChangeMap")
#function("XkbNoteMapChanges")
#function("_XkbNoteCoreMapChanges")
#function("XkbIgnoreExtension")
#function("XkbUseExtension")
#function("XkbGetIndicatorState")
#function("_XkbReadGetIndicatorMapReply")
#function("XkbGetIndicatorMap")
#function("XkbSetIndicatorMap")
#function("XkbGetNamedDeviceIndicator")
#function("XkbGetNamedIndicator")
#function("XkbSetNamedDeviceIndicator")
#function("XkbSetNamedIndicator")
#function("XkbDeviceBell")
#function("XkbForceDeviceBell")
#function("XkbDeviceBellEvent")
#function("XkbBell")
#function("XkbForceBell")
#function("XkbBellEvent")
#function("XkbComputeShapeBounds")
#function("XkbComputeShapeTop")
#function("XkbComputeRowBounds")
#function("XkbComputeSectionBounds")
#function("XkbFindOverlayForKey")
#function("_XkbReadGetGeometryReply")
#function("XkbGetGeometry")
#function("XkbGetNamedGeometry")
#function("XkbSetGeometry")
#function("XkbNoteDeviceChanges")
#function("XkbGetDeviceInfo")
#function("XkbGetDeviceInfoChanges")
#function("XkbGetDeviceButtonActions")
#function("XkbGetDeviceLedInfo")
#function("XkbSetDeviceInfo")
#function("XkbChangeDeviceInfo")
#function("XkbSetDeviceLedInfo")
#function("XkbSetDeviceButtonActions")
#function("XkbFreeComponentList")
#function("XkbListComponents")
#function("XkbInitCanonicalKeyTypes")
#function("XkbKeyTypesForCoreSymbols")
#function("XkbChangeTypesOfKey")
#function("XkbVirtualModsToReal")
#function("XkbApplyCompatMapToKey")
#function("XkbUpdateActionVirtualMods")
#function("XkbUpdateKeyTypeVirtualMods")
#function("XkbApplyVirtualModChanges")
#function("XkbUpdateMapFromCore")
#function("XkbAllocClientMap")
#function("XkbAllocServerMap")
#function("XkbCopyKeyType")
#function("XkbCopyKeyTypes")
#function("XkbResizeKeyType")
#function("XkbAddKeyType")
#function("XkbResizeKeySyms")
#function("XkbChangeKeycodeRange")
#function("XkbResizeKeyActions")
#function("XkbFreeClientMap")
#function("XkbFreeServerMap")
#function("XkbFreeGeomProperties")
#function("XkbFreeGeomKeyAliases")
#function("XkbFreeGeomColors")
#function("XkbFreeGeomPoints")
#function("XkbFreeGeomOutlines")
#function("XkbFreeGeomShapes")
#function("XkbFreeGeomOverlayKeys")
#function("XkbFreeGeomOverlayRows")
#function("XkbFreeGeomOverlays")
#function("XkbFreeGeomKeys")
#function("XkbFreeGeomRows")
#function("XkbFreeGeomSections")
#function("XkbFreeGeomDoodads")
#function("XkbFreeGeometry")
#function("XkbAllocGeomProps")
#function("XkbAllocGeomColors")
#function("XkbAllocGeomKeyAliases")
#function("XkbAllocGeomShapes")
#function("XkbAllocGeomSections")
#function("XkbAllocGeomOverlays")
#function("XkbAllocGeomOverlayRows")
#function("XkbAllocGeomOverlayKeys")
#function("XkbAllocGeomDoodads")
#function("XkbAllocGeomSectionDoodads")
#function("XkbAllocGeomOutlines")
#function("XkbAllocGeomRows")
#function("XkbAllocGeomPoints")
#function("XkbAllocGeomKeys")
#function("XkbAllocGeometry")
#function("XkbAddGeomProperty")
#function("XkbAddGeomKeyAlias")
#function("XkbAddGeomColor")
#function("XkbAddGeomOutline")
#function("XkbAddGeomShape")
#function("XkbAddGeomKey")
#function("XkbAddGeomRow")
#function("XkbAddGeomSection")
#function("XkbAddGeomDoodad")
#function("XkbAddGeomOverlayKey")
#function("XkbAddGeomOverlayRow")
#function("XkbAddGeomOverlay")
#function("XkbAllocCompatMap")
#function("XkbFreeCompatMap")
#function("XkbAllocNames")
#function("XkbFreeNames")
#function("XkbAllocControls")
#function("XkbFreeControls")
#function("XkbAllocIndicatorMaps")
#function("XkbFreeIndicatorMaps")
#function("XkbAllocKeyboard")
#function("XkbFreeKeyboard")
#function("XkbAddDeviceLedInfo")
#function("XkbResizeDeviceButtonActions")
#function("XkbAllocDeviceInfo")
#function("XkbFreeDeviceInfo")
#function("_Xevent_to_mask")
#function("_XkeyTable")
#function("_XcmsRGB_prefix")
#function("_XcmsRGBi_prefix")
#function("_XcmsTekHVC_prefix")
#function("_XcmsCIELuv_prefix")
#function("_XcmsCIELab_prefix")
#function("_XcmsCIExyY_prefix")
#function("_XcmsCIEuvY_prefix")
#function("_XcmsCIEXYZ_prefix")
#function("_XimXTransSocketUNIXFuncs")
#function("_XimXTransSocketLocalFuncs")
#function("_XimXTransSocketINET6Funcs")
#function("_XimXTransSocketINETFuncs")
#function("_XimXTransSocketTCPFuncs")
#function("_XlcGenericMethods")
#function("_XlcPublicMethods")
#function("_XimImSportRec")
#function("_XimTransportRec")
#function("XcmsTekHVCColorSpace")
#function("XcmsLinearRGBFunctionSet")
#function("XcmsRGBColorSpace")
#function("XcmsRGBiColorSpace")
#function("XcmsCIELabColorSpace")
#function("XcmsCIELuvColorSpace")
#function("XcmsUNDEFINEDColorSpace")
#function("XcmsCIEXYZColorSpace")
#function("_XcmsRegColorSpaces")
#function("_XcmsSCCFuncSets")
#function("_XcmsSCCFuncSetsInit")
#function("_XcmsDDColorSpaces")
#function("_XcmsDDColorSpacesInit")
#function("_XcmsDIColorSpaces")
#function("_XcmsDIColorSpacesInit")
#function("XcmsCIEuvYColorSpace")
#function("XcmsCIExyYColorSpace")
#function("_XkbGetAtomNameFunc")
#function("_XkbInternAtomFunc")
#function("_XFreeDisplayLock_fn")
#function("_XInitDisplayLock_fn")
#function("_Xthread_self_fn")
#function("_XUnlockMutex_fn")
#function("_XLockMutex_fn")
#function("_XFreeMutex_fn")
#function("_XCreateMutex_fn")
#function("_Xglobal_lock")
#function("_qfree")
#function("_XHeadOfDisplayList")
#function("_XErrorFunction")
#function("_XIOErrorFunction")
##function("_Xdebug")
#function("_Xi18n_lock")

fn("char* XFetchBytes(Display*, int*)")
fn("char* XLocaleOfIM(XIM)")
fn("char* XLocaleOfOM(XOM)")
fn("char* XmbResetIC(XIC)")
fn("char* Xpermalloc(unsigned int)")
fn("char* Xutf8ResetIC(XIC)")
fn("const char* XrmLocaleOfDatabase(XrmDatabase)")
fn("Display* XDisplayOfOM(XOM)")
fn("int XChangeKeyboardMapping(Display*, int, int, KeySym*, int)")
fn("int XCloseOM(XOM)")
fn("int XDrawText16(Display*, Drawable, GC, int, int, XTextItem16*, int)")
fn("int XDrawText(Display*, Drawable, GC, int, int, XTextItem*, int)")
fn("int XInternalConnectionNumbers(Display*, int**, int*)")
fn("int XMaskEvent(Display*, long int, XEvent*)")
fn("int XmbTextExtents(XFontSet, const char*, int, XRectangle*, XRectangle*)")
fn("int XmbTextPerCharExtents(XFontSet, const char*, int, XRectangle*, XRectangle*, int, int*, XRectangle*, XRectangle*)")
fn("int _Xmbtowc(wchar_t*, char*, int)")
fn("int XNoOp(Display*)")
fn("int XOffsetRegion(Region, int, int)")
# fn("int XPeekIfEvent(Display*, XEvent*, int (*)(Display*, XEvent*, XPointer), XPointer)")
fn("int XPointInRegion(Region, int, int)")
fn("int XQueryBestCursor(Display*, Drawable, unsigned int, unsigned int, unsigned int*, unsigned int*)")
fn("int XQueryBestSize(Display*, int, Drawable, unsigned int, unsigned int, unsigned int*, unsigned int*)")
fn("int XQueryBestStipple(Display*, Drawable, unsigned int, unsigned int, unsigned int*, unsigned int*)")
fn("int XQueryBestTile(Display*, Drawable, unsigned int, unsigned int, unsigned int*, unsigned int*)")
fn("int XQueryKeymap(Display*, char*)")
fn("int XQueryTextExtents16(Display*, XID, const XChar2b*, int, int*, int*, int*, XCharStruct*)")
fn("int XQueryTextExtents(Display*, XID, const char*, int, int*, int*, int*, XCharStruct*)")
fn("int XReadBitmapFile(Display*, Drawable, const char*, unsigned int*, unsigned int*, Pixmap*, int*, int*)")
fn("int XReconfigureWMWindow(Display*, Window, int, unsigned int, XWindowChanges*)")
fn("int XRegisterIMInstantiateCallback(Display*, _XrmHashBucketRec*, char*, char*, XIDProc, XPointer)")
fn("int XRestackWindows(Display*, Window*, int)")
fn("int XRotateWindowProperties(Display*, Window, Atom*, int, int)")
fn("int XSetClassHint(Display*, Window, XClassHint*)")
fn("int XSetFontPath(Display*, char**, int)")
fn("int XSetIconName(Display*, Window, const char*)")
fn("int XSetModifierMapping(Display*, XModifierKeymap*)")
fn("int XSetPointerMapping(Display*, const unsigned char*, int)")
fn("int XSetScreenSaver(Display*, int, int, int, int)")
fn("int XSetSizeHints(Display*, Window, XSizeHints*, Atom)")
fn("int XSetState(Display*, GC, long unsigned int, long unsigned int, int, long unsigned int)")
fn("int XSetWMColormapWindows(Display*, Window, Window*, int)")
fn("int XSetZoomHints(Display*, Window, XSizeHints*)")
fn("int XShrinkRegion(Region, int, int)")
fn("int XStoreBuffer(Display*, const char*, int, int)")
fn("int XStoreColor(Display*, Colormap, XColor*)")
fn("int XStoreNamedColor(Display*, Colormap, const char*, long unsigned int, int)")
fn("int XStringListToTextProperty(char**, int, XTextProperty*)")
fn("int XTextExtents(XFontStruct*, const char*, int, int*, int*, int*, XCharStruct*)")
fn("int XTextPropertyToStringList(XTextProperty*, char***, int*)")
fn("int XUninstallColormap(Display*, Colormap)")
fn("int XUnregisterIMInstantiateCallback(Display*, _XrmHashBucketRec*, char*, char*, XIDProc, XPointer)")
fn("int Xutf8TextEscapement(XFontSet, const char*, int)")
fn("int Xutf8TextExtents(XFontSet, const char*, int, XRectangle*, XRectangle*)")
fn("int Xutf8TextPerCharExtents(XFontSet, const char*, int, XRectangle*, XRectangle*, int, int*, XRectangle*, XRectangle*)")
fn("int XwcTextExtents(XFontSet, const wchar_t*, int, XRectangle*, XRectangle*)")
fn("int XwcTextPerCharExtents(XFontSet, const wchar_t*, int, XRectangle*, XRectangle*, int, int*, XRectangle*, XRectangle*)")
fn("int _Xwctomb(char*, wchar_t)")
fn("int XWriteBitmapFile(Display*, const char*, Pixmap, unsigned int, unsigned int, int, int)")
fn("int XXorRegion(Region, Region, Region)")
fn("KeyCode XKeysymToKeycode(Display*, KeySym)")
fn("KeySym XKeycodeToKeysym(Display*, KeyCode, int)")
fn("long unsigned int XDisplayMotionBufferSize(Display*)")
fn("void XDestroyOC(XOC)")
fn("void XmbDrawText(Display*, Drawable, GC, int, int, XmbTextItem*, int)")
fn("void XmbSetWMProperties(Display*, Window, const char*, const char*, char**, int, XSizeHints*, XWMHints*, XClassHint*)")
fn("void XRemoveConnectionWatch(Display*, XConnectionWatchProc, XPointer)")
fn("void XrmPutFileDatabase(XrmDatabase, const char*)")
fn("void XrmPutResource(_XrmHashBucketRec**, const char*, const char*, XrmValue*)")
fn("void XrmQPutStringResource(_XrmHashBucketRec**, XrmBindingList, XrmQuarkList, const char*)")
fn("void XrmStringToQuarkList(const char*, XrmQuarkList)")
fn("void XSetStandardColormap(Display*, Window, XStandardColormap*, Atom)")
fn("void XSetTextProperty(Display*, Window, XTextProperty*, Atom)")
fn("void XSetWMClientMachine(Display*, Window, XTextProperty*)")
fn("void XSetWMSizeHints(Display*, Window, XSizeHints*, Atom)")
fn("void Xutf8DrawImageString(Display*, Drawable, XFontSet, GC, int, int, const char*, int)")
fn("void Xutf8DrawString(Display*, Drawable, XFontSet, GC, int, int, const char*, int)")
fn("void Xutf8DrawText(Display*, Drawable, GC, int, int, XmbTextItem*, int)")
fn("void XwcDrawText(Display*, Drawable, GC, int, int, XwcTextItem*, int)")
fn("wchar_t* XwcResetIC(XIC)")
fn("_XIM* XIMOfIC(XIC)")
fn("XModifierKeymap* XDeleteModifiermapEntry(XModifierKeymap*, KeyCode, int)")
fn("XModifierKeymap* XInsertModifiermapEntry(XModifierKeymap*, KeyCode, int)")
fn("XModifierKeymap* XNewModifiermap(int)")
fn("_XOM* XOMOfOC(XOC)")
fn("_XOM* XOpenOM(Display*, _XrmHashBucketRec*, const char*, const char*)")
fn("_XRegion* XPolygonRegion(XPoint*, int, int)")


fn("const char* XDefaultString()")
fn("XClassHint* XAllocClassHint()")
fn("XWMHints* XAllocWMHints()")

fn("Atom* XListProperties(Display*, Window, int*)")
fn("char* XBaseFontNameListOfFontSet(XFontSet)")
fn("char** XGetFontPath(Display*, int*)")
fn("char** XListFontsWithInfo(Display*, const char*, int, int*, XFontStruct**)")
fn("char* XLocaleOfFontSet(XFontSet)")
fn("char* XServerVendor(Display*)")
fn("Colormap XCopyColormapAndFree(Display*, Colormap)")
fn("Colormap XDefaultColormapOfScreen(Screen*)")
fn("Colormap* XListInstalledColormaps(Display*, Window, int*)")
fn("int XActivateScreenSaver(Display*)")
fn("int XAddHosts(Display*, XHostAddress*, int)")
fn("int XAddToExtensionList(_XExtData**, XExtData*)")
fn("int XAddToSaveSet(Display*, Window)")
fn("int XAllocColorPlanes(Display*, Colormap, int, long unsigned int*, int, int, int, int, long unsigned int*, long unsigned int*, long unsigned int*)")
fn("int XAllowEvents(Display*, int, Time)")
fn("int XAutoRepeatOff(Display*)")
fn("int XAutoRepeatOn(Display*)")
fn("int XBitmapBitOrder(Display*)")
fn("int XBitmapPad(Display*)")
fn("int XBitmapUnit(Display*)")
fn("int XCellsOfScreen(Screen*)")
fn("int XChangeKeyboardControl(Display*, long unsigned int, XKeyboardControl*)")
fn("int XChangePointerControl(Display*, int, int, int, int, int)")
fn("int XChangeSaveSet(Display*, Window, int)")
fn("int XCheckMaskEvent(Display*, long int, XEvent*)")
fn("int XCheckTypedEvent(Display*, int, XEvent*)")
fn("int XCheckTypedWindowEvent(Display*, Window, int, XEvent*)")
fn("int XCirculateSubwindows(Display*, Window, int)")
fn("int XCirculateSubwindowsDown(Display*, Window)")
fn("int XCirculateSubwindowsUp(Display*, Window)")
fn("int XConnectionNumber(Display*)")
fn("int XContextDependentDrawing(XFontSet)")
fn("int XContextualDrawing(XFontSet)")
fn("int XCopyGC(Display*, GC, long unsigned int, GC)")
fn("int XDefaultDepthOfScreen(Screen*)")
fn("int XDestroySubwindows(Display*, Window)")
fn("int XDirectionalDependentDrawing(XFontSet)")
fn("int XDisplayCells(Display*, int)")
fn("int XDisplayHeightMM(Display*, int)")
fn("int XDisplayPlanes(Display*, int)")
fn("int XDisplayWidthMM(Display*, int)")
fn("int XDoesBackingStore(Screen*)")
fn("int XDoesSaveUnders(Screen*)")
fn("int XDrawImageString16(Display*, Drawable, GC, int, int, const XChar2b*, int)")
fn("int XDrawRectangles(Display*, Drawable, GC, XRectangle*, int)")
fn("int XForceScreenSaver(Display*, int)")
fn("int XFreeFontInfo(char**, XFontStruct*, int)")
fn("int XFreeFontNames(char**)")
fn("int XFreeFontPath(char**)")
fn("int XGeometry(Display*, int, const char*, const char*, unsigned int, unsigned int, unsigned int, int, int, int*, int*, int*, int*)")
fn("int XGetAtomNames(Display*, Atom*, int, char**)")
fn("int XGetCommand(Display*, Window, char***, int*)")
fn("int XGetIconName(Display*, Window, char**)")
fn("int XGetIconSizes(Display*, Window, XIconSize**, int*)")
fn("int XGetKeyboardControl(Display*, XKeyboardState*)")
fn("int XGetNormalHints(Display*, Window, XSizeHints*)")
fn("int XGetPointerControl(Display*, int*, int*, int*)")
fn("int XGetPointerMapping(Display*, unsigned char*, int)")
fn("int XGetScreenSaver(Display*, int*, int*, int*, int*)")
fn("int XGetSizeHints(Display*, Window, XSizeHints*, Atom)")
fn("int XGetStandardColormap(Display*, Window, XStandardColormap*, Atom)")
fn("int XGetTextProperty(Display*, Window, XTextProperty*, Atom)")
fn("int XGetTransientForHint(Display*, Window, Window*)")
fn("int XGetWMColormapWindows(Display*, Window, Window**, int*)")
fn("int XGetWMIconName(Display*, Window, XTextProperty*)")
fn("int XGetWMSizeHints(Display*, Window, XSizeHints*, long int*, Atom)")
fn("int XGetZoomHints(Display*, Window, XSizeHints*)")
fn("int XHeightMMOfScreen(Screen*)")
fn("int XHeightOfScreen(Screen*)")
fn("int XImageByteOrder(Display*)")
fn("int XInstallColormap(Display*, Colormap)")
fn("int XMaxCmapsOfScreen(Screen*)")
fn("int XMinCmapsOfScreen(Screen*)")
fn("int XPlanesOfScreen(Screen*)")
fn("int XProtocolRevision(Display*)")
fn("int XProtocolVersion(Display*)")
fn("int XQLength(Display*)")
fn("int XRebindKeysym(Display*, KeySym, KeySym*, int, const unsigned char*, int)")
fn("int XRemoveFromSaveSet(Display*, Window)")
fn("int XRemoveHosts(Display*, XHostAddress*, int)")
fn("int XScreenCount(Display*)")
fn("int XSetAccessControl(Display*, int)")
fn("int XSetWindowColormap(Display*, Window, Colormap)")
fn("int XVendorRelease(Display*)")
fn("int XWidthMMOfScreen(Screen*)")
fn("int XWidthOfScreen(Screen*)")
fn("long int XEventMaskOfScreen(Screen*)")
fn("long unsigned int XAllPlanes()")
fn("long unsigned int XBlackPixel(Display*, int)")
fn("long unsigned int XBlackPixelOfScreen(Screen*)")
fn("long unsigned int XLastKnownRequestProcessed(Display*)")
fn("long unsigned int XWhitePixel(Display*, int)")
fn("long unsigned int XWhitePixelOfScreen(Screen*)")
fn("Screen* XScreenOfDisplay(Display*, int)")
fn("Visual* XDefaultVisualOfScreen(Screen*)")
fn("void XFlushGC(Display*, GC)")
fn("Window XRootWindowOfScreen(Screen*)")
fn("XExtData** XEHeadOfExtensionList(XEDataObject)")
fn("XExtData* XFindOnExtensionList(XExtData**, int)")
fn("_XGC* XDefaultGC(Display*, int)")
fn("_XGC* XDefaultGCOfScreen(Screen*)")
fn("XImage* XGetSubImage(Display*, Drawable, int, int, unsigned int, unsigned int, long unsigned int, int, XImage*, int, int)")
fn("XTimeCoord* XGetMotionEvents(Display*, Window, Time, Time, int*)")

# these is internal? libcairo uses it
fn("void _XReadEvents(Display *)")

fn("int XInitImage(XImage*)")
fn("char* XrmQuarkToString(XrmQuark)")
fn("int XrmCombineFileDatabase(const char*, _XrmHashBucketRec**, int)")
fn("int XrmGetResource(XrmDatabase, const char*, const char*, char**, XrmValue*)")
fn("int XrmQGetResource(XrmDatabase, XrmNameList, XrmClassList, XrmRepresentation*, XrmValue*)")
fn("int XrmQGetSearchList(XrmDatabase, XrmNameList, XrmClassList, _XrmHashBucketRec***, int)")
fn("int XrmQGetSearchResource(_XrmHashBucketRec***, XrmName, XrmClass, XrmRepresentation*, XrmValue*)")
fn("void XrmCombineDatabase(XrmDatabase, _XrmHashBucketRec**, int)")
fn("void XrmDestroyDatabase(XrmDatabase)")
fn("void XrmMergeDatabases(XrmDatabase, _XrmHashBucketRec**)")
fn("void XrmParseCommand(_XrmHashBucketRec**, XrmOptionDescList, int, const char*, int*, char**)")
fn("void XrmPutLineResource(_XrmHashBucketRec**, const char*)")
fn("void XrmPutStringResource(_XrmHashBucketRec**, const char*, const char*)")
fn("void XrmQPutResource(_XrmHashBucketRec**, XrmBindingList, XrmQuarkList, XrmRepresentation, XrmValue*)")
fn("void XrmSetDatabase(Display*, XrmDatabase)")
fn("void XrmStringToBindingQuarkList(const char*, XrmBindingList, XrmQuarkList)")
fn("_XrmHashBucketRec* XrmGetDatabase(Display*)")
fn("_XrmHashBucketRec* XrmGetFileDatabase(const char*)")
fn("_XrmHashBucketRec* XrmGetStringDatabase(const char*)")
fn("XrmQuark XrmUniqueQuark()")
fn("XrmQuark XrmStringToQuark(const char*)")
fn("XrmQuark XrmPermStringToQuark(const char*)")

fn("char* XDisplayName(const char*)")
fn("char* XDisplayString(Display*)")
fn("char* XFetchBuffer(Display*, int*, int)")
fn("char* XGetAtomName(Display*, Atom)")
fn("char* XGetDefault(Display*, const char*, const char*)")
fn("char* XKeysymToString(KeySym)")
fn("char** XListFonts(Display*, const char*, int, int*)")
fn("char* XResourceManagerString(Display*)")
fn("char* XScreenResourceString(Screen*)")
fn("Colormap XDefaultColormap(Display*, int)")
fn("Cursor XCreateFontCursor(Display*, unsigned int)")
fn("Cursor XCreateGlyphCursor(Display*, Font, Font, unsigned int, unsigned int, const XColor*, const XColor*)")
fn("Display* XDisplayOfIM(XIM)")
fn("Display* XDisplayOfScreen(Screen*)")
fn("Font XLoadFont(Display*, const char*)")
fn("GContext XGContextFromGC(GC)")
fn("int XAddConnectionWatch(Display*, XConnectionWatchProc, XPointer)")
fn("int XAddHost(Display*, XHostAddress*)")
fn("int XAllocColorCells(Display*, Colormap, int, long unsigned int*, unsigned int, long unsigned int*, unsigned int)")
fn("int XAllocColor(Display*, Colormap, XColor*)")
fn("int XAllocNamedColor(Display*, Colormap, const char*, XColor*, XColor*)")
fn("int XBell(Display*, int)")
fn("int XChangeActivePointerGrab(Display*, unsigned int, Cursor, Time)")
fn("int XChangeGC(Display*, GC, long unsigned int, XGCValues*)")
fn("int XChangeWindowAttributes(Display*, Window, long unsigned int, XSetWindowAttributes*)")
fn("int XClearArea(Display*, Window, int, int, unsigned int, unsigned int, int)")
fn("int XClearWindow(Display*, Window)")
fn("int XClipBox(Region, XRectangle*)")
fn("int XConfigureWindow(Display*, Window, unsigned int, XWindowChanges*)")
fn("int XConvertSelection(Display*, Atom, Atom, Atom, Window, Time)")
fn("int XCopyArea(Display*, Drawable, Drawable, GC, int, int, unsigned int, unsigned int, int, int)")
fn("int XCopyPlane(Display*, Drawable, Drawable, GC, int, int, unsigned int, unsigned int, int, int, long unsigned int)")
fn("int XDefaultDepth(Display*, int)")
fn("int XDeleteContext(Display*, XID, XContext)")
fn("int XDeleteProperty(Display*, Window, Atom)")
fn("int XDestroyRegion(Region)")
fn("int XDisableAccessControl(Display*)")
fn("int XDisplayKeycodes(Display*, int*, int*)")
fn("int XDrawArc(Display*, Drawable, GC, int, int, unsigned int, unsigned int, int, int)")
fn("int XDrawArcs(Display*, Drawable, GC, XArc*, int)")
fn("int XDrawImageString(Display*, Drawable, GC, int, int, const char*, int)")
fn("int XDrawLine(Display*, Drawable, GC, int, int, int, int)")
fn("int XDrawLines(Display*, Drawable, GC, XPoint*, int, int)")
fn("int XDrawPoint(Display*, Drawable, GC, int, int)")
fn("int XDrawPoints(Display*, Drawable, GC, XPoint*, int, int)")
fn("int XDrawRectangle(Display*, Drawable, GC, int, int, unsigned int, unsigned int)")
fn("int XDrawSegments(Display*, Drawable, GC, XSegment*, int)")
fn("int XDrawString(Display*, Drawable, GC, int, int, const char*, int)")
fn("int XEmptyRegion(Region)")
fn("int XEnableAccessControl(Display*)")
fn("int XEqualRegion(Region, Region)")
fn("int XFetchName(Display*, Window, char**)")
fn("int XFillArc(Display*, Drawable, GC, int, int, unsigned int, unsigned int, int, int)")
fn("int XFillArcs(Display*, Drawable, GC, XArc*, int)")
fn("int XFillPolygon(Display*, Drawable, GC, XPoint*, int, int, int)")
fn("int XFillRectangles(Display*, Drawable, GC, XRectangle*, int)")
fn("int XFindContext(Display*, XID, XContext, char**)")
fn("int XFontsOfFontSet(XFontSet, XFontStruct***, char***)")
fn("int XFreeColors(Display*, Colormap, long unsigned int*, int, long unsigned int)")
fn("int XFreeModifiermap(XModifierKeymap*)")
fn("int XGetClassHint(Display*, Window, XClassHint*)")
fn("int XGetFontProperty(XFontStruct*, Atom, long unsigned int*)")
fn("int XGetGCValues(Display*, GC, long unsigned int, XGCValues*)")
fn("int XGetGeometry(Display*, Drawable, Window*, int*, int*, unsigned int*, unsigned int*, unsigned int*, unsigned int*)")
fn("int XGetInputFocus(Display*, Window*, int*)")
fn("int XGetRGBColormaps(Display*, Window, XStandardColormap**, int*, Atom)")
fn("int XGetWindowAttributes(Display*, Window, XWindowAttributes*)")
fn("int XGetWMClientMachine(Display*, Window, XTextProperty*)")
fn("int XGetWMName(Display*, Window, XTextProperty*)")
fn("int XGetWMNormalHints(Display*, Window, XSizeHints*, long int*)")
fn("int XGetWMProtocols(Display*, Window, Atom**, int*)")
fn("int XGrabButton(Display*, unsigned int, unsigned int, Window, int, unsigned int, int, int, Window, Cursor)")
fn("int XGrabKeyboard(Display*, Window, int, int, int, Time)")
fn("int XGrabKey(Display*, int, unsigned int, Window, int, int, int)")
fn("int XInternAtoms(Display*, char**, int, int, Atom*)")
fn("int XIntersectRegion(Region, Region, Region)")
fn("int XKillClient(Display*, XID)")
fn("int* XListDepths(Display*, int, int*)")
fn("int XLookupColor(Display*, Colormap, const char*, XColor*, XColor*)")
fn("int XLowerWindow(Display*, Window)")
fn("int XMapSubwindows(Display*, Window)")
fn("int XmbLookupString(XIC, XKeyPressedEvent*, char*, int, KeySym*, int*)")
fn("int XmbTextEscapement(XFontSet, const char*, int)")
fn("int XmbTextListToTextProperty(Display*, char**, int, XICCEncodingStyle, XTextProperty*)")
fn("int XmbTextPropertyToTextList(Display*, const XTextProperty*, char***, int*)")
fn("int XParseColor(Display*, Colormap, const char*, XColor*)")
fn("int XPutBackEvent(Display*, XEvent*)")
fn("int XQueryColor(Display*, Colormap, XColor*)")
fn("int XQueryColors(Display*, Colormap, XColor*, int)")
fn("int XRaiseWindow(Display*, Window)")
fn("int XReadBitmapFileData(const char*, unsigned int*, unsigned int*, unsigned char**, int*, int*)")
fn("int XRecolorCursor(Display*, Cursor, XColor*, XColor*)")
fn("int XRectInRegion(Region, int, int, unsigned int, unsigned int)")
fn("int XRefreshKeyboardMapping(XMappingEvent*)")
fn("int XRemoveHost(Display*, XHostAddress*)")
fn("int XReparentWindow(Display*, Window, Window, int, int)")
fn("int XRotateBuffers(Display*, int)")
fn("int XSaveContext(Display*, XID, XContext, const char*)")
fn("int XScreenNumberOfScreen(Screen*)")
fn("int XSetArcMode(Display*, GC, int)")
fn("int XSetBackground(Display*, GC, long unsigned int)")
fn("int XSetClipMask(Display*, GC, Pixmap)")
fn("int XSetClipOrigin(Display*, GC, int, int)")
fn("int XSetClipRectangles(Display*, GC, int, int, XRectangle*, int, int)")
fn("int XSetCloseDownMode(Display*, int)")
fn("int XSetCommand(Display*, Window, char**, int)")
fn("int XSetDashes(Display*, GC, int, const char*, int)")
fn("int XSetFillRule(Display*, GC, int)")
fn("int XSetFillStyle(Display*, GC, int)")
fn("int XSetFont(Display*, GC, Font)")
fn("int XSetForeground(Display*, GC, long unsigned int)")
fn("int XSetFunction(Display*, GC, int)")
fn("int XSetGraphicsExposures(Display*, GC, int)")
fn("int XSetIconSizes(Display*, Window, XIconSize*, int)")
fn("int XSetInputFocus(Display*, Window, int, Time)")
fn("int XSetLineAttributes(Display*, GC, unsigned int, int, int, int)")
fn("int XSetPlaneMask(Display*, GC, long unsigned int)")
fn("int XSetRegion(Display*, GC, Region)")
fn("int XSetSelectionOwner(Display*, Atom, Window, Time)")
fn("int XSetStipple(Display*, GC, Pixmap)")
fn("int XSetSubwindowMode(Display*, GC, int)")
fn("int XSetTile(Display*, GC, Pixmap)")
fn("int XSetTSOrigin(Display*, GC, int, int)")
fn("int XSetWindowBackground(Display*, Window, long unsigned int)")
fn("int XSetWindowBackgroundPixmap(Display*, Window, Pixmap)")
fn("int XSetWindowBorder(Display*, Window, long unsigned int)")
fn("int XSetWindowBorderPixmap(Display*, Window, Pixmap)")
fn("int XSetWindowBorderWidth(Display*, Window, unsigned int)")
fn("int XSetWMHints(Display*, Window, XWMHints*)")
fn("int XStoreBytes(Display*, const char*, int)")
fn("int XStoreColors(Display*, Colormap, XColor*, int)")
fn("int XStoreName(Display*, Window, const char*)")
fn("int XSubtractRegion(Region, Region, Region)")
fn("int XSupportsLocale()")
fn("int XTextWidth16(XFontStruct*, const XChar2b*, int)")
fn("int XTextWidth(XFontStruct*, const char*, int)")
fn("int XUngrabButton(Display*, unsigned int, unsigned int, Window)")
fn("int XUngrabKeyboard(Display*, Time)")
fn("int XUngrabKey(Display*, int, unsigned int, Window)")
fn("int XUnionRectWithRegion(XRectangle*, Region, Region)")
fn("int XUnionRegion(Region, Region, Region)")
fn("int XUnloadFont(Display*, Font)")
fn("int XUnmapSubwindows(Display*, Window)")
fn("int Xutf8TextListToTextProperty(Display*, char**, int, XICCEncodingStyle, XTextProperty*)")
fn("int Xutf8TextPropertyToTextList(Display*, const XTextProperty*, char***, int*)")
fn("int XwcLookupString(XIC, XKeyPressedEvent*, wchar_t*, int, KeySym*, int*)")
fn("int XwcTextEscapement(XFontSet, const wchar_t*, int)")
fn("int XwcTextListToTextProperty(Display*, wchar_t**, int, XICCEncodingStyle, XTextProperty*)")
fn("int XwcTextPropertyToTextList(Display*, const XTextProperty*, wchar_t***, int*)")
fn("int XWithdrawWindow(Display*, Window, int)")
fn("int XWMGeometry(Display*, int, const char*, const char*, unsigned int, XSizeHints*, int*, int*, int*, int*, int*)")
fn("KeySym* XGetKeyboardMapping(Display*, KeyCode, int, int*)")
fn("KeySym XStringToKeysym(const char*)")
fn("long int XExtendedMaxRequestSize(Display*)")
fn("long int XMaxRequestSize(Display*)")
fn("long unsigned int XNextRequest(Display*)")
fn("Pixmap XCreatePixmapFromBitmapData(Display*, Drawable, char*, unsigned int, unsigned int, long unsigned int, long unsigned int, unsigned int)")
fn("VisualID XVisualIDFromVisual(Visual*)")
fn("Visual* XDefaultVisual(Display*, int)")
fn("void XConvertCase(KeySym, KeySym*, KeySym*)")
fn("void XFreeFontSet(Display*, XFontSet)")
fn("void XFreeStringList(char**)")
fn("void XmbDrawImageString(Display*, Drawable, XFontSet, GC, int, int, const char*, int)")
fn("void XmbDrawString(Display*, Drawable, XFontSet, GC, int, int, const char*, int)")
fn("void XProcessInternalConnection(Display*, int)")
fn("void XrmInitialize()")
fn("void XSetAuthorization(char*, int, char*, int)")
fn("void XSetRGBColormaps(Display*, Window, XStandardColormap*, int, Atom)")
fn("void XSetWMIconName(Display*, Window, XTextProperty*)")
fn("void XSetWMName(Display*, Window, XTextProperty*)")
fn("void XSetWMProperties(Display*, Window, XTextProperty*, XTextProperty*, char**, int, XSizeHints*, XWMHints*, XClassHint*)")
fn("void XUnsetICFocus(XIC)")
fn("void XwcDrawImageString(Display*, Drawable, XFontSet, GC, int, int, const wchar_t*, int)")
fn("void XwcDrawString(Display*, Drawable, XFontSet, GC, int, int, const wchar_t*, int)")
fn("void XwcFreeStringList(wchar_t**)")
fn("Window XCreateSimpleWindow(Display*, Window, int, int, unsigned int, unsigned int, unsigned int, long unsigned int, long unsigned int)")
fn("Window XDefaultRootWindow(Display*)")
fn("Window XGetSelectionOwner(Display*, Atom)")
fn("Window XRootWindow(Display*, int)")
fn("XExtCodes* XAddExtension(Display*)")
fn("XExtCodes* XInitExtension(Display*, const char*)")
fn("XFontSetExtents* XExtentsOfFontSet(XFontSet)")
fn("XFontStruct* XQueryFont(Display*, XID)")
fn("XHostAddress* XListHosts(Display*, int*, int*)")
fn("XIconSize* XAllocIconSize()")
fn("XModifierKeymap* XGetModifierMapping(Display*)")
fn("_XOC* XCreateFontSet(Display*, const char*, char***, int*, char**)")
fn("XPixmapFormatValues* XListPixmapFormats(Display*, int*)")
fn("_XRegion* XCreateRegion()")
fn("XSizeHints* XAllocSizeHints()")
fn("XStandardColormap* XAllocStandardColormap()")
fn("XVisualInfo* XGetVisualInfo(Display*, long int, XVisualInfo*, int*)")
fn("XWMHints* XGetWMHints(Display*, Window)")


#Display *XOpenDisplay(char *display_name);
function("XOpenDisplay");
returns("Display *");
arg("const char *");

#Colormap XCreateColormap(Display *display, Window w, Visual *visual, int alloc);
function("XCreateColormap");
returns("Colormap");
arg("Display *");
arg("Window");
arg("Visual *");
arg("int");

#Window XCreateWindow(Display *display, Window parent, int x, int y, unsigned int width, unsigned int height, unsigned int border_width, int depth, 
#unsigned int class, Visual *visual, unsigned long valuemask, XSetWindowAttributes *attributes);
function("XCreateWindow");
returns("Window");
arg("Display *");
arg("Window");
arg("int")
arg("int")
arg("unsigned int")
arg("unsigned int")
arg("unsigned int")
arg("int")
arg("unsigned int")
arg("Visual *")
arg("unsigned long")
arg("XSetWindowAttributes *")

#int XMapWindow(Display *display, Window w);
function("XMapWindow");
returns("int");
arg("Display *");
arg("Window")


#
function("XChangeProperty")
returns("int")
arg("Display *")
arg("Window")
arg("Atom")
arg("Atom")
arg("int")
arg("int")
arg("const unsigned char *")
arg("int")

#
function("XCloseDisplay")
returns("int")
arg("Display *")

#
function("XDestroyWindow")
returns("int")
arg("Display *")
arg("Window")

#
function("XFree")
returns("int")
arg("void*")

#
function("XInternAtom")
returns("Atom")
arg("Display *")
arg("const char *")
arg("Bool")

#
function("XLookupKeysym")
returns("KeySym")
arg("XKeyEvent *")
arg("int")

#
function("XLookupString")
returns("int")
arg("XKeyEvent *")
arg("char *")
arg("int")
arg("KeySym *")
arg("XComposeStatus*")

#
function("XNextEvent")
returns("int")
arg("Display *")
arg("XEvent *")

#
function("XParseGeometry")
returns("int")
arg("const char *")
arg("int *")
arg("int *")
arg("unsigned int *")
arg("unsigned int *")

#
function("XPending")
returns("int")
arg("Display *")

#
function("XSetNormalHints")
returns("int")
arg("Display *")
arg("Window")
arg("XSizeHints *")

#
function("XSetStandardProperties")
returns("int")
arg("Display *")
arg("Window")
arg("const char *")
arg("const char *")
arg("Pixmap")
arg("char **")
arg("int")
arg("XSizeHints *")

########
########
########

fn("char* XGetICValues(XIC, ...)"); nothunkmap(); noforward(); nothunk()
fn("char* XGetICValues_internal(XIC, size_t, unsigned long*)"); noinit(); noload()

fn("_XIC* XCreateIC(XIM, ...)"); nothunkmap(); noforward(); nothunk()
fn("_XIC* XCreateIC_internal(XIM, size_t, unsigned long*)"); noinit(); noload()

fn("Atom XInternAtom(Display*, const char*, int)")
fn("char** XListExtensions(Display*, int*)")
fn("char* XSetLocaleModifiers(const char*)")
fn("Colormap XCreateColormap(Display*, Window, Visual*, int)")
fn("Cursor XCreatePixmapCursor(Display*, Pixmap, Pixmap, XColor*, XColor*, unsigned int, unsigned int)")
fn("Display* XOpenDisplay(const char*)")
fn("int XChangeProperty(Display*, Window, Atom, Atom, int, int, const unsigned char*, int)")
fn("int XCloseDisplay(Display*)")
fn("int XCloseIM(XIM)")
fn("int XDefineCursor(Display*, Window, Cursor)")
fn("int XDestroyWindow(Display*, Window)")
fn("int XDrawString16(Display*, Drawable, GC, int, int, const XChar2b*, int)")
fn("int XEventsQueued(Display*, int)")
fn("int XFillRectangle(Display*, Drawable, GC, int, int, unsigned int, unsigned int)")
fn("int XFilterEvent(XEvent*, Window)")
fn("int XFlush(Display*)")
fn("int XFreeColormap(Display*, Colormap)")
fn("int XFreeCursor(Display*, Cursor)")
fn("int XFreeExtensionList(char**)")
fn("int XFreeFont(Display*, XFontStruct*)")
fn("int XFreeGC(Display*, GC)")
fn("int XFreePixmap(Display*, Pixmap)")
fn("int XFree(void*)")
fn("int XGetErrorDatabaseText(Display*, const char*, const char*, const char*, char*, int)")
fn("int XGetErrorText(Display*, int, char*, int)")
fn("int XGetEventData(Display*, XGenericEventCookie*)")
fn("int XGetWindowProperty(Display*, Window, Atom, long int, long int, int, Atom, Atom*, int*, long unsigned int*, long unsigned int*, unsigned char**)")
fn("int XGrabPointer(Display*, Window, int, unsigned int, int, int, Window, Cursor, Time)")
fn("int XGrabServer(Display*)")
fn("int XIconifyWindow(Display*, Window, int)")
fn("int XIfEvent(Display*, XEvent*, XIfEventFN*, XPointer)")
fn("int XInitThreads()")
fn("int XLookupString(XKeyEvent*, char*, int, KeySym*, XComposeStatus*)")
fn("int XMapRaised(Display*, Window)")
fn("int XMoveResizeWindow(Display*, Window, int, int, unsigned int, unsigned int)")
fn("int XMoveWindow(Display*, Window, int, int)")
fn("int XNextEvent(Display*, XEvent*)")
fn("int XPeekEvent(Display*, XEvent*)")
fn("int XPending(Display*)")
fn("int XQueryExtension(Display*, const char*, int*, int*, int*)")
fn("int XQueryPointer(Display*, Window, Window*, Window*, int*, int*, int*, int*, unsigned int*)")
fn("int XQueryTree(Display*, Window, Window*, Window*, Window**, unsigned int*)")
fn("int XResetScreenSaver(Display*)")
fn("int XResizeWindow(Display*, Window, unsigned int, unsigned int)")
fn("int XSelectInput(Display*, Window, long int)")
fn("int XSendEvent(Display*, Window, int, long int, XEvent*)")
fn("XSetErrorHandlerFN* XSetErrorHandler(XErrorHandler)")
fn("int XSetTransientForHint(Display*, Window, Window)")
fn("int XSetWMProtocols(Display*, Window, Atom*, int)")
fn("int XSync(Display*, int)")
fn("int XTextExtents16(XFontStruct*, const XChar2b*, int, int*, int*, int*, XCharStruct*)")
fn("int XTranslateCoordinates(Display*, Window, Window, int, int, int*, int*, Window*)")
fn("int XUngrabPointer(Display*, Time)")
fn("int XUngrabServer(Display*)")
fn("int XUnmapWindow(Display*, Window)")
fn("int Xutf8LookupString(XIC, XKeyPressedEvent*, char*, int, KeySym*, int*)")
fn("int XWarpPointer(Display*, Window, Window, int, int, unsigned int, unsigned int, int, int)")
fn("int XWindowEvent(Display*, Window, long int, XEvent*)")
fn("Pixmap XCreateBitmapFromData(Display*, Drawable, const char*, unsigned int, unsigned int)")
fn("Pixmap XCreatePixmap(Display*, Drawable, unsigned int, unsigned int, unsigned int)")
fn("void XDestroyIC(XIC)")
fn("void XFreeEventData(Display*, XGenericEventCookie*)")
fn("void XLockDisplay(Display*)")
fn("void XSetICFocus(XIC)")
fn("void XSetWMNormalHints(Display*, Window, XSizeHints*)")
fn("void XUnlockDisplay(Display*)")
fn("void Xutf8SetWMProperties(Display*, Window, const char*, const char*, char**, int, XSizeHints*, XWMHints*, XClassHint*)")
fn("Window XCreateWindow(Display*, Window, int, int, unsigned int, unsigned int, unsigned int, int, unsigned int, Visual*, long unsigned int, XSetWindowAttributes*)")
fn("XFontStruct* XLoadQueryFont(Display*, const char*)")
fn("_XGC* XCreateGC(Display*, Drawable, long unsigned int, XGCValues*)")
fn("XImage* XGetImage(Display*, Drawable, int, int, unsigned int, unsigned int, long unsigned int, int)")
fn("_XIM* XOpenIM(Display*, _XrmHashBucketRec*, char*, char*)")
fn("KeySym XkbKeycodeToKeysym(Display *, KeyCode, unsigned int, unsigned int)")
fn("Bool XCheckWindowEvent(Display *, Window, long, XEvent *)")
fn("int XDefineCursor(Display *, Window, Cursor)")
fn("int XUndefineCursor(Display *, Window)")
fn("Screen *XDefaultScreenOfDisplay( Display* )")
fn("int XDefaultScreen(Display*)")
fn("int XDisplayWidth(Display*, int)")
fn("int XMatchVisualInfo(Display*, int, int, int, XVisualInfo*)")
fn("int XPutImage(Display*, Drawable, GC, XImage*, int, int, int, int, unsigned int, unsigned int)")
fn("XImage* XCreateImage(Display*, Visual*, unsigned int, int, int, char*, unsigned int, unsigned int, int, int)")
fn("int XDisplayHeight(Display*, int)")


Generate()